[workspace]
resolver = "2"
members = ["gateway"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/nikvoss/jumpgate"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
