[workspace]
resolver = "2"
members = ["gateway", "mesh", "workers/ssh-proxy"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/trevex/jumpgate"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
