// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_requests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeGrantIDsForUserAsset = `-- name: ActiveGrantIDsForUserAsset :many
SELECT id FROM access_grants
WHERE subject_user_id = $1 AND scope_asset_id = $2
  AND revoked_at IS NULL AND expires_at > now()
`

type ActiveGrantIDsForUserAssetParams struct {
	SubjectUserID uuid.UUID `json:"subject_user_id"`
	ScopeAssetID  uuid.UUID `json:"scope_asset_id"`
}

// Active (unrevoked, unexpired) grants for a subject on an asset. Used to attribute
// a JIT session to its grant when exactly one is active.
func (q *Queries) ActiveGrantIDsForUserAsset(ctx context.Context, arg ActiveGrantIDsForUserAssetParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeGrantIDsForUserAsset, arg.SubjectUserID, arg.ScopeAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addApproval = `-- name: AddApproval :one
INSERT INTO access_request_approvals (request_id, approver_user_id, decision)
VALUES ($1, $2, $3)
RETURNING id, request_id, approver_user_id, decision, created_at
`

type AddApprovalParams struct {
	RequestID      uuid.UUID `json:"request_id"`
	ApproverUserID uuid.UUID `json:"approver_user_id"`
	Decision       string    `json:"decision"`
}

func (q *Queries) AddApproval(ctx context.Context, arg AddApprovalParams) (AccessRequestApproval, error) {
	row := q.db.QueryRow(ctx, addApproval, arg.RequestID, arg.ApproverUserID, arg.Decision)
	var i AccessRequestApproval
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ApproverUserID,
		&i.Decision,
		&i.CreatedAt,
	)
	return i, err
}

const countApprovals = `-- name: CountApprovals :one
SELECT count(*) FROM access_request_approvals WHERE request_id = $1 AND decision = 'approve'
`

func (q *Queries) CountApprovals(ctx context.Context, requestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovals, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessGrant = `-- name: CreateAccessGrant :one
INSERT INTO access_grants (request_id, role_id, scope_asset_id, subject_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason
`

type CreateAccessGrantParams struct {
	RequestID     uuid.UUID `json:"request_id"`
	RoleID        uuid.UUID `json:"role_id"`
	ScopeAssetID  uuid.UUID `json:"scope_asset_id"`
	SubjectUserID uuid.UUID `json:"subject_user_id"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateAccessGrant(ctx context.Context, arg CreateAccessGrantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, createAccessGrant,
		arg.RequestID,
		arg.RoleID,
		arg.ScopeAssetID,
		arg.SubjectUserID,
		arg.ExpiresAt,
	)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RoleID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
	)
	return i, err
}

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at
`

type CreateAccessRequestParams struct {
	RequesterUserID   uuid.UUID       `json:"requester_user_id"`
	RoleID            uuid.UUID       `json:"role_id"`
	AssetID           uuid.UUID       `json:"asset_id"`
	Reason            string          `json:"reason"`
	RequestedDuration pgtype.Interval `json:"requested_duration"`
	RequiredApprovals int32           `json:"required_approvals"`
	GrantedDuration   pgtype.Interval `json:"granted_duration"`
	Status            string          `json:"status"`
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.RequesterUserID,
		arg.RoleID,
		arg.AssetID,
		arg.Reason,
		arg.RequestedDuration,
		arg.RequiredApprovals,
		arg.GrantedDuration,
		arg.Status,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.RoleID,
		&i.AssetID,
		&i.Reason,
		&i.RequestedDuration,
		&i.RequiredApprovals,
		&i.GrantedDuration,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const expireGrants = `-- name: ExpireGrants :many
UPDATE access_grants SET revoked_at = now(), revoked_reason = 'expired'
WHERE revoked_at IS NULL AND expires_at <= now()
RETURNING id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason
`

func (q *Queries) ExpireGrants(ctx context.Context) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, expireGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccessRequestForUpdate = `-- name: GetAccessRequestForUpdate :one
SELECT id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at FROM access_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccessRequestForUpdate(ctx context.Context, id uuid.UUID) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequestForUpdate, id)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.RoleID,
		&i.AssetID,
		&i.Reason,
		&i.RequestedDuration,
		&i.RequiredApprovals,
		&i.GrantedDuration,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getGrant = `-- name: GetGrant :one
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants WHERE id = $1
`

func (q *Queries) GetGrant(ctx context.Context, id uuid.UUID) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, getGrant, id)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RoleID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
	)
	return i, err
}

const getGrantByRequest = `-- name: GetGrantByRequest :one
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants WHERE request_id = $1
`

func (q *Queries) GetGrantByRequest(ctx context.Context, requestID uuid.UUID) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, getGrantByRequest, requestID)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RoleID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
	)
	return i, err
}

const isUserActive = `-- name: IsUserActive :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1 AND deactivated_at IS NULL)
`

func (q *Queries) IsUserActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccessRequestsByRequester = `-- name: ListAccessRequestsByRequester :many
SELECT id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at FROM access_requests WHERE requester_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccessRequestsByRequester(ctx context.Context, requesterUserID uuid.UUID) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsByRequester, requesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
			&i.Reason,
			&i.RequestedDuration,
			&i.RequiredApprovals,
			&i.GrantedDuration,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessRequestsByRequesterPaged = `-- name: ListAccessRequestsByRequesterPaged :many
SELECT id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at FROM access_requests
WHERE requester_user_id = $1::uuid
  AND (
    $2::timestamptz IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id > $3::uuid)
  )
ORDER BY created_at DESC, id
LIMIT $4
`

type ListAccessRequestsByRequesterPagedParams struct {
	RequesterUserID uuid.UUID          `json:"requester_user_id"`
	AfterTs         pgtype.Timestamptz `json:"after_ts"`
	AfterID         pgtype.UUID        `json:"after_id"`
	Lim             int32              `json:"lim"`
}

// Keyset pagination for (created_at DESC, id ASC). A row-comparison
// `(created_at,id) < (…)` is WRONG for DESC+ASC — use the explicit predicate.
func (q *Queries) ListAccessRequestsByRequesterPaged(ctx context.Context, arg ListAccessRequestsByRequesterPagedParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsByRequesterPaged,
		arg.RequesterUserID,
		arg.AfterTs,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
			&i.Reason,
			&i.RequestedDuration,
			&i.RequiredApprovals,
			&i.GrantedDuration,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsBySubject = `-- name: ListGrantsBySubject :many
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants WHERE subject_user_id = $1 ORDER BY granted_at DESC
`

func (q *Queries) ListGrantsBySubject(ctx context.Context, subjectUserID uuid.UUID) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsBySubject, subjectUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsBySubjectPaged = `-- name: ListGrantsBySubjectPaged :many
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants
WHERE subject_user_id = $1::uuid
  AND (
    $2::timestamptz IS NULL
    OR granted_at < $2
    OR (granted_at = $2 AND id > $3::uuid)
  )
ORDER BY granted_at DESC, id
LIMIT $4
`

type ListGrantsBySubjectPagedParams struct {
	SubjectUserID uuid.UUID          `json:"subject_user_id"`
	AfterTs       pgtype.Timestamptz `json:"after_ts"`
	AfterID       pgtype.UUID        `json:"after_id"`
	Lim           int32              `json:"lim"`
}

// Keyset pagination on (granted_at DESC, id ASC) for caller-scoped grants.
func (q *Queries) ListGrantsBySubjectPaged(ctx context.Context, arg ListGrantsBySubjectPagedParams) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsBySubjectPaged,
		arg.SubjectUserID,
		arg.AfterTs,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsFiltered = `-- name: ListGrantsFiltered :many
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants
WHERE ($1::uuid IS NULL OR subject_user_id = $1::uuid)
  AND (NOT $2::bool OR (revoked_at IS NULL AND expires_at > now()))
ORDER BY granted_at DESC
`

type ListGrantsFilteredParams struct {
	SubjectUserID pgtype.UUID `json:"subject_user_id"`
	ActiveOnly    bool        `json:"active_only"`
}

// Admin listing: all grants (active + past), optionally narrowed to a subject
// and/or to active-only. sqlc.narg(subject_user_id) NULL => any subject;
// active_only=false => include revoked/expired.
func (q *Queries) ListGrantsFiltered(ctx context.Context, arg ListGrantsFilteredParams) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsFiltered, arg.SubjectUserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsFilteredPaged = `-- name: ListGrantsFilteredPaged :many
SELECT id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason FROM access_grants
WHERE ($1::uuid IS NULL OR subject_user_id = $1::uuid)
  AND (NOT $2::bool OR (revoked_at IS NULL AND expires_at > now()))
  AND (
    $3::timestamptz IS NULL
    OR granted_at < $3
    OR (granted_at = $3 AND id > $4::uuid)
  )
ORDER BY granted_at DESC, id
LIMIT $5
`

type ListGrantsFilteredPagedParams struct {
	SubjectUserID pgtype.UUID        `json:"subject_user_id"`
	ActiveOnly    bool               `json:"active_only"`
	AfterTs       pgtype.Timestamptz `json:"after_ts"`
	AfterID       pgtype.UUID        `json:"after_id"`
	Lim           int32              `json:"lim"`
}

// Admin listing with keyset pagination on (granted_at DESC, id ASC). Filters
// are all optional (null subject => any subject; active_only=false => all).
func (q *Queries) ListGrantsFilteredPaged(ctx context.Context, arg ListGrantsFilteredPagedParams) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsFilteredPaged,
		arg.SubjectUserID,
		arg.ActiveOnly,
		arg.AfterTs,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at FROM access_requests WHERE status = 'pending' ORDER BY created_at DESC
`

func (q *Queries) ListPendingRequests(ctx context.Context) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
			&i.Reason,
			&i.RequestedDuration,
			&i.RequiredApprovals,
			&i.GrantedDuration,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsByAsset = `-- name: ListPendingRequestsByAsset :many
SELECT id, requester_user_id, role_id, asset_id
FROM access_requests
WHERE status = 'pending' AND asset_id = $1
`

type ListPendingRequestsByAssetRow struct {
	ID              uuid.UUID `json:"id"`
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	RoleID          uuid.UUID `json:"role_id"`
	AssetID         uuid.UUID `json:"asset_id"`
}

func (q *Queries) ListPendingRequestsByAsset(ctx context.Context, assetID uuid.UUID) ([]ListPendingRequestsByAssetRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsByAssetRow
	for rows.Next() {
		var i ListPendingRequestsByAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsByRole = `-- name: ListPendingRequestsByRole :many
SELECT id, requester_user_id, role_id, asset_id
FROM access_requests
WHERE status = 'pending' AND role_id = $1
`

type ListPendingRequestsByRoleRow struct {
	ID              uuid.UUID `json:"id"`
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	RoleID          uuid.UUID `json:"role_id"`
	AssetID         uuid.UUID `json:"asset_id"`
}

func (q *Queries) ListPendingRequestsByRole(ctx context.Context, roleID uuid.UUID) ([]ListPendingRequestsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsByRoleRow
	for rows.Next() {
		var i ListPendingRequestsByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsPaged = `-- name: ListPendingRequestsPaged :many
SELECT id, requester_user_id, role_id, asset_id, reason, requested_duration, required_approvals, granted_duration, status, created_at, resolved_at FROM access_requests
WHERE status = 'pending'
  AND (
    $1::timestamptz IS NULL
    OR created_at < $1
    OR (created_at = $1 AND id > $2::uuid)
  )
ORDER BY created_at DESC, id
LIMIT $3
`

type ListPendingRequestsPagedParams struct {
	AfterTs pgtype.Timestamptz `json:"after_ts"`
	AfterID pgtype.UUID        `json:"after_id"`
	Lim     int32              `json:"lim"`
}

// Keyset pagination for pending requests (created_at DESC, id ASC).
func (q *Queries) ListPendingRequestsPaged(ctx context.Context, arg ListPendingRequestsPagedParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsPaged, arg.AfterTs, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
			&i.Reason,
			&i.RequestedDuration,
			&i.RequiredApprovals,
			&i.GrantedDuration,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveGrantsForRole = `-- name: RevokeActiveGrantsForRole :many
UPDATE access_grants SET revoked_at = now(), revoked_by = $2, revoked_reason = $3
WHERE role_id = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason
`

type RevokeActiveGrantsForRoleParams struct {
	RoleID        uuid.UUID   `json:"role_id"`
	RevokedBy     pgtype.UUID `json:"revoked_by"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

// Revokes a role's still-live grants (not yet revoked, not yet expired) so the
// terminator can tear down the sessions they authorized. Used by the DeleteRole
// cascade before the role row (and, via FK cascade, these grant rows) is deleted.
func (q *Queries) RevokeActiveGrantsForRole(ctx context.Context, arg RevokeActiveGrantsForRoleParams) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, revokeActiveGrantsForRole, arg.RoleID, arg.RevokedBy, arg.RevokedReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveGrantsForUser = `-- name: RevokeActiveGrantsForUser :many
UPDATE access_grants SET revoked_at = now(), revoked_by = $2, revoked_reason = $3
WHERE subject_user_id = $1 AND revoked_at IS NULL
RETURNING id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason
`

type RevokeActiveGrantsForUserParams struct {
	SubjectUserID uuid.UUID   `json:"subject_user_id"`
	RevokedBy     pgtype.UUID `json:"revoked_by"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeActiveGrantsForUser(ctx context.Context, arg RevokeActiveGrantsForUserParams) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, revokeActiveGrantsForUser, arg.SubjectUserID, arg.RevokedBy, arg.RevokedReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGrant = `-- name: RevokeGrant :one
UPDATE access_grants SET revoked_at = now(), revoked_by = $2, revoked_reason = $3
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, request_id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_by, revoked_reason
`

type RevokeGrantParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedBy     pgtype.UUID `json:"revoked_by"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

// Predicate is revoked_at IS NULL only (NOT the derived "active" filter with
// expires_at): a grant past expiry but not yet reaped is still revocable so the
// deactivation cascade can stamp a reason/actor on it. Authz already excludes it
// (expires_at > now() is false everywhere), so this is harmless.
func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, revokeGrant, arg.ID, arg.RevokedBy, arg.RevokedReason)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RoleID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
	)
	return i, err
}

const setAccessRequestStatus = `-- name: SetAccessRequestStatus :exec
UPDATE access_requests SET status = $1, resolved_at = $2 WHERE id = $3
`

type SetAccessRequestStatusParams struct {
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) SetAccessRequestStatus(ctx context.Context, arg SetAccessRequestStatusParams) error {
	_, err := q.db.Exec(ctx, setAccessRequestStatus, arg.Status, arg.ResolvedAt, arg.ID)
	return err
}
