// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allFolderIDs = `-- name: AllFolderIDs :many
SELECT id FROM folders
`

// allFolderIDs: every folder id (root+cascade candidate set = the whole tree).
func (q *Queries) AllFolderIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, allFolderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anchorHomeFolders = `-- name: AnchorHomeFolders :many
WITH held_folder_caps(folder_id, scope, action, qualifier) AS (
    SELECT h.object_id, rc.scope, rc.action, rc.qualifier
    FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
    WHERE h.object_kind = 'folder'
),
global_caps(scope, action, qualifier) AS (
    SELECT rc.scope, rc.action, rc.qualifier
    FROM authz_global_held($1) gh JOIN role_capabilities rc ON rc.role_id = gh.role_id
),
mgmt_role_folders(folder_id) AS (
    SELECT DISTINCT nf.id
    FROM held_folder_caps hf
    JOIN folders mf ON mf.id = hf.folder_id
    JOIN folders nf ON nf.path_ids <@ mf.path_ids
    WHERE (hf.scope = 'access' OR hf.scope = '*')
      AND (hf.action = 'role' OR hf.action = '*')
      AND (hf.qualifier = 'read' OR hf.qualifier = '*')
),
mgmt_group_folders(folder_id) AS (
    SELECT DISTINCT nf.id
    FROM held_folder_caps hf
    JOIN folders mf ON mf.id = hf.folder_id
    JOIN folders nf ON nf.path_ids <@ mf.path_ids
    WHERE (hf.scope = 'identity' OR hf.scope = '*')
      AND (hf.action = 'group' OR hf.action = '*')
      AND (hf.qualifier = 'read' OR hf.qualifier = '*')
),
mgmt_asset_folders(folder_id) AS (
    SELECT DISTINCT nf.id
    FROM held_folder_caps hf
    JOIN folders mf ON mf.id = hf.folder_id
    JOIN folders nf ON nf.path_ids <@ mf.path_ids
    WHERE (hf.scope = 'catalog' OR hf.scope = '*')
      AND (hf.action = 'asset' OR hf.action = '*')
      AND (hf.qualifier = 'read' OR hf.qualifier = '*')
)
SELECT DISTINCT r.folder_id AS folder_id
FROM roles r
JOIN folders nf ON nf.id = r.folder_id
WHERE r.id = ANY($2::uuid[])
   OR EXISTS (SELECT 1 FROM global_caps c
              WHERE (c.scope = 'access' OR c.scope = '*')
                AND (c.action = 'role' OR c.action = '*')
                AND (c.qualifier = 'read' OR c.qualifier = '*'))
   OR nf.id IN (SELECT folder_id FROM mgmt_role_folders)
UNION
SELECT DISTINCT g.folder_id AS folder_id
FROM groups g
JOIN folders nf ON nf.id = g.folder_id
WHERE g.id = ANY($3::uuid[])
   OR EXISTS (SELECT 1 FROM global_caps c
              WHERE (c.scope = 'identity' OR c.scope = '*')
                AND (c.action = 'group' OR c.action = '*')
                AND (c.qualifier = 'read' OR c.qualifier = '*'))
   OR nf.id IN (SELECT folder_id FROM mgmt_group_folders)
UNION
SELECT DISTINCT a.folder_id AS folder_id
FROM assets a
WHERE a.id = ANY($4::uuid[])
   OR EXISTS (SELECT 1 FROM global_caps c
              WHERE (c.scope = 'catalog' OR c.scope = '*')
                AND (c.action = 'asset' OR c.action = '*')
                AND (c.qualifier = 'read' OR c.qualifier = '*'))
   OR a.folder_id IN (SELECT folder_id FROM mgmt_asset_folders)
   OR EXISTS (
        SELECT 1 FROM ssh_asset_login sal
        WHERE sal.asset_id = a.id
          AND EXISTS (
              SELECT 1 FROM role_capabilities rc
              WHERE rc.role_id IN (
                    SELECT role_id FROM authz_global_held($1)
                  UNION
                    SELECT h.role_id FROM authz_held($1) h
                    WHERE (h.object_kind = 'asset' AND h.object_id = a.id)
                       OR (h.object_kind = 'folder'
                           AND h.object_id IN (
                               SELECT f.id FROM folders f
                               WHERE f.path_ids @> (SELECT af.path_ids FROM folders af WHERE af.id = a.folder_id)
                           ))
              )
              AND (rc.scope = 'ssh' OR rc.scope = '*')
              AND (rc.action = 'login' OR rc.action = '*')
              AND (rc.qualifier = sal.login OR rc.qualifier = '*')
          )
   )
`

type AnchorHomeFoldersParams struct {
	User        uuid.UUID   `json:"user"`
	RoleAccess  []uuid.UUID `json:"role_access"`
	GroupAccess []uuid.UUID `json:"group_access"`
	AssetAccess []uuid.UUID `json:"asset_access"`
}

// [14] anchorHomeFolders: the union of the three folder-id anchor sources hanging
// off folder-homed nodes — the home folders of roles/groups visible to the user and
// the folders of assets visible to the user. Per kind visibility is (the pre-computed
// ACCESS id set) ∪ (MANAGEMENT via the kind's read cap over authz_held /
// authz_global_held) ∪ (for assets, CONNECT via an ssh:login entitled over the full
// asset-scope cascade). Management cascades DOWN a folder subtree (ltree <@).
func (q *Queries) AnchorHomeFolders(ctx context.Context, arg AnchorHomeFoldersParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, anchorHomeFolders,
		arg.User,
		arg.RoleAccess,
		arg.GroupAccess,
		arg.AssetAccess,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var folder_id pgtype.UUID
		if err := rows.Scan(&folder_id); err != nil {
			return nil, err
		}
		items = append(items, folder_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const approvablePending = `-- name: ApprovablePending :many
WITH pending AS (
    SELECT id, requester_user_id, role_id, asset_id, reason, required_approvals, status, created_at, resolved_at
    FROM access_requests
    WHERE status = 'pending' AND requester_user_id <> $1
      AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
),
pa AS (SELECT DISTINCT role_id, asset_id FROM pending),
eff AS (
    SELECT pa.role_id, pa.asset_id, ep.policy_id, ep.approver_role_id
    FROM pa
    JOIN LATERAL authz_effective_request_policy(pa.role_id, pa.asset_id) ep ON true
),
approve_counts AS (
    SELECT request_id, count(*) AS n FROM access_request_approvals
    WHERE decision = 'approve' AND request_id IN (SELECT id FROM pending)
    GROUP BY request_id
)
SELECT p.id, p.requester_user_id, p.role_id, p.asset_id, p.reason,
       p.required_approvals, p.status, p.created_at, p.resolved_at,
       COALESCE(c.n, 0)::bigint AS approvals
FROM pending p
JOIN eff e ON e.role_id = p.role_id AND e.asset_id = p.asset_id
LEFT JOIN approve_counts c ON c.request_id = p.id
WHERE authz_user_is_active($1)
  AND (
    EXISTS (
        SELECT 1 FROM request_policy_subjects sub
        WHERE sub.policy_id = e.policy_id AND sub.kind = 'approver'
          AND (sub.subject_user_id = $1
               OR sub.subject_group_id IN (SELECT group_id FROM authz_user_groups($1)))
    )
    OR (
        e.approver_role_id IS NOT NULL
        AND EXISTS (
            SELECT 1 FROM authz_held_standing($1) hs
            WHERE hs.role_id = e.approver_role_id AND hs.object_kind = 'asset' AND hs.object_id = p.asset_id
        )
    )
  )
ORDER BY p.created_at DESC, p.id
`

type ApprovablePendingParams struct {
	Caller   uuid.UUID   `json:"caller"`
	Restrict []uuid.UUID `json:"restrict"`
}

type ApprovablePendingRow struct {
	ID                uuid.UUID          `json:"id"`
	RequesterUserID   uuid.UUID          `json:"requester_user_id"`
	RoleID            uuid.UUID          `json:"role_id"`
	AssetID           uuid.UUID          `json:"asset_id"`
	Reason            string             `json:"reason"`
	RequiredApprovals int32              `json:"required_approvals"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	Approvals         pgtype.Int8        `json:"approvals"`
}

// [22] accessrequest.approvablePending: the pending access requests the caller may
// approve, with their current approve-count, resolved set-based (reproducing
// IsApprover over the whole candidate set). A candidate is included when the caller
// is neither its requester nor deactivated AND, for the request's EFFECTIVE policy
// (authz_effective_request_policy — the same asset/folder-ancestor/global precedence
// as EffectiveRule), the caller is either an explicit kind='approver' subject (direct
// or via a nested group, authz_user_groups) OR holds the policy's approver_role
// STANDING on the asset (authz_held_standing). @restrict limits the candidate set to
// those request ids (a keyset page); a NULL array considers all pending requests.
// Ordered created_at DESC, id to match the paged SQL page order.
func (q *Queries) ApprovablePending(ctx context.Context, arg ApprovablePendingParams) ([]ApprovablePendingRow, error) {
	rows, err := q.db.Query(ctx, approvablePending, arg.Caller, arg.Restrict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovablePendingRow
	for rows.Next() {
		var i ApprovablePendingRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.RoleID,
			&i.AssetID,
			&i.Reason,
			&i.RequiredApprovals,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Approvals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assetLoginsForAssets = `-- name: AssetLoginsForAssets :many
SELECT asset_id, login FROM ssh_asset_login WHERE asset_id = ANY($1::uuid[]) ORDER BY login
`

type AssetLoginsForAssetsRow struct {
	AssetID uuid.UUID `json:"asset_id"`
	Login   string    `json:"login"`
}

// assetLoginsFor: the SSH login names declared on each asset in `asset_ids`.
func (q *Queries) AssetLoginsForAssets(ctx context.Context, assetIds []uuid.UUID) ([]AssetLoginsForAssetsRow, error) {
	rows, err := q.db.Query(ctx, assetLoginsForAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetLoginsForAssetsRow
	for rows.Next() {
		var i AssetLoginsForAssetsRow
		if err := rows.Scan(&i.AssetID, &i.Login); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const childFolderIDs = `-- name: ChildFolderIDs :many
SELECT id FROM folders WHERE parent_id IS NOT DISTINCT FROM $1::uuid ORDER BY name, id
`

// childFolderIDs: the ids of folders directly under `parent`, ordered by (name, id).
// A NULL parent selects the tree root (parent_id IS NULL).
func (q *Queries) ChildFolderIDs(ctx context.Context, parent pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, childFolderIDs, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const effectiveRequestPolicy = `-- name: EffectiveRequestPolicy :one
SELECT policy_id, required_approvals, approver_role_id, requester_role_id, max_duration
FROM authz_effective_request_policy($1, $2)
`

type EffectiveRequestPolicyParams struct {
	RoleID  uuid.UUID `json:"role_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

type EffectiveRequestPolicyRow struct {
	PolicyID          pgtype.UUID     `json:"policy_id"`
	RequiredApprovals pgtype.Int4     `json:"required_approvals"`
	ApproverRoleID    pgtype.UUID     `json:"approver_role_id"`
	RequesterRoleID   pgtype.UUID     `json:"requester_role_id"`
	MaxDuration       pgtype.Interval `json:"max_duration"`
}

// approvals.EffectiveRule.
func (q *Queries) EffectiveRequestPolicy(ctx context.Context, arg EffectiveRequestPolicyParams) (EffectiveRequestPolicyRow, error) {
	row := q.db.QueryRow(ctx, effectiveRequestPolicy, arg.RoleID, arg.AssetID)
	var i EffectiveRequestPolicyRow
	err := row.Scan(
		&i.PolicyID,
		&i.RequiredApprovals,
		&i.ApproverRoleID,
		&i.RequesterRoleID,
		&i.MaxDuration,
	)
	return i, err
}

const explainRolePaths = `-- name: ExplainRolePaths :many
SELECT path, binding_id, subject_user_id, subject_group_id
FROM authz_role_goal_paths($1, $2, $3)
`

type ExplainRolePathsParams struct {
	User    uuid.UUID `json:"user"`
	RoleID  uuid.UUID `json:"role_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

type ExplainRolePathsRow struct {
	Path           []byte      `json:"path"`
	BindingID      pgtype.UUID `json:"binding_id"`
	SubjectUserID  pgtype.UUID `json:"subject_user_id"`
	SubjectGroupID pgtype.UUID `json:"subject_group_id"`
}

// ExplainRole.
func (q *Queries) ExplainRolePaths(ctx context.Context, arg ExplainRolePathsParams) ([]ExplainRolePathsRow, error) {
	rows, err := q.db.Query(ctx, explainRolePaths, arg.User, arg.RoleID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExplainRolePathsRow
	for rows.Next() {
		var i ExplainRolePathsRow
		if err := rows.Scan(
			&i.Path,
			&i.BindingID,
			&i.SubjectUserID,
			&i.SubjectGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folderAncestorsByPath = `-- name: FolderAncestorsByPath :many
SELECT f.id FROM folders f
WHERE f.path_ids @> (SELECT path_ids FROM folders WHERE id = $1)
`

// folderAncestorsAndSelf: every ancestor-or-self folder id of `id`, via the ltree
// ancestor operator (@>).
func (q *Queries) FolderAncestorsByPath(ctx context.Context, id pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderAncestorsByPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folderExists = `-- name: FolderExists :one
SELECT EXISTS(SELECT 1 FROM folders WHERE id = $1)
`

// FolderPathVisible global short-circuit: whether a folder id exists.
func (q *Queries) FolderExists(ctx context.Context, folderID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, folderExists, folderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const folderPathIDs = `-- name: FolderPathIDs :one
SELECT path_ids::text FROM folders WHERE id = $1
`

// folderPathIDs: the ltree path text of one folder. pgx.ErrNoRows for a missing folder.
func (q *Queries) FolderPathIDs(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, folderPathIDs, id)
	var path_ids string
	err := row.Scan(&path_ids)
	return path_ids, err
}

const folderPathVisible = `-- name: FolderPathVisible :one
WITH f  AS (SELECT path_ids FROM folders WHERE id = $1),
     ap AS (SELECT path_ids FROM folders WHERE id = ANY($2::uuid[])),
     mp AS (SELECT path_ids FROM folders WHERE id = ANY($3::uuid[]))
SELECT EXISTS (SELECT 1 FROM f, ap WHERE f.path_ids @> ap.path_ids)
    OR EXISTS (SELECT 1 FROM f, mp WHERE f.path_ids <@ mp.path_ids)
`

type FolderPathVisibleParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Anchors  []uuid.UUID `json:"anchors"`
	MgmtIds  []uuid.UUID `json:"mgmt_ids"`
}

// FolderPathVisible: whether `folder_id` is an ancestor-or-self of an anchor (path reveal)
// OR inside a folder the user manages (cascade down) — the same predicate as
// VisibleFoldersUnder, for one folder.
func (q *Queries) FolderPathVisible(ctx context.Context, arg FolderPathVisibleParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, folderPathVisible, arg.FolderID, arg.Anchors, arg.MgmtIds)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const folderSubtreeIDsByRoots = `-- name: FolderSubtreeIDsByRoots :many
SELECT f.id FROM folders f
WHERE f.path_ids <@ ANY (SELECT path_ids FROM folders WHERE id = ANY($1::uuid[]))
`

// folderSubtreeIDs: every folder id in the subtrees rooted at `roots` (inclusive),
// via the GiST-indexed ltree descendant operator (<@).
func (q *Queries) FolderSubtreeIDsByRoots(ctx context.Context, roots []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderSubtreeIDsByRoots, roots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalHeldCapabilities = `-- name: GlobalHeldCapabilities :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_global_held($1) gh JOIN role_capabilities rc ON rc.role_id = gh.role_id
`

type GlobalHeldCapabilitiesRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// globalHeldCapabilities.
func (q *Queries) GlobalHeldCapabilities(ctx context.Context, user uuid.UUID) ([]GlobalHeldCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, globalHeldCapabilities, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalHeldCapabilitiesRow
	for rows.Next() {
		var i GlobalHeldCapabilitiesRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldAssets = `-- name: HeldAssets :many
SELECT DISTINCT object_id, role_id FROM authz_held($1) WHERE object_kind = 'asset'
`

type HeldAssetsRow struct {
	ObjectID pgtype.UUID `json:"object_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

// VisibleAssets active tier.
func (q *Queries) HeldAssets(ctx context.Context, user uuid.UUID) ([]HeldAssetsRow, error) {
	rows, err := q.db.Query(ctx, heldAssets, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldAssetsRow
	for rows.Next() {
		var i HeldAssetsRow
		if err := rows.Scan(&i.ObjectID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCapabilitiesOnFolders = `-- name: HeldCapabilitiesOnFolders :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = 'folder' AND h.object_id = ANY($2::uuid[])
`

type HeldCapabilitiesOnFoldersParams struct {
	User      uuid.UUID   `json:"user"`
	FolderIds []uuid.UUID `json:"folder_ids"`
}

type HeldCapabilitiesOnFoldersRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// capsOnFolders.
func (q *Queries) HeldCapabilitiesOnFolders(ctx context.Context, arg HeldCapabilitiesOnFoldersParams) ([]HeldCapabilitiesOnFoldersRow, error) {
	rows, err := q.db.Query(ctx, heldCapabilitiesOnFolders, arg.User, arg.FolderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldCapabilitiesOnFoldersRow
	for rows.Next() {
		var i HeldCapabilitiesOnFoldersRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCapabilitiesOnObject = `-- name: HeldCapabilitiesOnObject :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = $2 AND h.object_id = $3
`

type HeldCapabilitiesOnObjectParams struct {
	User       pgtype.UUID `json:"user"`
	ObjectKind pgtype.Text `json:"object_kind"`
	ObjectID   pgtype.UUID `json:"object_id"`
}

type HeldCapabilitiesOnObjectRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnObject.
func (q *Queries) HeldCapabilitiesOnObject(ctx context.Context, arg HeldCapabilitiesOnObjectParams) ([]HeldCapabilitiesOnObjectRow, error) {
	rows, err := q.db.Query(ctx, heldCapabilitiesOnObject, arg.User, arg.ObjectKind, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldCapabilitiesOnObjectRow
	for rows.Next() {
		var i HeldCapabilitiesOnObjectRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCheckAssetCapability = `-- name: HeldCheckAssetCapability :one
SELECT EXISTS (
    SELECT 1 FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
    WHERE h.object_kind = 'asset' AND h.object_id = $2
      AND (rc.scope = $3 OR rc.scope = '*')
      AND (rc.action = $4 OR rc.action = '*')
      AND (rc.qualifier = $5 OR rc.qualifier = '*')
)
`

type HeldCheckAssetCapabilityParams struct {
	User      pgtype.UUID `json:"user"`
	AssetID   pgtype.UUID `json:"asset_id"`
	CapScope  pgtype.Text `json:"cap_scope"`
	CapAction pgtype.Text `json:"cap_action"`
	CapQual   pgtype.Text `json:"cap_qual"`
}

// Check.
func (q *Queries) HeldCheckAssetCapability(ctx context.Context, arg HeldCheckAssetCapabilityParams) (bool, error) {
	row := q.db.QueryRow(ctx, heldCheckAssetCapability,
		arg.User,
		arg.AssetID,
		arg.CapScope,
		arg.CapAction,
		arg.CapQual,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heldFolderCapabilities = `-- name: HeldFolderCapabilities :many
SELECT DISTINCT h.object_id, rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = 'folder'
`

type HeldFolderCapabilitiesRow struct {
	ObjectID  pgtype.UUID `json:"object_id"`
	Scope     string      `json:"scope"`
	Action    string      `json:"action"`
	Qualifier string      `json:"qualifier"`
}

// mgmtScopeFolders.
func (q *Queries) HeldFolderCapabilities(ctx context.Context, user uuid.UUID) ([]HeldFolderCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, heldFolderCapabilities, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldFolderCapabilitiesRow
	for rows.Next() {
		var i HeldFolderCapabilitiesRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.Scope,
			&i.Action,
			&i.Qualifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRoleIDs = `-- name: HeldRoleIDs :many
SELECT DISTINCT role_id FROM authz_held($1)
`

// heldRoleIDs.
func (q *Queries) HeldRoleIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, heldRoleIDs, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRolesAndAssets = `-- name: HeldRolesAndAssets :many
SELECT DISTINCT object_kind, object_id, role_id FROM authz_held($1)
`

type HeldRolesAndAssetsRow struct {
	ObjectKind pgtype.Text `json:"object_kind"`
	ObjectID   pgtype.UUID `json:"object_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

// heldRolesAndAssets.
func (q *Queries) HeldRolesAndAssets(ctx context.Context, user uuid.UUID) ([]HeldRolesAndAssetsRow, error) {
	rows, err := q.db.Query(ctx, heldRolesAndAssets, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldRolesAndAssetsRow
	for rows.Next() {
		var i HeldRolesAndAssetsRow
		if err := rows.Scan(&i.ObjectKind, &i.ObjectID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRolesOnAsset = `-- name: HeldRolesOnAsset :many
SELECT DISTINCT role_id FROM authz_held($1)
WHERE object_kind = 'asset' AND object_id = $2
`

type HeldRolesOnAssetParams struct {
	User    pgtype.UUID `json:"user"`
	AssetID pgtype.UUID `json:"asset_id"`
}

// RolesOnAsset active.
func (q *Queries) HeldRolesOnAsset(ctx context.Context, arg HeldRolesOnAssetParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, heldRolesOnAsset, arg.User, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdsRole = `-- name: HoldsRole :one
SELECT EXISTS (
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN role_bindings rb ON rb.role_id = g.role_id
      AND ((g.object_kind='asset' AND rb.scope_asset_id=g.object_id)
        OR (g.object_kind='folder' AND rb.scope_folder_id=g.object_id))
      AND (rb.subject_user_id = $4
        OR rb.subject_group_id IN (SELECT group_id FROM authz_user_groups($4)))
    WHERE authz_user_is_active($4)
  UNION ALL
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN active_access_grants ag ON ag.role_id = g.role_id
      AND g.object_kind='asset' AND ag.scope_asset_id = g.object_id
      AND ag.subject_user_id = $4
    WHERE authz_user_is_active($4)
)
`

type HoldsRoleParams struct {
	RoleID     uuid.UUID   `json:"role_id"`
	ObjectKind string      `json:"object_kind"`
	ObjectID   uuid.UUID   `json:"object_id"`
	User       pgtype.UUID `json:"user"`
}

// RoleResolver.HoldsRole (binding ∪ grant satisfaction over authz_role_goals).
func (q *Queries) HoldsRole(ctx context.Context, arg HoldsRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, holdsRole,
		arg.RoleID,
		arg.ObjectKind,
		arg.ObjectID,
		arg.User,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const holdsRoleStanding = `-- name: HoldsRoleStanding :one
SELECT EXISTS (
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN role_bindings rb ON rb.role_id = g.role_id
      AND ((g.object_kind='asset' AND rb.scope_asset_id=g.object_id)
        OR (g.object_kind='folder' AND rb.scope_folder_id=g.object_id))
      AND (rb.subject_user_id = $4
        OR rb.subject_group_id IN (SELECT group_id FROM authz_user_groups($4)))
    WHERE authz_user_is_active($4)
)
`

type HoldsRoleStandingParams struct {
	RoleID     uuid.UUID   `json:"role_id"`
	ObjectKind string      `json:"object_kind"`
	ObjectID   uuid.UUID   `json:"object_id"`
	User       pgtype.UUID `json:"user"`
}

// RoleResolver.HoldsRoleStanding (binding satisfaction only).
func (q *Queries) HoldsRoleStanding(ctx context.Context, arg HoldsRoleStandingParams) (bool, error) {
	row := q.db.QueryRow(ctx, holdsRoleStanding,
		arg.RoleID,
		arg.ObjectKind,
		arg.ObjectID,
		arg.User,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (SELECT 1 FROM authz_user_groups($1) WHERE group_id = $2)
   AND authz_user_is_active($1)
`

type IsMemberParams struct {
	User  pgtype.UUID `json:"user"`
	Group pgtype.UUID `json:"group"`
}

// visible_tree IsMember.
func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.User, arg.Group)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const memberGroupIDs = `-- name: MemberGroupIDs :many
SELECT group_id FROM authz_user_groups($1) WHERE authz_user_is_active($1)
`

// memberGroupIDs.
func (q *Queries) MemberGroupIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, memberGroupIDs, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var group_id pgtype.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestableRolesOnAsset = `-- name: RequestableRolesOnAsset :many
WITH held_on_asset AS (
    SELECT role_id FROM authz_held($1)
    WHERE object_kind = 'asset' AND object_id = $2
),
held_standing_on_asset AS (
    SELECT role_id FROM authz_held_standing($1)
    WHERE object_kind = 'asset' AND object_id = $2
),
effective AS (
    SELECT r.role_id, ep.policy_id, ep.requester_role_id
    FROM (SELECT DISTINCT role_id FROM request_policies) r
    JOIN LATERAL authz_effective_request_policy(r.role_id, $2) ep ON true
)
SELECT e.role_id
FROM effective e
WHERE
  (
    ( e.requester_role_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM held_standing_on_asset ha WHERE ha.role_id = e.requester_role_id) )
    OR EXISTS (
        SELECT 1 FROM request_policy_subjects rps
        WHERE rps.policy_id = e.policy_id
          AND rps.kind = 'requester'
          AND (rps.subject_user_id = $1
               OR rps.subject_group_id IN (SELECT group_id FROM authz_user_groups($1)))
          AND authz_user_is_active($1)
    )
  )
  AND NOT EXISTS (SELECT 1 FROM held_on_asset ha WHERE ha.role_id = e.role_id)
`

type RequestableRolesOnAssetParams struct {
	User    pgtype.UUID `json:"user"`
	AssetID pgtype.UUID `json:"asset_id"`
}

// [2] requestableRoles: roles requestable (but not already active) for the user on
// the asset under the request_policy eligibility model. The effective policy per
// candidate role is authz_effective_request_policy(role, asset); the held /
// held_standing closures come from the shared authz_held / authz_held_standing
// functions. A role is requestable iff its effective policy makes the user eligible
// (requester_role held STANDING on the asset OR an explicit kind='requester'
// subject) AND the user does not already hold it Active on the asset (grants count).
func (q *Queries) RequestableRolesOnAsset(ctx context.Context, arg RequestableRolesOnAssetParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, requestableRolesOnAsset, arg.User, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewableGrants = `-- name: ReviewableGrants :many
WITH grants AS (
    SELECT id, role_id, scope_asset_id, subject_user_id, granted_at, expires_at, revoked_at, revoked_reason
    FROM access_grants
    WHERE ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
),
ga AS (SELECT DISTINCT role_id, scope_asset_id FROM grants),
eff AS (
    SELECT ga.role_id, ga.scope_asset_id, ep.policy_id, ep.approver_role_id
    FROM ga
    JOIN LATERAL authz_effective_request_policy(ga.role_id, ga.scope_asset_id) ep ON true
)
SELECT g.id, g.role_id, g.scope_asset_id, g.subject_user_id, g.granted_at, g.expires_at, g.revoked_at, g.revoked_reason
FROM grants g
LEFT JOIN eff e ON e.role_id = g.role_id AND e.scope_asset_id = g.scope_asset_id
WHERE g.subject_user_id = $1
   OR (
       authz_user_is_active($1)
       AND e.policy_id IS NOT NULL
       AND (
           EXISTS (
               SELECT 1 FROM request_policy_subjects sub
               WHERE sub.policy_id = e.policy_id AND sub.kind = 'approver'
                 AND (sub.subject_user_id = $1
                      OR sub.subject_group_id IN (SELECT group_id FROM authz_user_groups($1)))
           )
           OR (
               e.approver_role_id IS NOT NULL
               AND EXISTS (
                   SELECT 1 FROM authz_held_standing($1) hs
                   WHERE hs.role_id = e.approver_role_id AND hs.object_kind = 'asset' AND hs.object_id = g.scope_asset_id
               )
           )
       )
   )
ORDER BY g.granted_at DESC, g.id
`

type ReviewableGrantsParams struct {
	Caller   pgtype.UUID `json:"caller"`
	Restrict []uuid.UUID `json:"restrict"`
}

type ReviewableGrantsRow struct {
	ID            uuid.UUID          `json:"id"`
	RoleID        uuid.UUID          `json:"role_id"`
	ScopeAssetID  uuid.UUID          `json:"scope_asset_id"`
	SubjectUserID uuid.UUID          `json:"subject_user_id"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

// [23] accessrequest.reviewableGrants: the grants the caller may review, resolved
// set-based (reproducing CanReviewGrant over the whole candidate set). A grant is
// reviewable when the caller is its subject OR (the caller is active AND, for the
// grant's (role, asset) EFFECTIVE policy — authz_effective_request_policy — an
// explicit kind='approver' subject, direct or via a nested group, OR the approver_role
// held STANDING on the asset). The subject arm intentionally has no active-user check,
// matching CanReviewGrant. @restrict limits the candidate set to those grant ids (a
// keyset page); a NULL array considers all grants. Ordered granted_at DESC, id.
func (q *Queries) ReviewableGrants(ctx context.Context, arg ReviewableGrantsParams) ([]ReviewableGrantsRow, error) {
	rows, err := q.db.Query(ctx, reviewableGrants, arg.Caller, arg.Restrict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewableGrantsRow
	for rows.Next() {
		var i ReviewableGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleStandingHolders = `-- name: RoleStandingHolders :many
SELECT DISTINCT
  rb.subject_user_id,
  rb.subject_group_id,
  (CASE WHEN rb.subject_group_id IS NOT NULL THEN 'group' ELSE 'user' END)::text AS subject_kind,
  COALESCE(u.display_name, g.name, '')::text AS display_name,
  folder_path(g.folder_id) AS folder_path,
  COALESCE(gm.cnt, 0)::int AS group_member_count,
  COALESCE(u.deactivated_at IS NULL, true) AS active,
  rb.role_id AS via_role_id,
  vr.name AS via_role_name
FROM role_bindings rb
JOIN authz_role_goals($1, $2, $3) gl
  ON gl.role_id = rb.role_id
 AND (
      (gl.object_kind = 'asset'  AND rb.scope_asset_id  = gl.object_id)
   OR (gl.object_kind = 'folder' AND rb.scope_folder_id = gl.object_id)
     )
JOIN roles vr ON vr.id = rb.role_id
LEFT JOIN users u ON u.id = rb.subject_user_id
LEFT JOIN groups g ON g.id = rb.subject_group_id
LEFT JOIN LATERAL (
  SELECT count(*)::int AS cnt FROM group_memberships m WHERE m.group_id = rb.subject_group_id
) gm ON rb.subject_group_id IS NOT NULL
WHERE (rb.subject_group_id IS NOT NULL OR authz_user_is_active(rb.subject_user_id))
`

type RoleStandingHoldersParams struct {
	RoleID     uuid.UUID `json:"role_id"`
	ObjectKind string    `json:"object_kind"`
	ObjectID   uuid.UUID `json:"object_id"`
}

type RoleStandingHoldersRow struct {
	SubjectUserID    pgtype.UUID `json:"subject_user_id"`
	SubjectGroupID   pgtype.UUID `json:"subject_group_id"`
	SubjectKind      string      `json:"subject_kind"`
	DisplayName      string      `json:"display_name"`
	FolderPath       string      `json:"folder_path"`
	GroupMemberCount int32       `json:"group_member_count"`
	Active           pgtype.Bool `json:"active"`
	ViaRoleID        uuid.UUID   `json:"via_role_id"`
	ViaRoleName      string      `json:"via_role_name"`
}

// Subjects whose standing binding confers p_role on the given object (asset|folder),
// mirroring the base arm of authz_held over the backward goal-expansion. Subjects are
// returned as NODES (not expanded to members), fully resolved for display, tagged with
// the actually-bound role (via_role_name). Deactivated user-subjects excluded.
func (q *Queries) RoleStandingHolders(ctx context.Context, arg RoleStandingHoldersParams) ([]RoleStandingHoldersRow, error) {
	rows, err := q.db.Query(ctx, roleStandingHolders, arg.RoleID, arg.ObjectKind, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleStandingHoldersRow
	for rows.Next() {
		var i RoleStandingHoldersRow
		if err := rows.Scan(
			&i.SubjectUserID,
			&i.SubjectGroupID,
			&i.SubjectKind,
			&i.DisplayName,
			&i.FolderPath,
			&i.GroupMemberCount,
			&i.Active,
			&i.ViaRoleID,
			&i.ViaRoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeCapabilitiesAsset = `-- name: ScopeCapabilitiesAsset :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM role_capabilities rc
WHERE rc.role_id IN (
    SELECT role_id FROM authz_global_held($1)
  UNION
    SELECT h.role_id FROM authz_held($1) h
    WHERE (h.object_kind = 'asset' AND h.object_id = $2)
       OR (h.object_kind = 'folder' AND h.object_id IN (
              SELECT anc.id FROM folders anc
              JOIN assets a ON a.id = $2
              WHERE anc.path_ids @> (SELECT af.path_ids FROM folders af WHERE af.id = a.folder_id)))
)
`

type ScopeCapabilitiesAssetParams struct {
	User    pgtype.UUID `json:"user"`
	ScopeID pgtype.UUID `json:"scope_id"`
}

type ScopeCapabilitiesAssetRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnScope asset arm (global_held ∪ held on the asset or its ancestor-or-self folders).
func (q *Queries) ScopeCapabilitiesAsset(ctx context.Context, arg ScopeCapabilitiesAssetParams) ([]ScopeCapabilitiesAssetRow, error) {
	rows, err := q.db.Query(ctx, scopeCapabilitiesAsset, arg.User, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeCapabilitiesAssetRow
	for rows.Next() {
		var i ScopeCapabilitiesAssetRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeCapabilitiesFolder = `-- name: ScopeCapabilitiesFolder :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM role_capabilities rc
WHERE rc.role_id IN (
    SELECT role_id FROM authz_global_held($1)
  UNION
    SELECT h.role_id FROM authz_held($1) h
    WHERE h.object_kind = 'folder'
      AND h.object_id IN (SELECT f.id FROM folders f
                          WHERE f.path_ids @> (SELECT s.path_ids FROM folders s WHERE s.id = $2))
)
`

type ScopeCapabilitiesFolderParams struct {
	User    uuid.UUID `json:"user"`
	ScopeID uuid.UUID `json:"scope_id"`
}

type ScopeCapabilitiesFolderRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnScope folder arm (global_held ∪ held on folders in the scope subtree).
func (q *Queries) ScopeCapabilitiesFolder(ctx context.Context, arg ScopeCapabilitiesFolderParams) ([]ScopeCapabilitiesFolderRow, error) {
	rows, err := q.db.Query(ctx, scopeCapabilitiesFolder, arg.User, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeCapabilitiesFolderRow
	for rows.Next() {
		var i ScopeCapabilitiesFolderRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectExistsForKind = `-- name: SubjectExistsForKind :one
SELECT EXISTS (
    SELECT 1 FROM request_policy_subjects rps
    WHERE rps.policy_id = $1
      AND rps.kind = $2
      AND (rps.subject_user_id = $3
           OR rps.subject_group_id IN (SELECT group_id FROM authz_user_groups($3)))
      AND authz_user_is_active($3)
)
`

type SubjectExistsForKindParams struct {
	PolicyID uuid.UUID   `json:"policy_id"`
	Kind     string      `json:"kind"`
	User     pgtype.UUID `json:"user"`
}

// Explicit-subject arm shared by approvals.IsApprover (kind='approver') and
// approvals.IsEligibleRequester (kind='requester'): the caller is an explicit
// subject of the policy — named directly or via a (nested) group — under the
// deactivation guard. Parameterized by kind to single-source the identical body.
func (q *Queries) SubjectExistsForKind(ctx context.Context, arg SubjectExistsForKindParams) (bool, error) {
	row := q.db.QueryRow(ctx, subjectExistsForKind, arg.PolicyID, arg.Kind, arg.User)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const visibleAssetsUnder = `-- name: VisibleAssetsUnder :many
SELECT a.id
FROM assets a
WHERE (
        (NOT $1::boolean AND $2::uuid IS NOT NULL AND a.folder_id = $2::uuid)
     OR ($1::boolean AND (
            $2::uuid IS NULL
            OR a.folder_id IN (SELECT f.id FROM folders f WHERE f.path_ids <@ (SELECT path_ids FROM folders WHERE id = $2::uuid))
        ))
      )
  AND (
        a.id = ANY($3::uuid[])
     OR (SELECT authz_mgmt_global_read($4, $5, $6, $7))
     OR a.folder_id IN (SELECT folder_id FROM authz_mgmt_visible_folders($4, $5, $6, $7))
     OR EXISTS (
        SELECT 1 FROM ssh_asset_login sal
        WHERE sal.asset_id = a.id
          AND EXISTS (
              SELECT 1 FROM role_capabilities rc
              WHERE rc.role_id IN (
                    SELECT role_id FROM authz_global_held($4)
                  UNION
                    SELECT h.role_id FROM authz_held($4) h
                    WHERE (h.object_kind = 'asset' AND h.object_id = a.id)
                       OR (h.object_kind = 'folder'
                           AND h.object_id IN (
                               SELECT f.id FROM folders f
                               WHERE f.path_ids @> (SELECT af.path_ids FROM folders af WHERE af.id = a.folder_id)
                           ))
              )
              AND (rc.scope = 'ssh' OR rc.scope = '*')
              AND (rc.action = 'login' OR rc.action = '*')
              AND (rc.qualifier = sal.login OR rc.qualifier = '*')
          )
      )
      )
ORDER BY a.id
`

type VisibleAssetsUnderParams struct {
	Cascade   bool        `json:"cascade"`
	Parent    pgtype.UUID `json:"parent"`
	AccessIds []uuid.UUID `json:"access_ids"`
	User      uuid.UUID   `json:"user"`
	CapScope  string      `json:"cap_scope"`
	CapAction string      `json:"cap_action"`
	CapQual   string      `json:"cap_qual"`
}

// [13] VisibleAssetsUnder: asset ids under `parent` the user may see, unifying the
// ACCESS (access_ids), MANAGEMENT (catalog:asset:read OR the subtree-wide
// catalog:folder:read, cascade over authz_held / authz_global_held), and CONNECT
// (ssh:login entitled over the full asset-scope cascade) axes. The (parent, cascade)
// browse level is selected by the nullable @parent and @cascade args (the (NULL
// parent, non-cascade) case is short-circuited by the caller and never reaches this
// query). The catalog:folder:read literal arm is the READ-ONLY subtree broadening
// (see authz.FolderReadCap) — it confers READ, never CONNECT or grantable authority.
func (q *Queries) VisibleAssetsUnder(ctx context.Context, arg VisibleAssetsUnderParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, visibleAssetsUnder,
		arg.Cascade,
		arg.Parent,
		arg.AccessIds,
		arg.User,
		arg.CapScope,
		arg.CapAction,
		arg.CapQual,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleFoldersUnder = `-- name: VisibleFoldersUnder :many
WITH anchor_paths AS (SELECT path_ids FROM folders WHERE id = ANY($3::uuid[])),
     mgmt_paths   AS (SELECT path_ids FROM folders WHERE id = ANY($4::uuid[]))
SELECT f.id,
       EXISTS (SELECT 1 FROM mgmt_paths m WHERE f.path_ids <@ m.path_ids) AS governed
FROM folders f
WHERE (
        (NOT $1::boolean AND f.parent_id IS NOT DISTINCT FROM $2::uuid)
     OR ($1::boolean AND $2::uuid IS NULL)
     OR ($1::boolean AND $2::uuid IS NOT NULL
         AND f.path_ids <@ (SELECT path_ids FROM folders WHERE id = $2::uuid)
         AND f.id <> $2::uuid)
      )
  AND ( EXISTS (SELECT 1 FROM anchor_paths a WHERE f.path_ids @> a.path_ids)
     OR EXISTS (SELECT 1 FROM mgmt_paths  m WHERE f.path_ids <@ m.path_ids) )
ORDER BY f.name, f.id
`

type VisibleFoldersUnderParams struct {
	Cascade bool        `json:"cascade"`
	Parent  pgtype.UUID `json:"parent"`
	Anchors []uuid.UUID `json:"anchors"`
	MgmtIds []uuid.UUID `json:"mgmt_ids"`
}

type VisibleFoldersUnderRow struct {
	ID       uuid.UUID `json:"id"`
	Governed bool      `json:"governed"`
}

// VisibleFoldersUnder: folders under `parent` visible to the user under the path-reveal
// model, each with a `governed` flag. `anchors` are the folders whose browse PATH must be
// revealed (ancestor-or-self); `mgmt_ids` are the folders the user manages (their subtrees
// are visible AND governed). The (parent, cascade) browse level is selected by the nullable
// @parent and @cascade args, mirroring childCandidateFolderIDs.
func (q *Queries) VisibleFoldersUnder(ctx context.Context, arg VisibleFoldersUnderParams) ([]VisibleFoldersUnderRow, error) {
	rows, err := q.db.Query(ctx, visibleFoldersUnder,
		arg.Cascade,
		arg.Parent,
		arg.Anchors,
		arg.MgmtIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleFoldersUnderRow
	for rows.Next() {
		var i VisibleFoldersUnderRow
		if err := rows.Scan(&i.ID, &i.Governed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleGroupsHomed = `-- name: VisibleGroupsHomed :many
SELECT n.id, n.folder_id
FROM groups n
WHERE (
        (NOT $1::boolean AND (
            ($2::uuid IS NULL AND n.folder_id IS NULL)
            OR ($2::uuid IS NOT NULL AND n.folder_id = $2::uuid)
        ))
     OR ($1::boolean AND (
            $2::uuid IS NULL
            OR n.folder_id IN (SELECT f.id FROM folders f WHERE f.path_ids <@ (SELECT path_ids FROM folders WHERE id = $2::uuid))
        ))
      )
  AND (
        n.id = ANY($3::uuid[])
     OR (SELECT authz_mgmt_global_read($4, $5, $6, $7))
     OR n.folder_id IN (SELECT folder_id FROM authz_mgmt_visible_folders($4, $5, $6, $7))
      )
ORDER BY n.id
`

type VisibleGroupsHomedParams struct {
	Cascade   bool        `json:"cascade"`
	Parent    pgtype.UUID `json:"parent"`
	AccessIds []uuid.UUID `json:"access_ids"`
	User      uuid.UUID   `json:"user"`
	CapScope  string      `json:"cap_scope"`
	CapAction string      `json:"cap_action"`
	CapQual   string      `json:"cap_qual"`
}

type VisibleGroupsHomedRow struct {
	ID       uuid.UUID   `json:"id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

// [18] visibleHomedSetBased(groups): groups homed under `parent` visible to the user,
// each with its home folder. ACCESS (access_ids = transitive membership) ∪ MANAGEMENT
// (identity:group:read OR the subtree-wide catalog:folder:read cascade). Table variant
// of VisibleRolesHomed (FROM groups). The catalog:folder:read literal arm is the
// READ-ONLY subtree broadening (see authz.FolderReadCap).
func (q *Queries) VisibleGroupsHomed(ctx context.Context, arg VisibleGroupsHomedParams) ([]VisibleGroupsHomedRow, error) {
	rows, err := q.db.Query(ctx, visibleGroupsHomed,
		arg.Cascade,
		arg.Parent,
		arg.AccessIds,
		arg.User,
		arg.CapScope,
		arg.CapAction,
		arg.CapQual,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleGroupsHomedRow
	for rows.Next() {
		var i VisibleGroupsHomedRow
		if err := rows.Scan(&i.ID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleRequestable = `-- name: VisibleRequestable :many
WITH RECURSIVE
ancestors(asset_id, folder_id, depth) AS (
    SELECT id, folder_id, 0 FROM assets
  UNION ALL
    SELECT a.asset_id, f.parent_id, a.depth + 1
    FROM folders f JOIN ancestors a ON f.id = a.folder_id
    WHERE f.parent_id IS NOT NULL
),
held_on_asset(asset_id, role_id) AS (
    SELECT object_id, role_id FROM authz_held($1) WHERE object_kind = 'asset'
),
held_standing_on_asset(asset_id, role_id) AS (
    SELECT object_id, role_id FROM authz_held_standing($1) WHERE object_kind = 'asset'
),
candidate_pairs(asset_id, role_id) AS (
    SELECT rp.scope_asset_id, rp.role_id
    FROM request_policies rp WHERE rp.scope_asset_id IS NOT NULL
  UNION
    SELECT an.asset_id, rp.role_id
    FROM request_policies rp JOIN ancestors an ON rp.scope_folder_id = an.folder_id
  UNION
    SELECT a.id, rp.role_id
    FROM request_policies rp CROSS JOIN assets a
    WHERE rp.scope_folder_id IS NULL AND rp.scope_asset_id IS NULL
),
effective AS (
    SELECT cp.asset_id, cp.role_id, ep.policy_id, ep.requester_role_id
    FROM candidate_pairs cp
    JOIN LATERAL authz_effective_request_policy(cp.role_id, cp.asset_id) ep ON true
)
SELECT e.asset_id, e.role_id
FROM effective e
WHERE
  (
    ( e.requester_role_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM held_standing_on_asset ha WHERE ha.asset_id = e.asset_id AND ha.role_id = e.requester_role_id) )
    OR EXISTS (
        SELECT 1 FROM request_policy_subjects rps
        WHERE rps.policy_id = e.policy_id
          AND rps.kind = 'requester'
          AND (rps.subject_user_id = $1
               OR rps.subject_group_id IN (SELECT group_id FROM authz_user_groups($1)))
          AND authz_user_is_active($1)
    )
  )
  AND NOT EXISTS (SELECT 1 FROM held_on_asset ha WHERE ha.asset_id = e.asset_id AND ha.role_id = e.role_id)
`

type VisibleRequestableRow struct {
	AssetID pgtype.UUID `json:"asset_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

// [3] visibleRequestable: every (asset, role) requestable (and not already active)
// for the user across ALL assets. The candidate (asset, role) universe is the union
// of asset-scoped, ancestor-folder-scoped, and scopeless request_policies; per pair
// the winning policy is authz_effective_request_policy(role, asset) via LATERAL. The
// eligibility and active-exclusion arms mirror RequestableRolesOnAsset, keyed on the
// (asset, role) pair.
func (q *Queries) VisibleRequestable(ctx context.Context, user pgtype.UUID) ([]VisibleRequestableRow, error) {
	rows, err := q.db.Query(ctx, visibleRequestable, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleRequestableRow
	for rows.Next() {
		var i VisibleRequestableRow
		if err := rows.Scan(&i.AssetID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleRolesHomed = `-- name: VisibleRolesHomed :many
SELECT n.id, n.folder_id
FROM roles n
WHERE (
        (NOT $1::boolean AND (
            ($2::uuid IS NULL AND n.folder_id IS NULL)
            OR ($2::uuid IS NOT NULL AND n.folder_id = $2::uuid)
        ))
     OR ($1::boolean AND (
            $2::uuid IS NULL
            OR n.folder_id IN (SELECT f.id FROM folders f WHERE f.path_ids <@ (SELECT path_ids FROM folders WHERE id = $2::uuid))
        ))
      )
  AND (
        n.id = ANY($3::uuid[])
     OR (SELECT authz_mgmt_global_read($4, $5, $6, $7))
     OR n.folder_id IN (SELECT folder_id FROM authz_mgmt_visible_folders($4, $5, $6, $7))
      )
ORDER BY n.id
`

type VisibleRolesHomedParams struct {
	Cascade   bool        `json:"cascade"`
	Parent    pgtype.UUID `json:"parent"`
	AccessIds []uuid.UUID `json:"access_ids"`
	User      uuid.UUID   `json:"user"`
	CapScope  string      `json:"cap_scope"`
	CapAction string      `json:"cap_action"`
	CapQual   string      `json:"cap_qual"`
}

type VisibleRolesHomedRow struct {
	ID       uuid.UUID   `json:"id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

// [18] visibleHomedSetBased(roles): roles homed under `parent` visible to the user,
// each with its home folder. ACCESS (access_ids) ∪ MANAGEMENT (access:role:read OR
// the subtree-wide catalog:folder:read, cascade over authz_held / authz_global_held).
// Level selected by @parent/@cascade. The catalog:folder:read literal arm is the
// READ-ONLY subtree broadening (see authz.FolderReadCap).
func (q *Queries) VisibleRolesHomed(ctx context.Context, arg VisibleRolesHomedParams) ([]VisibleRolesHomedRow, error) {
	rows, err := q.db.Query(ctx, visibleRolesHomed,
		arg.Cascade,
		arg.Parent,
		arg.AccessIds,
		arg.User,
		arg.CapScope,
		arg.CapAction,
		arg.CapQual,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleRolesHomedRow
	for rows.Next() {
		var i VisibleRolesHomedRow
		if err := rows.Scan(&i.ID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
