// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const effectiveRequestPolicy = `-- name: EffectiveRequestPolicy :one
SELECT policy_id, required_approvals, approver_role_id, requester_role_id, max_duration
FROM authz_effective_request_policy($1, $2)
`

type EffectiveRequestPolicyParams struct {
	RoleID  uuid.UUID `json:"role_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

type EffectiveRequestPolicyRow struct {
	PolicyID          pgtype.UUID     `json:"policy_id"`
	RequiredApprovals pgtype.Int4     `json:"required_approvals"`
	ApproverRoleID    pgtype.UUID     `json:"approver_role_id"`
	RequesterRoleID   pgtype.UUID     `json:"requester_role_id"`
	MaxDuration       pgtype.Interval `json:"max_duration"`
}

// approvals.EffectiveRule.
func (q *Queries) EffectiveRequestPolicy(ctx context.Context, arg EffectiveRequestPolicyParams) (EffectiveRequestPolicyRow, error) {
	row := q.db.QueryRow(ctx, effectiveRequestPolicy, arg.RoleID, arg.AssetID)
	var i EffectiveRequestPolicyRow
	err := row.Scan(
		&i.PolicyID,
		&i.RequiredApprovals,
		&i.ApproverRoleID,
		&i.RequesterRoleID,
		&i.MaxDuration,
	)
	return i, err
}

const explainRolePaths = `-- name: ExplainRolePaths :many
SELECT path, binding_id, subject_user_id, subject_group_id
FROM authz_role_goal_paths($1, $2, $3)
`

type ExplainRolePathsParams struct {
	User    uuid.UUID `json:"user"`
	RoleID  uuid.UUID `json:"role_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

type ExplainRolePathsRow struct {
	Path           []byte      `json:"path"`
	BindingID      pgtype.UUID `json:"binding_id"`
	SubjectUserID  pgtype.UUID `json:"subject_user_id"`
	SubjectGroupID pgtype.UUID `json:"subject_group_id"`
}

// ExplainRole.
func (q *Queries) ExplainRolePaths(ctx context.Context, arg ExplainRolePathsParams) ([]ExplainRolePathsRow, error) {
	rows, err := q.db.Query(ctx, explainRolePaths, arg.User, arg.RoleID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExplainRolePathsRow
	for rows.Next() {
		var i ExplainRolePathsRow
		if err := rows.Scan(
			&i.Path,
			&i.BindingID,
			&i.SubjectUserID,
			&i.SubjectGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalHeldCapabilities = `-- name: GlobalHeldCapabilities :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_global_held($1) gh JOIN role_capabilities rc ON rc.role_id = gh.role_id
`

type GlobalHeldCapabilitiesRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// globalHeldCapabilities.
func (q *Queries) GlobalHeldCapabilities(ctx context.Context, user uuid.UUID) ([]GlobalHeldCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, globalHeldCapabilities, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalHeldCapabilitiesRow
	for rows.Next() {
		var i GlobalHeldCapabilitiesRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldAssets = `-- name: HeldAssets :many
SELECT DISTINCT object_id, role_id FROM authz_held($1) WHERE object_kind = 'asset'
`

type HeldAssetsRow struct {
	ObjectID pgtype.UUID `json:"object_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

// VisibleAssets active tier.
func (q *Queries) HeldAssets(ctx context.Context, user uuid.UUID) ([]HeldAssetsRow, error) {
	rows, err := q.db.Query(ctx, heldAssets, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldAssetsRow
	for rows.Next() {
		var i HeldAssetsRow
		if err := rows.Scan(&i.ObjectID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCapabilitiesOnFolders = `-- name: HeldCapabilitiesOnFolders :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = 'folder' AND h.object_id = ANY($2::uuid[])
`

type HeldCapabilitiesOnFoldersParams struct {
	User      uuid.UUID   `json:"user"`
	FolderIds []uuid.UUID `json:"folder_ids"`
}

type HeldCapabilitiesOnFoldersRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// capsOnFolders.
func (q *Queries) HeldCapabilitiesOnFolders(ctx context.Context, arg HeldCapabilitiesOnFoldersParams) ([]HeldCapabilitiesOnFoldersRow, error) {
	rows, err := q.db.Query(ctx, heldCapabilitiesOnFolders, arg.User, arg.FolderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldCapabilitiesOnFoldersRow
	for rows.Next() {
		var i HeldCapabilitiesOnFoldersRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCapabilitiesOnObject = `-- name: HeldCapabilitiesOnObject :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = $2 AND h.object_id = $3
`

type HeldCapabilitiesOnObjectParams struct {
	User       pgtype.UUID `json:"user"`
	ObjectKind pgtype.Text `json:"object_kind"`
	ObjectID   pgtype.UUID `json:"object_id"`
}

type HeldCapabilitiesOnObjectRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnObject.
func (q *Queries) HeldCapabilitiesOnObject(ctx context.Context, arg HeldCapabilitiesOnObjectParams) ([]HeldCapabilitiesOnObjectRow, error) {
	rows, err := q.db.Query(ctx, heldCapabilitiesOnObject, arg.User, arg.ObjectKind, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldCapabilitiesOnObjectRow
	for rows.Next() {
		var i HeldCapabilitiesOnObjectRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldCheckAssetCapability = `-- name: HeldCheckAssetCapability :one
SELECT EXISTS (
    SELECT 1 FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
    WHERE h.object_kind = 'asset' AND h.object_id = $2
      AND (rc.scope = $3 OR rc.scope = '*')
      AND (rc.action = $4 OR rc.action = '*')
      AND (rc.qualifier = $5 OR rc.qualifier = '*')
)
`

type HeldCheckAssetCapabilityParams struct {
	User      pgtype.UUID `json:"user"`
	AssetID   pgtype.UUID `json:"asset_id"`
	CapScope  pgtype.Text `json:"cap_scope"`
	CapAction pgtype.Text `json:"cap_action"`
	CapQual   pgtype.Text `json:"cap_qual"`
}

// Check.
func (q *Queries) HeldCheckAssetCapability(ctx context.Context, arg HeldCheckAssetCapabilityParams) (bool, error) {
	row := q.db.QueryRow(ctx, heldCheckAssetCapability,
		arg.User,
		arg.AssetID,
		arg.CapScope,
		arg.CapAction,
		arg.CapQual,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heldFolderCapabilities = `-- name: HeldFolderCapabilities :many
SELECT DISTINCT h.object_id, rc.scope, rc.action, rc.qualifier
FROM authz_held($1) h JOIN role_capabilities rc ON rc.role_id = h.role_id
WHERE h.object_kind = 'folder'
`

type HeldFolderCapabilitiesRow struct {
	ObjectID  pgtype.UUID `json:"object_id"`
	Scope     string      `json:"scope"`
	Action    string      `json:"action"`
	Qualifier string      `json:"qualifier"`
}

// mgmtScopeFolders.
func (q *Queries) HeldFolderCapabilities(ctx context.Context, user uuid.UUID) ([]HeldFolderCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, heldFolderCapabilities, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldFolderCapabilitiesRow
	for rows.Next() {
		var i HeldFolderCapabilitiesRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.Scope,
			&i.Action,
			&i.Qualifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRoleIDs = `-- name: HeldRoleIDs :many
SELECT DISTINCT role_id FROM authz_held($1)
`

// heldRoleIDs.
func (q *Queries) HeldRoleIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, heldRoleIDs, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRolesAndAssets = `-- name: HeldRolesAndAssets :many
SELECT DISTINCT object_kind, object_id, role_id FROM authz_held($1)
`

type HeldRolesAndAssetsRow struct {
	ObjectKind pgtype.Text `json:"object_kind"`
	ObjectID   pgtype.UUID `json:"object_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

// heldRolesAndAssets.
func (q *Queries) HeldRolesAndAssets(ctx context.Context, user uuid.UUID) ([]HeldRolesAndAssetsRow, error) {
	rows, err := q.db.Query(ctx, heldRolesAndAssets, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldRolesAndAssetsRow
	for rows.Next() {
		var i HeldRolesAndAssetsRow
		if err := rows.Scan(&i.ObjectKind, &i.ObjectID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldRolesOnAsset = `-- name: HeldRolesOnAsset :many
SELECT DISTINCT role_id FROM authz_held($1)
WHERE object_kind = 'asset' AND object_id = $2
`

type HeldRolesOnAssetParams struct {
	User    pgtype.UUID `json:"user"`
	AssetID pgtype.UUID `json:"asset_id"`
}

// RolesOnAsset active.
func (q *Queries) HeldRolesOnAsset(ctx context.Context, arg HeldRolesOnAssetParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, heldRolesOnAsset, arg.User, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const holdsRole = `-- name: HoldsRole :one
SELECT EXISTS (
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN role_bindings rb ON rb.role_id = g.role_id
      AND ((g.object_kind='asset' AND rb.scope_asset_id=g.object_id)
        OR (g.object_kind='folder' AND rb.scope_folder_id=g.object_id))
      AND (rb.subject_user_id = $4
        OR rb.subject_group_id IN (SELECT group_id FROM authz_user_groups($4)))
    WHERE authz_user_is_active($4)
  UNION ALL
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN active_access_grants ag ON ag.role_id = g.role_id
      AND g.object_kind='asset' AND ag.scope_asset_id = g.object_id
      AND ag.subject_user_id = $4
    WHERE authz_user_is_active($4)
)
`

type HoldsRoleParams struct {
	RoleID     uuid.UUID   `json:"role_id"`
	ObjectKind string      `json:"object_kind"`
	ObjectID   uuid.UUID   `json:"object_id"`
	User       pgtype.UUID `json:"user"`
}

// RoleResolver.HoldsRole (binding ∪ grant satisfaction over authz_role_goals).
func (q *Queries) HoldsRole(ctx context.Context, arg HoldsRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, holdsRole,
		arg.RoleID,
		arg.ObjectKind,
		arg.ObjectID,
		arg.User,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const holdsRoleStanding = `-- name: HoldsRoleStanding :one
SELECT EXISTS (
    SELECT 1 FROM authz_role_goals($1, $2, $3) g
    JOIN role_bindings rb ON rb.role_id = g.role_id
      AND ((g.object_kind='asset' AND rb.scope_asset_id=g.object_id)
        OR (g.object_kind='folder' AND rb.scope_folder_id=g.object_id))
      AND (rb.subject_user_id = $4
        OR rb.subject_group_id IN (SELECT group_id FROM authz_user_groups($4)))
    WHERE authz_user_is_active($4)
)
`

type HoldsRoleStandingParams struct {
	RoleID     uuid.UUID   `json:"role_id"`
	ObjectKind string      `json:"object_kind"`
	ObjectID   uuid.UUID   `json:"object_id"`
	User       pgtype.UUID `json:"user"`
}

// RoleResolver.HoldsRoleStanding (binding satisfaction only).
func (q *Queries) HoldsRoleStanding(ctx context.Context, arg HoldsRoleStandingParams) (bool, error) {
	row := q.db.QueryRow(ctx, holdsRoleStanding,
		arg.RoleID,
		arg.ObjectKind,
		arg.ObjectID,
		arg.User,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (SELECT 1 FROM authz_user_groups($1) WHERE group_id = $2)
   AND authz_user_is_active($1)
`

type IsMemberParams struct {
	User  pgtype.UUID `json:"user"`
	Group pgtype.UUID `json:"group"`
}

// visible_tree IsMember.
func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.User, arg.Group)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const memberGroupIDs = `-- name: MemberGroupIDs :many
SELECT group_id FROM authz_user_groups($1) WHERE authz_user_is_active($1)
`

// memberGroupIDs.
func (q *Queries) MemberGroupIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, memberGroupIDs, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var group_id pgtype.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeCapabilitiesAsset = `-- name: ScopeCapabilitiesAsset :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM role_capabilities rc
WHERE rc.role_id IN (
    SELECT role_id FROM authz_global_held($1)
  UNION
    SELECT h.role_id FROM authz_held($1) h
    WHERE (h.object_kind = 'asset' AND h.object_id = $2)
       OR (h.object_kind = 'folder' AND h.object_id IN (
              SELECT anc.id FROM folders anc
              JOIN assets a ON a.id = $2
              WHERE anc.path_ids @> (SELECT af.path_ids FROM folders af WHERE af.id = a.folder_id)))
)
`

type ScopeCapabilitiesAssetParams struct {
	User    pgtype.UUID `json:"user"`
	ScopeID pgtype.UUID `json:"scope_id"`
}

type ScopeCapabilitiesAssetRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnScope asset arm (global_held ∪ held on the asset or its ancestor-or-self folders).
func (q *Queries) ScopeCapabilitiesAsset(ctx context.Context, arg ScopeCapabilitiesAssetParams) ([]ScopeCapabilitiesAssetRow, error) {
	rows, err := q.db.Query(ctx, scopeCapabilitiesAsset, arg.User, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeCapabilitiesAssetRow
	for rows.Next() {
		var i ScopeCapabilitiesAssetRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeCapabilitiesFolder = `-- name: ScopeCapabilitiesFolder :many
SELECT DISTINCT rc.scope, rc.action, rc.qualifier
FROM role_capabilities rc
WHERE rc.role_id IN (
    SELECT role_id FROM authz_global_held($1)
  UNION
    SELECT h.role_id FROM authz_held($1) h
    WHERE h.object_kind = 'folder'
      AND h.object_id IN (SELECT f.id FROM folders f
                          WHERE f.path_ids @> (SELECT s.path_ids FROM folders s WHERE s.id = $2))
)
`

type ScopeCapabilitiesFolderParams struct {
	User    uuid.UUID `json:"user"`
	ScopeID uuid.UUID `json:"scope_id"`
}

type ScopeCapabilitiesFolderRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

// CapabilitiesOnScope folder arm (global_held ∪ held on folders in the scope subtree).
func (q *Queries) ScopeCapabilitiesFolder(ctx context.Context, arg ScopeCapabilitiesFolderParams) ([]ScopeCapabilitiesFolderRow, error) {
	rows, err := q.db.Query(ctx, scopeCapabilitiesFolder, arg.User, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeCapabilitiesFolderRow
	for rows.Next() {
		var i ScopeCapabilitiesFolderRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
