// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assetByFolderName = `-- name: AssetByFolderName :one
SELECT id, folder_id, name, labels, created_at, kind FROM assets WHERE folder_id = $1 AND name = $2
`

type AssetByFolderNameParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	Name     string    `json:"name"`
}

func (q *Queries) AssetByFolderName(ctx context.Context, arg AssetByFolderNameParams) (Asset, error) {
	row := q.db.QueryRow(ctx, assetByFolderName, arg.FolderID, arg.Name)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Labels,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const assetIDsInFolders = `-- name: AssetIDsInFolders :many
SELECT id, folder_id FROM assets WHERE folder_id = ANY($1::uuid[])
`

type AssetIDsInFoldersRow struct {
	ID       uuid.UUID `json:"id"`
	FolderID uuid.UUID `json:"folder_id"`
}

func (q *Queries) AssetIDsInFolders(ctx context.Context, dollar_1 []uuid.UUID) ([]AssetIDsInFoldersRow, error) {
	rows, err := q.db.Query(ctx, assetIDsInFolders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetIDsInFoldersRow
	for rows.Next() {
		var i AssetIDsInFoldersRow
		if err := rows.Scan(&i.ID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindingsScopedToFoldersOrAssets = `-- name: BindingsScopedToFoldersOrAssets :many
SELECT id, role_id, scope_folder_id, scope_asset_id, subject_user_id, subject_group_id, created_at FROM role_bindings
WHERE scope_folder_id = ANY($1::uuid[]) OR scope_asset_id = ANY($2::uuid[])
`

type BindingsScopedToFoldersOrAssetsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) BindingsScopedToFoldersOrAssets(ctx context.Context, arg BindingsScopedToFoldersOrAssetsParams) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, bindingsScopedToFoldersOrAssets, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleBinding
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeFolderID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.SubjectGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const deleteAssetSecretsForAsset = `-- name: DeleteAssetSecretsForAsset :exec
DELETE FROM asset_secrets WHERE asset_id = $1
`

func (q *Queries) DeleteAssetSecretsForAsset(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetSecretsForAsset, assetID)
	return err
}

const deleteOrphanSecretsForAsset = `-- name: DeleteOrphanSecretsForAsset :exec
DELETE FROM asset_secrets s
WHERE s.asset_id = $1
  AND s.id NOT IN (SELECT l.secret_id FROM ssh_asset_login l WHERE l.asset_id = $1 AND l.secret_id IS NOT NULL)
  AND s.id NOT IN (SELECT l.secret_id FROM postgres_asset_login l WHERE l.asset_id = $1 AND l.secret_id IS NOT NULL)
`

// Drop asset_secrets no longer referenced by any of the asset's logins (ssh OR
// postgres). A postgres password login references a secret via secret_id too, so it
// must be counted here or the secret is wrongly deemed orphan and its DELETE trips
// the postgres_login_secret_same_asset FK (ON DELETE RESTRICT).
func (q *Queries) DeleteOrphanSecretsForAsset(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrphanSecretsForAsset, assetID)
	return err
}

const deletePostgresAssetLoginsForAsset = `-- name: DeletePostgresAssetLoginsForAsset :exec
DELETE FROM postgres_asset_login WHERE asset_id = $1
`

func (q *Queries) DeletePostgresAssetLoginsForAsset(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostgresAssetLoginsForAsset, assetID)
	return err
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :exec
DELETE FROM role_bindings WHERE id = $1
`

func (q *Queries) DeleteRoleBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoleBinding, id)
	return err
}

const deleteRoleBindingsForRole = `-- name: DeleteRoleBindingsForRole :exec
DELETE FROM role_bindings WHERE role_id = $1
`

// Removes every standing binding of the role. Part of the DeleteRole cascade.
func (q *Queries) DeleteRoleBindingsForRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoleBindingsForRole, roleID)
	return err
}

const deleteSSHAssetLoginsForAsset = `-- name: DeleteSSHAssetLoginsForAsset :exec
DELETE FROM ssh_asset_login WHERE asset_id = $1
`

func (q *Queries) DeleteSSHAssetLoginsForAsset(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSHAssetLoginsForAsset, assetID)
	return err
}

const folderAncestorsAndSelf = `-- name: FolderAncestorsAndSelf :many
WITH RECURSIVE up AS (
    SELECT folders.id, folders.parent_id FROM folders WHERE folders.id = $1
    UNION ALL
    SELECT f.id, f.parent_id FROM folders f JOIN up ON f.id = up.parent_id
)
SELECT up.id FROM up
`

// Every ancestor-or-self folder id of $1 (the target), walking parent links up
// to the root. Used for folder-scoped role containment checks.
func (q *Queries) FolderAncestorsAndSelf(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderAncestorsAndSelf, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folderByParentName = `-- name: FolderByParentName :one
SELECT id, name, parent_id, created_at, path_ids FROM folders WHERE parent_id IS NOT DISTINCT FROM $1 AND name = $2
`

type FolderByParentNameParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

// One folder by (parent, name). parent_id NULL matches a top-level folder
// (IS NOT DISTINCT FROM treats NULL = NULL as a match).
func (q *Queries) FolderByParentName(ctx context.Context, arg FolderByParentNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, folderByParentName, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.PathIds,
	)
	return i, err
}

const folderPath = `-- name: FolderPath :one
WITH RECURSIVE chain AS (
    SELECT folders.id, folders.parent_id, folders.name, 0 AS depth FROM folders WHERE folders.id = $1
    UNION ALL
    SELECT f.id, f.parent_id, f.name, c.depth + 1
    FROM folders f JOIN chain c ON f.id = c.parent_id
)
SELECT COALESCE(string_agg(chain.name, '.' ORDER BY chain.depth ASC), '')::text AS path FROM chain
`

// Dotted leaf->root path of a single folder (the folder's own name first).
func (q *Queries) FolderPath(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, folderPath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const folderPaths = `-- name: FolderPaths :many
WITH RECURSIVE chain AS (
    SELECT id, parent_id, name::text AS path FROM folders WHERE parent_id IS NULL
    UNION ALL
    SELECT f.id, f.parent_id, (f.name || '.' || c.path)::text
    FROM folders f JOIN chain c ON f.parent_id = c.id
)
SELECT chain.id, chain.path FROM chain
`

type FolderPathsRow struct {
	ID   uuid.UUID `json:"id"`
	Path string    `json:"path"`
}

// Every folder's full leaf->root dotted path in one query (for list responses).
func (q *Queries) FolderPaths(ctx context.Context) ([]FolderPathsRow, error) {
	rows, err := q.db.Query(ctx, folderPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderPathsRow
	for rows.Next() {
		var i FolderPathsRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folderSubtreeIDs = `-- name: FolderSubtreeIDs :many
WITH RECURSIVE sub AS (
    SELECT f.id FROM folders f WHERE f.id = $1
    UNION ALL
    SELECT f.id FROM folders f JOIN sub ON f.parent_id = sub.id
)
SELECT sub.id FROM sub
`

// All folder ids in the subtree rooted at $1 (including $1 itself).
func (q *Queries) FolderSubtreeIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderSubtreeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, parent_id, created_at, path_ids FROM folders WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.PathIds,
	)
	return i, err
}

const getPostgresAssetConfig = `-- name: GetPostgresAssetConfig :one
SELECT asset_id, target_address, target_server_ca, default_database FROM postgres_asset_config WHERE asset_id = $1
`

func (q *Queries) GetPostgresAssetConfig(ctx context.Context, assetID uuid.UUID) (PostgresAssetConfig, error) {
	row := q.db.QueryRow(ctx, getPostgresAssetConfig, assetID)
	var i PostgresAssetConfig
	err := row.Scan(
		&i.AssetID,
		&i.TargetAddress,
		&i.TargetServerCa,
		&i.DefaultDatabase,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, name, folder_id, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBinding = `-- name: GetRoleBinding :one
SELECT id, role_id, scope_folder_id, scope_asset_id, subject_user_id, subject_group_id, created_at FROM role_bindings WHERE id = $1
`

func (q *Queries) GetRoleBinding(ctx context.Context, id uuid.UUID) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, getRoleBinding, id)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ScopeFolderID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.SubjectGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByFolderAndName = `-- name: GetRoleByFolderAndName :one
SELECT id, name, folder_id, created_at FROM roles WHERE folder_id = $1 AND name = $2
`

type GetRoleByFolderAndNameParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetRoleByFolderAndName(ctx context.Context, arg GetRoleByFolderAndNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByFolderAndName, arg.FolderID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByNameGlobal = `-- name: GetRoleByNameGlobal :one
SELECT id, name, folder_id, created_at FROM roles WHERE name = $1 AND folder_id IS NULL
`

func (q *Queries) GetRoleByNameGlobal(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameGlobal, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getSSHAssetConfig = `-- name: GetSSHAssetConfig :one
SELECT asset_id, target_address, host_public_key FROM ssh_asset_config WHERE asset_id = $1
`

func (q *Queries) GetSSHAssetConfig(ctx context.Context, assetID uuid.UUID) (SshAssetConfig, error) {
	row := q.db.QueryRow(ctx, getSSHAssetConfig, assetID)
	var i SshAssetConfig
	err := row.Scan(&i.AssetID, &i.TargetAddress, &i.HostPublicKey)
	return i, err
}

const getSSHAssetLogin = `-- name: GetSSHAssetLogin :one
SELECT asset_id, login, kind, secret_id FROM ssh_asset_login WHERE asset_id = $1 AND login = $2
`

type GetSSHAssetLoginParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	Login   string    `json:"login"`
}

func (q *Queries) GetSSHAssetLogin(ctx context.Context, arg GetSSHAssetLoginParams) (SshAssetLogin, error) {
	row := q.db.QueryRow(ctx, getSSHAssetLogin, arg.AssetID, arg.Login)
	var i SshAssetLogin
	err := row.Scan(
		&i.AssetID,
		&i.Login,
		&i.Kind,
		&i.SecretID,
	)
	return i, err
}

const listAssetsByIDs = `-- name: ListAssetsByIDs :many
SELECT id, folder_id, name, labels, created_at, kind FROM assets WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListAssetsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.Labels,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByIDsPaged = `-- name: ListAssetsByIDsPaged :many
SELECT id, folder_id, name, labels, created_at, kind FROM assets
WHERE id = ANY($1::uuid[])
  AND (
    $2::text IS NULL
    OR (name, id) > ($2, $3::uuid)
  )
ORDER BY name, id
LIMIT $4
`

type ListAssetsByIDsPagedParams struct {
	Ids       []uuid.UUID `json:"ids"`
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListAssetsByIDsPaged(ctx context.Context, arg ListAssetsByIDsPagedParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByIDsPaged,
		arg.Ids,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.Labels,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, parent_id, created_at, path_ids FROM folders WHERE ($1::uuid IS NULL OR id > $1) ORDER BY id LIMIT $2
`

type ListFoldersParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Limit   int64     `json:"limit"`
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.PathIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByIDsPaged = `-- name: ListFoldersByIDsPaged :many
SELECT id, name, parent_id, created_at, path_ids FROM folders
WHERE id = ANY($1::uuid[])
  AND (
    $2::text IS NULL
    OR (name, id) > ($2, $3::uuid)
  )
ORDER BY name, id
LIMIT $4
`

type ListFoldersByIDsPagedParams struct {
	Ids       []uuid.UUID `json:"ids"`
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListFoldersByIDsPaged(ctx context.Context, arg ListFoldersByIDsPagedParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByIDsPaged,
		arg.Ids,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.PathIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresAssetLogins = `-- name: ListPostgresAssetLogins :many
SELECT asset_id, role, kind, secret_id FROM postgres_asset_login WHERE asset_id = $1 ORDER BY role
`

func (q *Queries) ListPostgresAssetLogins(ctx context.Context, assetID uuid.UUID) ([]PostgresAssetLogin, error) {
	rows, err := q.db.Query(ctx, listPostgresAssetLogins, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostgresAssetLogin
	for rows.Next() {
		var i PostgresAssetLogin
		if err := rows.Scan(
			&i.AssetID,
			&i.Role,
			&i.Kind,
			&i.SecretID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestPoliciesByAsset = `-- name: ListRequestPoliciesByAsset :many
SELECT id, role_id, scope_folder_id, scope_asset_id, required_approvals, approver_role_id, created_at, requester_role_id, max_duration, name FROM request_policies WHERE scope_asset_id = $1 ORDER BY id
`

func (q *Queries) ListRequestPoliciesByAsset(ctx context.Context, scopeAssetID pgtype.UUID) ([]RequestPolicy, error) {
	rows, err := q.db.Query(ctx, listRequestPoliciesByAsset, scopeAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestPolicy
	for rows.Next() {
		var i RequestPolicy
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeFolderID,
			&i.ScopeAssetID,
			&i.RequiredApprovals,
			&i.ApproverRoleID,
			&i.CreatedAt,
			&i.RequesterRoleID,
			&i.MaxDuration,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindings = `-- name: ListRoleBindings :many
SELECT
  rb.id, rb.role_id, rb.scope_folder_id, rb.scope_asset_id,
  rb.subject_user_id, rb.subject_group_id, rb.created_at,
  (CASE WHEN rb.subject_group_id IS NOT NULL THEN 'group' ELSE 'user' END)::text AS subject_kind,
  COALESCE(u.display_name, g.name, '')::text AS subject_display_name,
  folder_path(g.folder_id) AS subject_folder_path,
  COALESCE(gm.cnt, 0)::int AS group_member_count,
  r.name AS role_name,
  (CASE
     WHEN rb.scope_asset_id IS NOT NULL THEN
       CASE WHEN folder_path(sa.folder_id) <> '' THEN sa.name || '.' || folder_path(sa.folder_id) ELSE sa.name END
     WHEN rb.scope_folder_id IS NOT NULL THEN folder_path(rb.scope_folder_id)
     ELSE 'global'
   END)::text AS scope_path
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN users u ON u.id = rb.subject_user_id
LEFT JOIN groups g ON g.id = rb.subject_group_id
LEFT JOIN assets sa ON sa.id = rb.scope_asset_id
LEFT JOIN LATERAL (SELECT count(*)::int AS cnt FROM group_memberships m WHERE m.group_id = rb.subject_group_id) gm ON rb.subject_group_id IS NOT NULL
WHERE ($1::uuid IS NULL OR rb.role_id = $1)
  AND ($2::uuid IS NULL OR rb.scope_folder_id = $2)
  AND ($3::uuid IS NULL OR rb.scope_asset_id = $3)
  AND ($4::uuid IS NULL OR rb.subject_user_id = $4)
  AND ($5::uuid IS NULL OR rb.subject_group_id = $5)
  AND (
    -- keyset for ORDER BY created_at DESC, id ASC: strictly older, or same
    -- instant with a later id. A row-comparison ` + "`" + `(created_at,id) < (…)` + "`" + ` is WRONG
    -- here — it would invert the id tiebreak.
    $6::timestamptz IS NULL
    OR rb.created_at < $6
    OR (rb.created_at = $6 AND rb.id > $7::uuid)
  )
ORDER BY rb.created_at DESC, rb.id
LIMIT $8
`

type ListRoleBindingsParams struct {
	RoleID         pgtype.UUID        `json:"role_id"`
	ScopeFolderID  pgtype.UUID        `json:"scope_folder_id"`
	ScopeAssetID   pgtype.UUID        `json:"scope_asset_id"`
	SubjectUserID  pgtype.UUID        `json:"subject_user_id"`
	SubjectGroupID pgtype.UUID        `json:"subject_group_id"`
	AfterTs        pgtype.Timestamptz `json:"after_ts"`
	AfterID        pgtype.UUID        `json:"after_id"`
	Lim            int64              `json:"lim"`
}

type ListRoleBindingsRow struct {
	ID                 uuid.UUID   `json:"id"`
	RoleID             uuid.UUID   `json:"role_id"`
	ScopeFolderID      pgtype.UUID `json:"scope_folder_id"`
	ScopeAssetID       pgtype.UUID `json:"scope_asset_id"`
	SubjectUserID      pgtype.UUID `json:"subject_user_id"`
	SubjectGroupID     pgtype.UUID `json:"subject_group_id"`
	CreatedAt          time.Time   `json:"created_at"`
	SubjectKind        string      `json:"subject_kind"`
	SubjectDisplayName string      `json:"subject_display_name"`
	SubjectFolderPath  string      `json:"subject_folder_path"`
	GroupMemberCount   int32       `json:"group_member_count"`
	RoleName           string      `json:"role_name"`
	ScopePath          string      `json:"scope_path"`
}

// Bindings matching the (all-optional) filters, fully resolved for display in SQL:
// subject kind/name/group-home path/member count, role name, and the binding's scope
// rendered as a dotted path (or 'global'). Single-sources folder-path rendering via
// folder_path(); no per-row Go resolution.
func (q *Queries) ListRoleBindings(ctx context.Context, arg ListRoleBindingsParams) ([]ListRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listRoleBindings,
		arg.RoleID,
		arg.ScopeFolderID,
		arg.ScopeAssetID,
		arg.SubjectUserID,
		arg.SubjectGroupID,
		arg.AfterTs,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleBindingsRow
	for rows.Next() {
		var i ListRoleBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeFolderID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.SubjectGroupID,
			&i.CreatedAt,
			&i.SubjectKind,
			&i.SubjectDisplayName,
			&i.SubjectFolderPath,
			&i.GroupMemberCount,
			&i.RoleName,
			&i.ScopePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsByAsset = `-- name: ListRoleBindingsByAsset :many
SELECT id, role_id, scope_folder_id, scope_asset_id, subject_user_id, subject_group_id, created_at FROM role_bindings WHERE scope_asset_id = $1 ORDER BY id
`

func (q *Queries) ListRoleBindingsByAsset(ctx context.Context, scopeAssetID pgtype.UUID) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsByAsset, scopeAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleBinding
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeFolderID,
			&i.ScopeAssetID,
			&i.SubjectUserID,
			&i.SubjectGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, folder_id, created_at FROM roles
WHERE (
  -- keyset for ORDER BY name ASC, id ASC: row-comparison is correct for
  -- same-direction sort (both ascending). A NULL after_name means first page.
  $1::text IS NULL
  OR (name, id) > ($1, $2::uuid)
)
ORDER BY name, id
LIMIT $3
`

type ListRolesParams struct {
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.AfterName, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByIDs = `-- name: ListRolesByIDs :many
SELECT id, name, folder_id, created_at FROM roles WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListRolesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByIDsPaged = `-- name: ListRolesByIDsPaged :many
SELECT id, name, folder_id, created_at FROM roles
WHERE id = ANY($1::uuid[])
  AND (
    $2::text IS NULL
    OR (name, id) > ($2, $3::uuid)
  )
ORDER BY name, id
LIMIT $4
`

type ListRolesByIDsPagedParams struct {
	Column1   []uuid.UUID `json:"column_1"`
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListRolesByIDsPaged(ctx context.Context, arg ListRolesByIDsPagedParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByIDsPaged,
		arg.Column1,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHAssetLogins = `-- name: ListSSHAssetLogins :many
SELECT asset_id, login, kind, secret_id FROM ssh_asset_login WHERE asset_id = $1 ORDER BY login
`

func (q *Queries) ListSSHAssetLogins(ctx context.Context, assetID uuid.UUID) ([]SshAssetLogin, error) {
	rows, err := q.db.Query(ctx, listSSHAssetLogins, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshAssetLogin
	for rows.Next() {
		var i SshAssetLogin
		if err := rows.Scan(
			&i.AssetID,
			&i.Login,
			&i.Kind,
			&i.SecretID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policiesScopedToFoldersOrAssets = `-- name: PoliciesScopedToFoldersOrAssets :many
SELECT id, role_id, scope_folder_id, scope_asset_id, required_approvals, approver_role_id, created_at, requester_role_id, max_duration, name FROM request_policies
WHERE scope_folder_id = ANY($1::uuid[]) OR scope_asset_id = ANY($2::uuid[])
`

type PoliciesScopedToFoldersOrAssetsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) PoliciesScopedToFoldersOrAssets(ctx context.Context, arg PoliciesScopedToFoldersOrAssetsParams) ([]RequestPolicy, error) {
	rows, err := q.db.Query(ctx, policiesScopedToFoldersOrAssets, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestPolicy
	for rows.Next() {
		var i RequestPolicy
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ScopeFolderID,
			&i.ScopeAssetID,
			&i.RequiredApprovals,
			&i.ApproverRoleID,
			&i.CreatedAt,
			&i.RequesterRoleID,
			&i.MaxDuration,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssetsByIDs = `-- name: SearchAssetsByIDs :many
SELECT id, folder_id, name, labels, created_at, kind FROM assets
WHERE id = ANY($1::uuid[]) AND name ILIKE $2
ORDER BY name, id
LIMIT $3
`

type SearchAssetsByIDsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchAssetsByIDs(ctx context.Context, arg SearchAssetsByIDsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssetsByIDs, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.Labels,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFoldersByIDs = `-- name: SearchFoldersByIDs :many
SELECT id, name, parent_id, created_at, path_ids FROM folders
WHERE id = ANY($1::uuid[]) AND name ILIKE $2
ORDER BY name, id
LIMIT $3
`

type SearchFoldersByIDsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int64       `json:"limit"`
}

// Name-matching folders within a visible-id set. The `name ILIKE` predicate is
// served by the pg_trgm GIN index (idx_folders_name_trgm), so search filters by
// name in the database instead of materializing the whole visible catalog.
func (q *Queries) SearchFoldersByIDs(ctx context.Context, arg SearchFoldersByIDsParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchFoldersByIDs, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.PathIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGroupsByIDs = `-- name: SearchGroupsByIDs :many
SELECT id, name, folder_id, created_at FROM groups
WHERE id = ANY($1::uuid[]) AND name ILIKE $2
ORDER BY name, id
LIMIT $3
`

type SearchGroupsByIDsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchGroupsByIDs(ctx context.Context, arg SearchGroupsByIDsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, searchGroupsByIDs, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRolesByIDs = `-- name: SearchRolesByIDs :many
SELECT id, name, folder_id, created_at FROM roles
WHERE id = ANY($1::uuid[]) AND name ILIKE $2
ORDER BY name, id
LIMIT $3
`

type SearchRolesByIDsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchRolesByIDs(ctx context.Context, arg SearchRolesByIDsParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, searchRolesByIDs, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPostgresAssetConfig = `-- name: UpsertPostgresAssetConfig :one
INSERT INTO postgres_asset_config (asset_id, target_address, target_server_ca, default_database)
VALUES ($1, $2, $3, $4)
ON CONFLICT (asset_id) DO UPDATE SET
  target_address = EXCLUDED.target_address,
  target_server_ca = EXCLUDED.target_server_ca,
  default_database = EXCLUDED.default_database
RETURNING asset_id, target_address, target_server_ca, default_database
`

type UpsertPostgresAssetConfigParams struct {
	AssetID         uuid.UUID `json:"asset_id"`
	TargetAddress   string    `json:"target_address"`
	TargetServerCa  string    `json:"target_server_ca"`
	DefaultDatabase string    `json:"default_database"`
}

func (q *Queries) UpsertPostgresAssetConfig(ctx context.Context, arg UpsertPostgresAssetConfigParams) (PostgresAssetConfig, error) {
	row := q.db.QueryRow(ctx, upsertPostgresAssetConfig,
		arg.AssetID,
		arg.TargetAddress,
		arg.TargetServerCa,
		arg.DefaultDatabase,
	)
	var i PostgresAssetConfig
	err := row.Scan(
		&i.AssetID,
		&i.TargetAddress,
		&i.TargetServerCa,
		&i.DefaultDatabase,
	)
	return i, err
}

const upsertPostgresAssetLogin = `-- name: UpsertPostgresAssetLogin :one
INSERT INTO postgres_asset_login (asset_id, role, kind, secret_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (asset_id, role) DO UPDATE SET
  kind = EXCLUDED.kind,
  secret_id = EXCLUDED.secret_id
RETURNING asset_id, role, kind, secret_id
`

type UpsertPostgresAssetLoginParams struct {
	AssetID  uuid.UUID   `json:"asset_id"`
	Role     string      `json:"role"`
	Kind     string      `json:"kind"`
	SecretID pgtype.UUID `json:"secret_id"`
}

func (q *Queries) UpsertPostgresAssetLogin(ctx context.Context, arg UpsertPostgresAssetLoginParams) (PostgresAssetLogin, error) {
	row := q.db.QueryRow(ctx, upsertPostgresAssetLogin,
		arg.AssetID,
		arg.Role,
		arg.Kind,
		arg.SecretID,
	)
	var i PostgresAssetLogin
	err := row.Scan(
		&i.AssetID,
		&i.Role,
		&i.Kind,
		&i.SecretID,
	)
	return i, err
}

const upsertSSHAssetConfig = `-- name: UpsertSSHAssetConfig :one
INSERT INTO ssh_asset_config (asset_id, host_public_key, target_address)
VALUES ($1, $2, $3)
ON CONFLICT (asset_id) DO UPDATE SET
  host_public_key = EXCLUDED.host_public_key,
  target_address = EXCLUDED.target_address
RETURNING asset_id, target_address, host_public_key
`

type UpsertSSHAssetConfigParams struct {
	AssetID       uuid.UUID `json:"asset_id"`
	HostPublicKey string    `json:"host_public_key"`
	TargetAddress string    `json:"target_address"`
}

func (q *Queries) UpsertSSHAssetConfig(ctx context.Context, arg UpsertSSHAssetConfigParams) (SshAssetConfig, error) {
	row := q.db.QueryRow(ctx, upsertSSHAssetConfig, arg.AssetID, arg.HostPublicKey, arg.TargetAddress)
	var i SshAssetConfig
	err := row.Scan(&i.AssetID, &i.TargetAddress, &i.HostPublicKey)
	return i, err
}

const upsertSSHAssetLogin = `-- name: UpsertSSHAssetLogin :one
INSERT INTO ssh_asset_login (asset_id, login, kind, secret_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (asset_id, login) DO UPDATE SET
  kind = EXCLUDED.kind,
  secret_id = EXCLUDED.secret_id
RETURNING asset_id, login, kind, secret_id
`

type UpsertSSHAssetLoginParams struct {
	AssetID  uuid.UUID   `json:"asset_id"`
	Login    string      `json:"login"`
	Kind     string      `json:"kind"`
	SecretID pgtype.UUID `json:"secret_id"`
}

func (q *Queries) UpsertSSHAssetLogin(ctx context.Context, arg UpsertSSHAssetLoginParams) (SshAssetLogin, error) {
	row := q.db.QueryRow(ctx, upsertSSHAssetLogin,
		arg.AssetID,
		arg.Login,
		arg.Kind,
		arg.SecretID,
	)
	var i SshAssetLogin
	err := row.Scan(
		&i.AssetID,
		&i.Login,
		&i.Kind,
		&i.SecretID,
	)
	return i, err
}
