// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAgentEnrollmentToken = `-- name: ConsumeAgentEnrollmentToken :one
DELETE FROM agent_enrollment_tokens
WHERE token_hash = $1 AND expires_at > now()
RETURNING asset_id
`

func (q *Queries) ConsumeAgentEnrollmentToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAgentEnrollmentToken, tokenHash)
	var asset_id uuid.UUID
	err := row.Scan(&asset_id)
	return asset_id, err
}

const createAgentEnrollmentToken = `-- name: CreateAgentEnrollmentToken :one
INSERT INTO agent_enrollment_tokens (asset_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, asset_id, token_hash, expires_at, created_at
`

type CreateAgentEnrollmentTokenParams struct {
	AssetID   uuid.UUID          `json:"asset_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAgentEnrollmentToken(ctx context.Context, arg CreateAgentEnrollmentTokenParams) (AgentEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createAgentEnrollmentToken, arg.AssetID, arg.TokenHash, arg.ExpiresAt)
	var i AgentEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAgentEnrollmentTokens = `-- name: DeleteExpiredAgentEnrollmentTokens :exec
DELETE FROM agent_enrollment_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAgentEnrollmentTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAgentEnrollmentTokens)
	return err
}
