// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupToGroup = `-- name: AddGroupToGroup :exec
INSERT INTO group_memberships (group_id, member_group_id) VALUES ($1, $2)
`

type AddGroupToGroupParams struct {
	GroupID       uuid.UUID   `json:"group_id"`
	MemberGroupID pgtype.UUID `json:"member_group_id"`
}

func (q *Queries) AddGroupToGroup(ctx context.Context, arg AddGroupToGroupParams) error {
	_, err := q.db.Exec(ctx, addGroupToGroup, arg.GroupID, arg.MemberGroupID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO group_memberships (group_id, member_user_id) VALUES ($1, $2)
`

type AddUserToGroupParams struct {
	GroupID      uuid.UUID   `json:"group_id"`
	MemberUserID pgtype.UUID `json:"member_user_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.GroupID, arg.MemberUserID)
	return err
}

const countAssetsInFolder = `-- name: CountAssetsInFolder :one
SELECT count(*) FROM assets WHERE folder_id = $1
`

func (q *Queries) CountAssetsInFolder(ctx context.Context, folderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsInFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBindingsScopedToFolder = `-- name: CountBindingsScopedToFolder :one
SELECT count(*) FROM role_bindings WHERE scope_folder_id = $1
`

func (q *Queries) CountBindingsScopedToFolder(ctx context.Context, scopeFolderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBindingsScopedToFolder, scopeFolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChildFolders = `-- name: CountChildFolders :one
SELECT count(*) FROM folders WHERE parent_id = $1
`

func (q *Queries) CountChildFolders(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildFolders, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*)::int FROM group_memberships WHERE group_id = $1
`

// Direct membership count for a group (users + nested groups), for roster/badge display.
func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGroupsHomedInFolder = `-- name: CountGroupsHomedInFolder :one
SELECT count(*) FROM groups WHERE folder_id = $1
`

func (q *Queries) CountGroupsHomedInFolder(ctx context.Context, folderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsHomedInFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoliciesScopedToFolder = `-- name: CountPoliciesScopedToFolder :one
SELECT count(*) FROM request_policies WHERE scope_folder_id = $1
`

func (q *Queries) CountPoliciesScopedToFolder(ctx context.Context, scopeFolderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesScopedToFolder, scopeFolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRolesHomedInFolder = `-- name: CountRolesHomedInFolder :one
SELECT count(*) FROM roles WHERE folder_id = $1
`

func (q *Queries) CountRolesHomedInFolder(ctx context.Context, folderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesHomedInFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (folder_id, name, labels, kind) VALUES ($1, $2, $3, $4) RETURNING id, folder_id, name, labels, created_at, kind
`

type CreateAssetParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	Name     string    `json:"name"`
	Labels   []byte    `json:"labels"`
	Kind     string    `json:"kind"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.FolderID,
		arg.Name,
		arg.Labels,
		arg.Kind,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Labels,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (name, parent_id) VALUES ($1, $2) RETURNING id, name, parent_id, created_at, path_ids
`

type CreateFolderParams struct {
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.PathIds,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, folder_id) VALUES ($1, $2) RETURNING id, name, folder_id, created_at
`

type CreateGroupParams struct {
	Name     string      `json:"name"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.FolderID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, folder_id) VALUES ($1, $2) RETURNING id, name, folder_id, created_at
`

type CreateRoleParams struct {
	Name     string      `json:"name"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.FolderID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleBinding = `-- name: CreateRoleBinding :one
INSERT INTO role_bindings
  (role_id, scope_folder_id, scope_asset_id, subject_user_id, subject_group_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, role_id, scope_folder_id, scope_asset_id, subject_user_id, subject_group_id, created_at
`

type CreateRoleBindingParams struct {
	RoleID         uuid.UUID   `json:"role_id"`
	ScopeFolderID  pgtype.UUID `json:"scope_folder_id"`
	ScopeAssetID   pgtype.UUID `json:"scope_asset_id"`
	SubjectUserID  pgtype.UUID `json:"subject_user_id"`
	SubjectGroupID pgtype.UUID `json:"subject_group_id"`
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, createRoleBinding,
		arg.RoleID,
		arg.ScopeFolderID,
		arg.ScopeAssetID,
		arg.SubjectUserID,
		arg.SubjectGroupID,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ScopeFolderID,
		&i.ScopeAssetID,
		&i.SubjectUserID,
		&i.SubjectGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name) VALUES ($1, $2) RETURNING id, email, display_name, created_at, password_hash, deactivated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.DeactivatedAt,
	)
	return i, err
}

const createUserFull = `-- name: CreateUserFull :one
INSERT INTO users (email, display_name) VALUES ($1, $2) RETURNING id, email, display_name, created_at, password_hash, deactivated_at
`

type CreateUserFullParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUserFull(ctx context.Context, arg CreateUserFullParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFull, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.DeactivatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET deactivated_at = now() WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

// Deletes the role row. The role's name uniqueness is enforced by the partial
// UNIQUE indexes on roles(name)/roles(folder_id, name), so deleting the row frees
// the name automatically (no separate registry entry). Final step of DeleteRole,
// run only after its bindings/edges/policies are removed and its grants revoked.
func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, folder_id, name, labels, created_at, kind FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Labels,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, folder_id, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByFolderAndName = `-- name: GetGroupByFolderAndName :one
SELECT id, name, folder_id, created_at FROM groups WHERE folder_id = $1 AND name = $2
`

type GetGroupByFolderAndNameParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetGroupByFolderAndName(ctx context.Context, arg GetGroupByFolderAndNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByFolderAndName, arg.FolderID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByNameGlobal = `-- name: GetGroupByNameGlobal :one
SELECT id, name, folder_id, created_at FROM groups WHERE name = $1 AND folder_id IS NULL
`

func (q *Queries) GetGroupByNameGlobal(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByNameGlobal, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const groupNestingCyclic = `-- name: GroupNestingCyclic :one
WITH RECURSIVE supergroups(gid) AS (
    SELECT group_id FROM group_memberships WHERE member_group_id = $2
  UNION
    SELECT gm.group_id FROM group_memberships gm JOIN supergroups sg ON gm.member_group_id = sg.gid
)
SELECT EXISTS (SELECT 1 FROM supergroups WHERE gid = $1)
`

type GroupNestingCyclicParams struct {
	MemberGroupID pgtype.UUID `json:"member_group_id"`
	GroupID       pgtype.UUID `json:"group_id"`
}

// AddGroupToGroup cycle check: whether making member_group_id a member of group_id
// would close a cycle — true iff group_id is ALREADY a transitive supergroup of
// member_group_id (walking member->super edges up from group_id).
func (q *Queries) GroupNestingCyclic(ctx context.Context, arg GroupNestingCyclicParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupNestingCyclic, arg.MemberGroupID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAssetName = `-- name: InsertAssetName :exec
INSERT INTO catalog_names (parent_id, name, asset_id) VALUES ($1, $2, $3)
`

type InsertAssetNameParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) InsertAssetName(ctx context.Context, arg InsertAssetNameParams) error {
	_, err := q.db.Exec(ctx, insertAssetName, arg.ParentID, arg.Name, arg.AssetID)
	return err
}

const insertFolderName = `-- name: InsertFolderName :exec
INSERT INTO catalog_names (parent_id, name, folder_id) VALUES ($1, $2, $3)
`

type InsertFolderNameParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) InsertFolderName(ctx context.Context, arg InsertFolderNameParams) error {
	_, err := q.db.Exec(ctx, insertFolderName, arg.ParentID, arg.Name, arg.FolderID)
	return err
}

const insertRoleCapability = `-- name: InsertRoleCapability :exec
INSERT INTO role_capabilities (role_id, scope, action, qualifier) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type InsertRoleCapabilityParams struct {
	RoleID    uuid.UUID `json:"role_id"`
	Scope     string    `json:"scope"`
	Action    string    `json:"action"`
	Qualifier string    `json:"qualifier"`
}

func (q *Queries) InsertRoleCapability(ctx context.Context, arg InsertRoleCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertRoleCapability,
		arg.RoleID,
		arg.Scope,
		arg.Action,
		arg.Qualifier,
	)
	return err
}

const listGroupMembersPaged = `-- name: ListGroupMembersPaged :many
SELECT gm.id, gm.group_id, gm.member_user_id, gm.member_group_id, gm.created_at FROM group_memberships gm
WHERE gm.group_id = $1
  AND (
    $2::timestamptz IS NULL
    OR gm.created_at < $2
    OR (gm.created_at = $2 AND gm.id > $3::uuid)
  )
ORDER BY gm.created_at DESC, gm.id
LIMIT $4
`

type ListGroupMembersPagedParams struct {
	GroupID uuid.UUID          `json:"group_id"`
	AfterTs pgtype.Timestamptz `json:"after_ts"`
	AfterID pgtype.UUID        `json:"after_id"`
	Lim     int64              `json:"lim"`
}

// Single keyset scan over group_memberships ordered by (created_at DESC, id).
// Each row is either a user-member (member_user_id non-null) or group-member
// (member_group_id non-null); the handler splits them.
func (q *Queries) ListGroupMembersPaged(ctx context.Context, arg ListGroupMembersPagedParams) ([]GroupMembership, error) {
	rows, err := q.db.Query(ctx, listGroupMembersPaged,
		arg.GroupID,
		arg.AfterTs,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMembership
	for rows.Next() {
		var i GroupMembership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.MemberUserID,
			&i.MemberGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByIDsPaged = `-- name: ListGroupsByIDsPaged :many
SELECT id, name, folder_id, created_at FROM groups
WHERE id = ANY($1::uuid[])
  AND (
    $2::text IS NULL
    OR (name, id) > ($2, $3::uuid)
  )
ORDER BY name, id
LIMIT $4
`

type ListGroupsByIDsPagedParams struct {
	Column1   []uuid.UUID `json:"column_1"`
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListGroupsByIDsPaged(ctx context.Context, arg ListGroupsByIDsPagedParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByIDsPaged,
		arg.Column1,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsPaged = `-- name: ListGroupsPaged :many
SELECT id, name, folder_id, created_at FROM groups
WHERE (
  $1::text IS NULL
  OR (name, id) > ($1, $2::uuid)
)
ORDER BY name, id
LIMIT $3
`

type ListGroupsPagedParams struct {
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListGroupsPaged(ctx context.Context, arg ListGroupsPagedParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsPaged, arg.AfterName, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, created_at, password_hash, deactivated_at FROM users
WHERE (
  $1::text IS NULL
  OR (email, id) > ($1, $2::uuid)
)
ORDER BY email, id
LIMIT $3
`

type ListUsersParams struct {
	AfterEmail pgtype.Text `json:"after_email"`
	AfterID    pgtype.UUID `json:"after_id"`
	Lim        int64       `json:"lim"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.AfterEmail, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyAuthzChanged = `-- name: NotifyAuthzChanged :exec
SELECT pg_notify('authz_changed', '')
`

func (q *Queries) NotifyAuthzChanged(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyAuthzChanged)
	return err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users SET deactivated_at = NULL WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const removeGroupFromGroup = `-- name: RemoveGroupFromGroup :exec
DELETE FROM group_memberships WHERE group_id = $1 AND member_group_id = $2
`

type RemoveGroupFromGroupParams struct {
	GroupID       uuid.UUID   `json:"group_id"`
	MemberGroupID pgtype.UUID `json:"member_group_id"`
}

func (q *Queries) RemoveGroupFromGroup(ctx context.Context, arg RemoveGroupFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeGroupFromGroup, arg.GroupID, arg.MemberGroupID)
	return err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM group_memberships WHERE group_id = $1 AND member_user_id = $2
`

type RemoveUserFromGroupParams struct {
	GroupID      uuid.UUID   `json:"group_id"`
	MemberUserID pgtype.UUID `json:"member_user_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.GroupID, arg.MemberUserID)
	return err
}

const roleCapabilityRows = `-- name: RoleCapabilityRows :many
SELECT scope, action, qualifier FROM role_capabilities WHERE role_id = $1
`

type RoleCapabilityRowsRow struct {
	Scope     string `json:"scope"`
	Action    string `json:"action"`
	Qualifier string `json:"qualifier"`
}

func (q *Queries) RoleCapabilityRows(ctx context.Context, roleID uuid.UUID) ([]RoleCapabilityRowsRow, error) {
	rows, err := q.db.Query(ctx, roleCapabilityRows, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleCapabilityRowsRow
	for rows.Next() {
		var i RoleCapabilityRowsRow
		if err := rows.Scan(&i.Scope, &i.Action, &i.Qualifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetCatalogName = `-- name: UpdateAssetCatalogName :exec
UPDATE catalog_names SET parent_id = $2, name = $3 WHERE asset_id = $1
`

type UpdateAssetCatalogNameParams struct {
	AssetID  pgtype.UUID `json:"asset_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) UpdateAssetCatalogName(ctx context.Context, arg UpdateAssetCatalogNameParams) error {
	_, err := q.db.Exec(ctx, updateAssetCatalogName, arg.AssetID, arg.ParentID, arg.Name)
	return err
}

const updateAssetFolder = `-- name: UpdateAssetFolder :exec
UPDATE assets SET folder_id = $2 WHERE id = $1
`

type UpdateAssetFolderParams struct {
	ID       uuid.UUID `json:"id"`
	FolderID uuid.UUID `json:"folder_id"`
}

func (q *Queries) UpdateAssetFolder(ctx context.Context, arg UpdateAssetFolderParams) error {
	_, err := q.db.Exec(ctx, updateAssetFolder, arg.ID, arg.FolderID)
	return err
}

const updateAssetName = `-- name: UpdateAssetName :exec
UPDATE assets SET name = $2 WHERE id = $1
`

type UpdateAssetNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateAssetName(ctx context.Context, arg UpdateAssetNameParams) error {
	_, err := q.db.Exec(ctx, updateAssetName, arg.ID, arg.Name)
	return err
}

const updateFolderCatalogName = `-- name: UpdateFolderCatalogName :exec
UPDATE catalog_names SET parent_id = $2, name = $3 WHERE folder_id = $1
`

type UpdateFolderCatalogNameParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) UpdateFolderCatalogName(ctx context.Context, arg UpdateFolderCatalogNameParams) error {
	_, err := q.db.Exec(ctx, updateFolderCatalogName, arg.FolderID, arg.ParentID, arg.Name)
	return err
}

const updateFolderName = `-- name: UpdateFolderName :exec
UPDATE folders SET name = $2 WHERE id = $1
`

type UpdateFolderNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) error {
	_, err := q.db.Exec(ctx, updateFolderName, arg.ID, arg.Name)
	return err
}

const updateFolderParent = `-- name: UpdateFolderParent :exec
UPDATE folders SET parent_id = $2 WHERE id = $1
`

type UpdateFolderParentParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) error {
	_, err := q.db.Exec(ctx, updateFolderParent, arg.ID, arg.ParentID)
	return err
}
