// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingNotifications = `-- name: CountPendingNotifications :one
SELECT count(*) FROM notification_outbox WHERE state = 'pending'
`

func (q *Queries) CountPendingNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox (idempotency_key, kind, subject, payload, max_attempts, next_delivery_at)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type EnqueueNotificationParams struct {
	IdempotencyKey string             `json:"idempotency_key"`
	Kind           string             `json:"kind"`
	Subject        string             `json:"subject"`
	Payload        []byte             `json:"payload"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextDeliveryAt pgtype.Timestamptz `json:"next_delivery_at"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.IdempotencyKey,
		arg.Kind,
		arg.Subject,
		arg.Payload,
		arg.MaxAttempts,
		arg.NextDeliveryAt,
	)
	return err
}

const getProbeSchedule = `-- name: GetProbeSchedule :one
SELECT asset_id, probe_interval_seconds, freshness_seconds, enabled, created_at, updated_at FROM target_identity_probe_schedules WHERE asset_id = $1
`

func (q *Queries) GetProbeSchedule(ctx context.Context, assetID uuid.UUID) (TargetIdentityProbeSchedule, error) {
	row := q.db.QueryRow(ctx, getProbeSchedule, assetID)
	var i TargetIdentityProbeSchedule
	err := row.Scan(
		&i.AssetID,
		&i.ProbeIntervalSeconds,
		&i.FreshnessSeconds,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApproachingAnchorExpiry = `-- name: ListApproachingAnchorExpiry :many
SELECT ta.asset_id, ta.endpoint_revision, ta.id AS anchor_id, ta.expires_at
FROM target_trust_anchors ta
JOIN target_identity_probe_schedules s ON s.asset_id = ta.asset_id
JOIN assets a ON a.id = ta.asset_id AND a.endpoint_revision = ta.endpoint_revision
WHERE s.enabled
  AND ta.revoked_at IS NULL
  AND ta.expires_at IS NOT NULL
  AND ta.approved_at <= $1::timestamptz
  AND (ta.not_before IS NULL OR ta.not_before <= $1::timestamptz)
  AND ta.expires_at > $1::timestamptz
  AND ta.expires_at <= $1::timestamptz + ($2::bigint * interval '1 second')
`

type ListApproachingAnchorExpiryParams struct {
	AtTime      time.Time `json:"at_time"`
	WarnSeconds int64     `json:"warn_seconds"`
}

type ListApproachingAnchorExpiryRow struct {
	AssetID          uuid.UUID          `json:"asset_id"`
	EndpointRevision int64              `json:"endpoint_revision"`
	AnchorID         uuid.UUID          `json:"anchor_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// ListApproachingAnchorExpiry returns active anchors on enabled schedules whose
// expires_at falls inside the warning window ahead of the reference time.
func (q *Queries) ListApproachingAnchorExpiry(ctx context.Context, arg ListApproachingAnchorExpiryParams) ([]ListApproachingAnchorExpiryRow, error) {
	rows, err := q.db.Query(ctx, listApproachingAnchorExpiry, arg.AtTime, arg.WarnSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApproachingAnchorExpiryRow
	for rows.Next() {
		var i ListApproachingAnchorExpiryRow
		if err := rows.Scan(
			&i.AssetID,
			&i.EndpointRevision,
			&i.AnchorID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApproachingFreshnessExpiry = `-- name: ListApproachingFreshnessExpiry :many
SELECT s.asset_id,
       a.endpoint_revision,
       (last.observed_at + (s.freshness_seconds * interval '1 second'))::timestamptz AS expires_at
FROM target_identity_probe_schedules s
JOIN assets a ON a.id = s.asset_id
JOIN LATERAL (
    SELECT max(o.observed_at) AS observed_at
    FROM target_identity_observations o
    WHERE o.asset_id = s.asset_id
      AND o.endpoint_revision = a.endpoint_revision
      AND o.outcome = 'succeeded'
) last ON true
WHERE s.enabled
  AND s.freshness_seconds IS NOT NULL
  AND last.observed_at IS NOT NULL
  AND (last.observed_at + (s.freshness_seconds * interval '1 second')) > $1::timestamptz
  AND (last.observed_at + (s.freshness_seconds * interval '1 second')) <= $1::timestamptz + ($2::bigint * interval '1 second')
`

type ListApproachingFreshnessExpiryParams struct {
	AtTime      time.Time `json:"at_time"`
	WarnSeconds int64     `json:"warn_seconds"`
}

type ListApproachingFreshnessExpiryRow struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
	ExpiresAt        time.Time `json:"expires_at"`
}

// ListApproachingFreshnessExpiry returns enabled schedules with a freshness policy
// whose latest successful observation is about to age past the freshness window
// (its derived expiry falls inside the warning window ahead of the reference time).
func (q *Queries) ListApproachingFreshnessExpiry(ctx context.Context, arg ListApproachingFreshnessExpiryParams) ([]ListApproachingFreshnessExpiryRow, error) {
	rows, err := q.db.Query(ctx, listApproachingFreshnessExpiry, arg.AtTime, arg.WarnSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApproachingFreshnessExpiryRow
	for rows.Next() {
		var i ListApproachingFreshnessExpiryRow
		if err := rows.Scan(&i.AssetID, &i.EndpointRevision, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueNotifications = `-- name: ListDueNotifications :many
SELECT id, idempotency_key, kind, subject, payload, attempts, max_attempts
FROM notification_outbox
WHERE state = 'pending'
  AND next_delivery_at <= $1::timestamptz
ORDER BY next_delivery_at, seq
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueNotificationsParams struct {
	AtTime time.Time `json:"at_time"`
	Batch  int64     `json:"batch"`
}

type ListDueNotificationsRow struct {
	ID             uuid.UUID `json:"id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Kind           string    `json:"kind"`
	Subject        string    `json:"subject"`
	Payload        []byte    `json:"payload"`
	Attempts       int32     `json:"attempts"`
	MaxAttempts    int32     `json:"max_attempts"`
}

func (q *Queries) ListDueNotifications(ctx context.Context, arg ListDueNotificationsParams) ([]ListDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listDueNotifications, arg.AtTime, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueNotificationsRow
	for rows.Next() {
		var i ListDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Kind,
			&i.Subject,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePeriodicProbes = `-- name: ListDuePeriodicProbes :many
SELECT s.asset_id, a.endpoint_revision
FROM target_identity_probe_schedules s
JOIN assets a ON a.id = s.asset_id
WHERE s.enabled
  AND a.kind IN ('ssh','postgres','rdp','k8s')
  AND NOT EXISTS (
      SELECT 1 FROM target_probe_jobs j
      WHERE j.asset_id = s.asset_id
        AND j.endpoint_revision = a.endpoint_revision
        AND j.reason = 'periodic'
        AND j.state IN ('queued','leased')
  )
  AND COALESCE(
        (SELECT max(o.observed_at)
         FROM target_identity_observations o
         WHERE o.asset_id = s.asset_id
           AND o.endpoint_revision = a.endpoint_revision),
        'epoch'::timestamptz
      ) < $1::timestamptz - (s.probe_interval_seconds * interval '1 second')
ORDER BY s.asset_id
FOR UPDATE OF s SKIP LOCKED
LIMIT $2
`

type ListDuePeriodicProbesParams struct {
	AtTime time.Time `json:"at_time"`
	Batch  int64     `json:"batch"`
}

type ListDuePeriodicProbesRow struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

// ListDuePeriodicProbes selects assets whose enabled schedule is due for a fresh
// periodic probe against their CURRENT endpoint revision: no active (queued/leased)
// periodic probe exists, and the most recent observation for that revision (if any)
// is older than the per-asset probe interval measured from the supplied reference
// time. FOR UPDATE SKIP LOCKED partitions due rows across concurrent schedulers so
// replicas claim disjoint batches; the partial unique index is the correctness
// backstop against duplicate current-revision jobs.
func (q *Queries) ListDuePeriodicProbes(ctx context.Context, arg ListDuePeriodicProbesParams) ([]ListDuePeriodicProbesRow, error) {
	rows, err := q.db.Query(ctx, listDuePeriodicProbes, arg.AtTime, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDuePeriodicProbesRow
	for rows.Next() {
		var i ListDuePeriodicProbesRow
		if err := rows.Scan(&i.AssetID, &i.EndpointRevision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepeatedProbeFailures = `-- name: ListRepeatedProbeFailures :many
SELECT s.asset_id,
       a.endpoint_revision,
       fail.failure_count::bigint AS failure_count,
       fail.latest_failed_job_id::uuid AS latest_failed_job_id
FROM target_identity_probe_schedules s
JOIN assets a ON a.id = s.asset_id
JOIN LATERAL (
    SELECT count(*) AS failure_count,
           (array_agg(j.id ORDER BY j.completed_at DESC, j.id DESC))[1] AS latest_failed_job_id
    FROM target_probe_jobs j
    WHERE j.asset_id = s.asset_id
      AND j.endpoint_revision = a.endpoint_revision
      AND j.state = 'failed'
      AND j.completed_at > COALESCE((
          SELECT max(o.observed_at)
          FROM target_identity_observations o
          WHERE o.asset_id = s.asset_id
            AND o.endpoint_revision = a.endpoint_revision
            AND o.outcome = 'succeeded'
      ), 'epoch'::timestamptz)
) fail ON true
WHERE s.enabled
  AND fail.failure_count >= $1::bigint
`

type ListRepeatedProbeFailuresRow struct {
	AssetID           uuid.UUID `json:"asset_id"`
	EndpointRevision  int64     `json:"endpoint_revision"`
	FailureCount      int64     `json:"failure_count"`
	LatestFailedJobID uuid.UUID `json:"latest_failed_job_id"`
}

// ListRepeatedProbeFailures returns enabled schedules whose current revision has
// accumulated at least the threshold of failed probe jobs since the last successful
// observation. This is the connectivity-degraded signal: it drives a notification
// but never a trust change.
func (q *Queries) ListRepeatedProbeFailures(ctx context.Context, threshold int64) ([]ListRepeatedProbeFailuresRow, error) {
	rows, err := q.db.Query(ctx, listRepeatedProbeFailures, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepeatedProbeFailuresRow
	for rows.Next() {
		var i ListRepeatedProbeFailuresRow
		if err := rows.Scan(
			&i.AssetID,
			&i.EndpointRevision,
			&i.FailureCount,
			&i.LatestFailedJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedMismatches = `-- name: ListUnresolvedMismatches :many
SELECT o.asset_id, o.endpoint_revision, o.id AS observation_id
FROM target_identity_probe_schedules s
JOIN assets a ON a.id = s.asset_id
JOIN target_identity_observations o
  ON o.asset_id = s.asset_id AND o.endpoint_revision = a.endpoint_revision
WHERE s.enabled
  AND o.outcome = 'mismatch'
  AND NOT EXISTS (
      SELECT 1 FROM target_trust_anchors ta
      WHERE ta.asset_id = o.asset_id
        AND ta.endpoint_revision = o.endpoint_revision
        AND ta.observation_id = o.id
        AND ta.revoked_at IS NULL
        AND ta.approved_at <= $1::timestamptz
        AND (ta.not_before IS NULL OR ta.not_before <= $1::timestamptz)
        AND (ta.expires_at IS NULL OR ta.expires_at > $1::timestamptz)
  )
  AND NOT EXISTS (
      SELECT 1 FROM audit_outbox
      WHERE event_type = 'target_identity.observation_rejected'
        AND subject = 'asset:' || o.asset_id::text
        AND details->>'observation_id' = o.id::text
  )
  AND NOT EXISTS (
      SELECT 1 FROM audit_log
      WHERE event_type = 'target_identity.observation_rejected'
        AND subject = 'asset:' || o.asset_id::text
        AND details->>'observation_id' = o.id::text
  )
`

type ListUnresolvedMismatchesRow struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
	ObservationID    uuid.UUID `json:"observation_id"`
}

// ListUnresolvedMismatches returns current-revision mismatch observations for
// enabled schedules that are neither approved (an active anchor tied to the exact
// observation) nor explicitly rejected (an observation_rejected audit event).
func (q *Queries) ListUnresolvedMismatches(ctx context.Context, atTime time.Time) ([]ListUnresolvedMismatchesRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedMismatches, atTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnresolvedMismatchesRow
	for rows.Next() {
		var i ListUnresolvedMismatchesRow
		if err := rows.Scan(&i.AssetID, &i.EndpointRevision, &i.ObservationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE notification_outbox
SET state = 'delivered', attempts = attempts + 1, delivered_at = $1, last_error = NULL
WHERE id = $2
`

type MarkNotificationDeliveredParams struct {
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, arg.DeliveredAt, arg.ID)
	return err
}

const rescheduleNotification = `-- name: RescheduleNotification :exec
UPDATE notification_outbox
SET attempts = attempts + 1,
    last_error = $1,
    state = CASE WHEN attempts + 1 >= max_attempts THEN 'failed' ELSE 'pending' END,
    next_delivery_at = $2
WHERE id = $3
`

type RescheduleNotificationParams struct {
	LastError      pgtype.Text        `json:"last_error"`
	NextDeliveryAt pgtype.Timestamptz `json:"next_delivery_at"`
	ID             uuid.UUID          `json:"id"`
}

// RescheduleNotification records one failed delivery attempt. It goes terminal
// ('failed') once attempts reach max_attempts, otherwise stays 'pending' with a
// caller-computed backoff deadline. It NEVER touches authorization or identity state.
func (q *Queries) RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) error {
	_, err := q.db.Exec(ctx, rescheduleNotification, arg.LastError, arg.NextDeliveryAt, arg.ID)
	return err
}

const upsertProbeSchedule = `-- name: UpsertProbeSchedule :one

INSERT INTO target_identity_probe_schedules (
    asset_id, probe_interval_seconds, freshness_seconds, enabled
) VALUES (
    $1, $2,
    $3::bigint, $4
)
ON CONFLICT (asset_id) DO UPDATE
SET probe_interval_seconds = excluded.probe_interval_seconds,
    freshness_seconds = excluded.freshness_seconds,
    enabled = excluded.enabled,
    updated_at = now()
RETURNING asset_id, probe_interval_seconds, freshness_seconds, enabled, created_at, updated_at
`

type UpsertProbeScheduleParams struct {
	AssetID              uuid.UUID   `json:"asset_id"`
	ProbeIntervalSeconds int64       `json:"probe_interval_seconds"`
	FreshnessSeconds     pgtype.Int8 `json:"freshness_seconds"`
	Enabled              bool        `json:"enabled"`
}

// Periodic-probe scheduling and the durable notification outbox.
func (q *Queries) UpsertProbeSchedule(ctx context.Context, arg UpsertProbeScheduleParams) (TargetIdentityProbeSchedule, error) {
	row := q.db.QueryRow(ctx, upsertProbeSchedule,
		arg.AssetID,
		arg.ProbeIntervalSeconds,
		arg.FreshnessSeconds,
		arg.Enabled,
	)
	var i TargetIdentityProbeSchedule
	err := row.Scan(
		&i.AssetID,
		&i.ProbeIntervalSeconds,
		&i.FreshnessSeconds,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
