// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireAuditLock(ctx context.Context) error
	// Active (unrevoked, unexpired) grants for a subject on an asset. Used to attribute
	// a JIT session to its grant when exactly one is active.
	ActiveGrantIDsForUserAsset(ctx context.Context, arg ActiveGrantIDsForUserAssetParams) ([]uuid.UUID, error)
	AddApproval(ctx context.Context, arg AddApprovalParams) (AccessRequestApproval, error)
	AddGroupToGroup(ctx context.Context, arg AddGroupToGroupParams) error
	AddPolicySubject(ctx context.Context, arg AddPolicySubjectParams) (RequestPolicySubject, error)
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	// allFolderIDs: every folder id (root+cascade candidate set = the whole tree).
	AllFolderIDs(ctx context.Context) ([]uuid.UUID, error)
	// [14] anchorHomeFolders: the union of the three folder-id anchor sources hanging
	// off folder-homed nodes — the home folders of roles/groups visible to the user and
	// the folders of assets visible to the user. Per kind visibility is (the pre-computed
	// ACCESS id set) ∪ (MANAGEMENT via the kind's read cap over authz_held /
	// authz_global_held) ∪ (for assets, CONNECT via an ssh:login entitled over the full
	// asset-scope cascade). Management cascades DOWN a folder subtree (ltree <@).
	AnchorHomeFolders(ctx context.Context, arg AnchorHomeFoldersParams) ([]pgtype.UUID, error)
	// [22] accessrequest.approvablePending: the pending access requests the caller may
	// approve, with their current approve-count, resolved set-based (reproducing
	// IsApprover over the whole candidate set). A candidate is included when the caller
	// is neither its requester nor deactivated AND, for the request's EFFECTIVE policy
	// (authz_effective_request_policy — the same asset/folder-ancestor/global precedence
	// as EffectiveRule), the caller is either an explicit kind='approver' subject (direct
	// or via a nested group, authz_user_groups) OR holds the policy's approver_role
	// STANDING on the asset (authz_held_standing). @restrict limits the candidate set to
	// those request ids (a keyset page); a NULL array considers all pending requests.
	// Ordered created_at DESC, id to match the paged SQL page order.
	ApprovablePending(ctx context.Context, arg ApprovablePendingParams) ([]ApprovablePendingRow, error)
	// [25] approvals.IsApprover explicit-subject arm. The caller is an explicit
	// approver subject of the policy when a request_policy_subjects(kind='approver') row
	// names them directly or via a (nested) group — subject to the deactivation guard.
	ApproverSubjectExists(ctx context.Context, arg ApproverSubjectExistsParams) (bool, error)
	AssetByFolderName(ctx context.Context, arg AssetByFolderNameParams) (Asset, error)
	AssetIDsInFolders(ctx context.Context, dollar_1 []uuid.UUID) ([]AssetIDsInFoldersRow, error)
	// assetLoginsFor: the SSH login names declared on each asset in `asset_ids`.
	AssetLoginsForAssets(ctx context.Context, assetIds []uuid.UUID) ([]AssetLoginsForAssetsRow, error)
	AuditChainTip(ctx context.Context) (AuditChainTipRow, error)
	AuditEntryHashAtSeq(ctx context.Context, seq int64) ([]byte, error)
	BindingsScopedToFoldersOrAssets(ctx context.Context, arg BindingsScopedToFoldersOrAssetsParams) ([]RoleBinding, error)
	// childFolderIDs: the ids of folders directly under `parent`, ordered by (name, id).
	// A NULL parent selects the tree root (parent_id IS NULL).
	ChildFolderIDs(ctx context.Context, parent pgtype.UUID) ([]uuid.UUID, error)
	ConsumeAgentEnrollmentToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error)
	CountApprovals(ctx context.Context, requestID uuid.UUID) (int64, error)
	CountAssetsInFolder(ctx context.Context, folderID uuid.UUID) (int64, error)
	CountBindingsScopedToFolder(ctx context.Context, scopeFolderID pgtype.UUID) (int64, error)
	CountChildFolders(ctx context.Context, parentID pgtype.UUID) (int64, error)
	// Direct membership count for a group (users + nested groups), for roster/badge display.
	CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int32, error)
	CountGroupsHomedInFolder(ctx context.Context, folderID pgtype.UUID) (int64, error)
	CountOutbox(ctx context.Context) (int64, error)
	CountPoliciesScopedToFolder(ctx context.Context, scopeFolderID pgtype.UUID) (int64, error)
	CountRolesHomedInFolder(ctx context.Context, folderID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccessGrant(ctx context.Context, arg CreateAccessGrantParams) (AccessGrant, error)
	CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (AccessRequest, error)
	CreateAgentEnrollmentToken(ctx context.Context, arg CreateAgentEnrollmentTokenParams) (AgentEnrollmentToken, error)
	// The asset's catalog_names entry is registered by an AFTER INSERT trigger
	// (trg_assets_register_name), so an asset can never exist without a resolvable name.
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateCAKey(ctx context.Context, arg CreateCAKeyParams) (CaKey, error)
	// The folder's catalog_names entry is registered by an AFTER INSERT trigger
	// (trg_folders_register_name), so a folder can never exist without a resolvable name.
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateRequestPolicy(ctx context.Context, arg CreateRequestPolicyParams) (RequestPolicy, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (RoleBinding, error)
	CreateRoleGrant(ctx context.Context, arg CreateRoleGrantParams) (RoleGrant, error)
	CreateSessionSigningKey(ctx context.Context, arg CreateSessionSigningKeyParams) (SessionSigningKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserFull(ctx context.Context, arg CreateUserFullParams) (User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteAsset(ctx context.Context, id uuid.UUID) error
	DeleteAssetSecret(ctx context.Context, id uuid.UUID) error
	DeleteAssetSecretsForAsset(ctx context.Context, assetID uuid.UUID) error
	DeleteAuthToken(ctx context.Context, tokenHash []byte) error
	DeleteExpiredAgentEnrollmentTokens(ctx context.Context) error
	DeleteExpiredAuthTokens(ctx context.Context) error
	DeleteFolder(ctx context.Context, id uuid.UUID) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteLiveSession(ctx context.Context, id uuid.UUID) (int64, error)
	// Drop asset_secrets no longer referenced by any of the asset's logins (ssh OR
	// postgres). A postgres password login references a secret via secret_id too, so it
	// must be counted here or the secret is wrongly deemed orphan and its DELETE trips
	// the postgres_login_secret_same_asset FK (ON DELETE RESTRICT).
	DeleteOrphanSecretsForAsset(ctx context.Context, assetID uuid.UUID) error
	DeleteOutboxEvent(ctx context.Context, id uuid.UUID) error
	// Deletes the policies for which the role is the requestable role (meaningless once
	// the role is gone). Part of the DeleteRole cascade.
	DeletePoliciesForRole(ctx context.Context, roleID uuid.UUID) error
	// Removes the subjects of every policy whose requestable role is $1 (those policies
	// are about to be deleted). Part of the DeleteRole cascade.
	DeletePolicySubjectsForRole(ctx context.Context, roleID uuid.UUID) error
	DeletePostgresAssetLoginsForAsset(ctx context.Context, assetID uuid.UUID) error
	DeleteRequestPolicy(ctx context.Context, id uuid.UUID) error
	// Deletes the role row. The role's name uniqueness is enforced by the partial
	// UNIQUE indexes on roles(name)/roles(folder_id, name), so deleting the row frees
	// the name automatically (no separate registry entry). Final step of DeleteRole,
	// run only after its bindings/edges/policies are removed and its grants revoked.
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteRoleBinding(ctx context.Context, id uuid.UUID) error
	// Removes every standing binding of the role. Part of the DeleteRole cascade.
	DeleteRoleBindingsForRole(ctx context.Context, roleID uuid.UUID) error
	DeleteRoleGrant(ctx context.Context, id uuid.UUID) error
	// Removes every rewrite edge touching the role, in either direction (the role as
	// the conferred role_id, or as the source that confers another). Part of DeleteRole.
	DeleteRoleGrantsForRole(ctx context.Context, roleID uuid.UUID) error
	DeleteSSHAssetLoginsForAsset(ctx context.Context, assetID uuid.UUID) error
	DeleteStaleWorkerPresence(ctx context.Context, lastSeenAt pgtype.Timestamptz) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// approvals.EffectiveRule.
	EffectiveRequestPolicy(ctx context.Context, arg EffectiveRequestPolicyParams) (EffectiveRequestPolicyRow, error)
	EnqueueAuditEvent(ctx context.Context, arg EnqueueAuditEventParams) (uuid.UUID, error)
	ExpireGrants(ctx context.Context) ([]AccessGrant, error)
	// ExplainRole.
	ExplainRolePaths(ctx context.Context, arg ExplainRolePathsParams) ([]ExplainRolePathsRow, error)
	// Every ancestor-or-self folder id of $1 (the target), walking parent links up
	// to the root. Used for folder-scoped role containment checks.
	FolderAncestorsAndSelf(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// folderAncestorsAndSelf: every ancestor-or-self folder id of `id`, via the ltree
	// ancestor operator (@>).
	FolderAncestorsByPath(ctx context.Context, id pgtype.UUID) ([]uuid.UUID, error)
	// One folder by (parent, name). parent_id NULL matches a top-level folder
	// (IS NOT DISTINCT FROM treats NULL = NULL as a match).
	FolderByParentName(ctx context.Context, arg FolderByParentNameParams) (Folder, error)
	// FolderPathVisible global short-circuit: whether a folder id exists.
	FolderExists(ctx context.Context, folderID uuid.UUID) (bool, error)
	// Dotted leaf->root path of a single folder (the folder's own name first).
	FolderPath(ctx context.Context, id uuid.UUID) (string, error)
	// folderPathIDs: the ltree path text of one folder. pgx.ErrNoRows for a missing folder.
	FolderPathIDs(ctx context.Context, id uuid.UUID) (string, error)
	// FolderPathVisible: whether `folder_id` is an ancestor-or-self of an anchor (path reveal)
	// OR inside a folder the user manages (cascade down) — the same predicate as
	// VisibleFoldersUnder, for one folder.
	FolderPathVisible(ctx context.Context, arg FolderPathVisibleParams) (pgtype.Bool, error)
	// Every folder's full leaf->root dotted path in one query (for list responses).
	FolderPaths(ctx context.Context) ([]FolderPathsRow, error)
	// All folder ids in the subtree rooted at $1 (including $1 itself).
	FolderSubtreeIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// folderSubtreeIDs: every folder id in the subtrees rooted at `roots` (inclusive),
	// via the GiST-indexed ltree descendant operator (<@).
	FolderSubtreeIDsByRoots(ctx context.Context, roots []uuid.UUID) ([]uuid.UUID, error)
	GetAccessRequestForUpdate(ctx context.Context, id uuid.UUID) (AccessRequest, error)
	GetActiveCA(ctx context.Context, kind string) (CaKey, error)
	GetActiveSessionSigningKey(ctx context.Context) (SessionSigningKey, error)
	GetAsset(ctx context.Context, id uuid.UUID) (Asset, error)
	// Scoped to the owning asset: a config referencing another asset's secret (admin
	// misconfiguration) fails closed rather than leaking a secret cross-asset.
	GetAssetSecret(ctx context.Context, arg GetAssetSecretParams) (AssetSecret, error)
	// Loads a secret by id alone (for management scope-derivation → owning asset).
	GetAssetSecretByID(ctx context.Context, id uuid.UUID) (AssetSecret, error)
	GetAuthTokenByHash(ctx context.Context, tokenHash []byte) (AuthToken, error)
	GetFolder(ctx context.Context, id uuid.UUID) (Folder, error)
	GetGrant(ctx context.Context, id uuid.UUID) (AccessGrant, error)
	GetGrantByRequest(ctx context.Context, requestID uuid.UUID) (AccessGrant, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupByFolderAndName(ctx context.Context, arg GetGroupByFolderAndNameParams) (Group, error)
	GetGroupByNameGlobal(ctx context.Context, name string) (Group, error)
	GetLastAuditEntry(ctx context.Context) (AuditLog, error)
	GetLiveSession(ctx context.Context, id uuid.UUID) (LiveSession, error)
	GetLiveSessionParties(ctx context.Context, id uuid.UUID) (GetLiveSessionPartiesRow, error)
	GetPolicyByNameAndAsset(ctx context.Context, arg GetPolicyByNameAndAssetParams) (RequestPolicy, error)
	GetPolicySubject(ctx context.Context, id uuid.UUID) (RequestPolicySubject, error)
	GetPostgresAssetConfig(ctx context.Context, assetID uuid.UUID) (PostgresAssetConfig, error)
	GetRequestPolicy(ctx context.Context, id uuid.UUID) (RequestPolicy, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleBinding(ctx context.Context, id uuid.UUID) (RoleBinding, error)
	GetRoleByFolderAndName(ctx context.Context, arg GetRoleByFolderAndNameParams) (Role, error)
	GetRoleByNameGlobal(ctx context.Context, name string) (Role, error)
	GetRoleDefaultPolicy(ctx context.Context, roleID uuid.UUID) (RequestPolicy, error)
	GetRoleGrant(ctx context.Context, id uuid.UUID) (RoleGrant, error)
	GetSSHAssetConfig(ctx context.Context, assetID uuid.UUID) (SshAssetConfig, error)
	GetSSHAssetLogin(ctx context.Context, arg GetSSHAssetLoginParams) (SshAssetLogin, error)
	GetSessionRecording(ctx context.Context, sessionID uuid.UUID) (SessionRecording, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// globalHeldCapabilities.
	GlobalHeldCapabilities(ctx context.Context, user uuid.UUID) ([]GlobalHeldCapabilitiesRow, error)
	// AddGroupToGroup cycle check: whether making member_group_id a member of group_id
	// would close a cycle — true iff group_id is ALREADY a transitive supergroup of
	// member_group_id (walking member->super edges up from group_id).
	GroupNestingCyclic(ctx context.Context, arg GroupNestingCyclicParams) (bool, error)
	// VisibleAssets active tier.
	HeldAssets(ctx context.Context, user uuid.UUID) ([]HeldAssetsRow, error)
	// capsOnFolders.
	HeldCapabilitiesOnFolders(ctx context.Context, arg HeldCapabilitiesOnFoldersParams) ([]HeldCapabilitiesOnFoldersRow, error)
	// CapabilitiesOnObject.
	HeldCapabilitiesOnObject(ctx context.Context, arg HeldCapabilitiesOnObjectParams) ([]HeldCapabilitiesOnObjectRow, error)
	// Check.
	HeldCheckAssetCapability(ctx context.Context, arg HeldCheckAssetCapabilityParams) (bool, error)
	// mgmtScopeFolders.
	HeldFolderCapabilities(ctx context.Context, user uuid.UUID) ([]HeldFolderCapabilitiesRow, error)
	// heldRoleIDs.
	HeldRoleIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error)
	// heldRolesAndAssets.
	HeldRolesAndAssets(ctx context.Context, user uuid.UUID) ([]HeldRolesAndAssetsRow, error)
	// RolesOnAsset active.
	HeldRolesOnAsset(ctx context.Context, arg HeldRolesOnAssetParams) ([]pgtype.UUID, error)
	// RoleResolver.HoldsRole (binding ∪ grant satisfaction over authz_role_goals).
	HoldsRole(ctx context.Context, arg HoldsRoleParams) (bool, error)
	// RoleResolver.HoldsRoleStanding (binding satisfaction only).
	HoldsRoleStanding(ctx context.Context, arg HoldsRoleStandingParams) (bool, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	InsertLiveSession(ctx context.Context, arg InsertLiveSessionParams) (LiveSession, error)
	InsertRoleCapability(ctx context.Context, arg InsertRoleCapabilityParams) error
	// visible_tree IsMember.
	IsMember(ctx context.Context, arg IsMemberParams) (pgtype.Bool, error)
	IsUserActive(ctx context.Context, id uuid.UUID) (bool, error)
	ListAccessRequestsByRequester(ctx context.Context, requesterUserID uuid.UUID) ([]AccessRequest, error)
	// Keyset pagination for (created_at DESC, id ASC). A row-comparison
	// `(created_at,id) < (…)` is WRONG for DESC+ASC — use the explicit predicate.
	ListAccessRequestsByRequesterPaged(ctx context.Context, arg ListAccessRequestsByRequesterPagedParams) ([]AccessRequest, error)
	ListAssetSecrets(ctx context.Context, arg ListAssetSecretsParams) ([]ListAssetSecretsRow, error)
	ListAssetsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Asset, error)
	ListAssetsByIDsPaged(ctx context.Context, arg ListAssetsByIDsPagedParams) ([]Asset, error)
	ListAuditEntries(ctx context.Context) ([]AuditLog, error)
	ListDistinctAssetsByUserAndWorkers(ctx context.Context, arg ListDistinctAssetsByUserAndWorkersParams) ([]uuid.UUID, error)
	ListDistinctUserAssetsByWorkers(ctx context.Context, dollar_1 []string) ([]ListDistinctUserAssetsByWorkersRow, error)
	ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error)
	ListFoldersByIDsPaged(ctx context.Context, arg ListFoldersByIDsPagedParams) ([]Folder, error)
	ListGrantsBySubject(ctx context.Context, subjectUserID uuid.UUID) ([]AccessGrant, error)
	// Keyset pagination on (granted_at DESC, id ASC) for caller-scoped grants.
	ListGrantsBySubjectPaged(ctx context.Context, arg ListGrantsBySubjectPagedParams) ([]AccessGrant, error)
	// Admin listing: all grants (active + past), optionally narrowed to a subject
	// and/or to active-only. sqlc.narg(subject_user_id) NULL => any subject;
	// active_only=false => include revoked/expired.
	ListGrantsFiltered(ctx context.Context, arg ListGrantsFilteredParams) ([]AccessGrant, error)
	// Admin listing with keyset pagination on (granted_at DESC, id ASC). Filters
	// are all optional (null subject => any subject; active_only=false => all).
	ListGrantsFilteredPaged(ctx context.Context, arg ListGrantsFilteredPagedParams) ([]AccessGrant, error)
	// Single keyset scan over group_memberships ordered by (created_at DESC, id).
	// Each row is either a user-member (member_user_id non-null) or group-member
	// (member_group_id non-null); the handler splits them.
	ListGroupMembersPaged(ctx context.Context, arg ListGroupMembersPagedParams) ([]GroupMembership, error)
	ListGroupsByIDsPaged(ctx context.Context, arg ListGroupsByIDsPagedParams) ([]Group, error)
	ListGroupsPaged(ctx context.Context, arg ListGroupsPagedParams) ([]Group, error)
	ListLiveSessionsByAsset(ctx context.Context, assetID uuid.UUID) ([]LiveSession, error)
	ListLiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	ListLiveSessionsByUserAsset(ctx context.Context, arg ListLiveSessionsByUserAssetParams) ([]LiveSession, error)
	ListLiveSessionsByWorker(ctx context.Context, workerID string) ([]LiveSession, error)
	ListPendingRequests(ctx context.Context) ([]AccessRequest, error)
	ListPendingRequestsByAsset(ctx context.Context, assetID uuid.UUID) ([]ListPendingRequestsByAssetRow, error)
	ListPendingRequestsByRole(ctx context.Context, roleID uuid.UUID) ([]ListPendingRequestsByRoleRow, error)
	// Keyset pagination for pending requests (created_at DESC, id ASC).
	ListPendingRequestsPaged(ctx context.Context, arg ListPendingRequestsPagedParams) ([]AccessRequest, error)
	ListPoliciesForAsset(ctx context.Context, arg ListPoliciesForAssetParams) ([]RequestPolicy, error)
	ListPoliciesForSubjectGroup(ctx context.Context, arg ListPoliciesForSubjectGroupParams) ([]RequestPolicy, error)
	// Every policy that references the role in any position, tagged with how: as the
	// requestable role, as the requester-source role, or as the approver-source role.
	// Bounded (a role appears in few policies); not paginated.
	ListPoliciesUsingRole(ctx context.Context, roleID uuid.UUID) ([]ListPoliciesUsingRoleRow, error)
	// Explicit requester/approver subjects of a policy, fully resolved for display
	// (name, kind, group home path, member count, active) in one query.
	ListPolicyRosterSubjects(ctx context.Context, arg ListPolicyRosterSubjectsParams) ([]ListPolicyRosterSubjectsRow, error)
	// Subjects attached to a policy, fully resolved for display in SQL: subject name,
	// group-home path (via folder_path()), and member count. No per-row Go resolution.
	ListPolicySubjects(ctx context.Context, arg ListPolicySubjectsParams) ([]ListPolicySubjectsRow, error)
	ListPostgresAssetLogins(ctx context.Context, assetID uuid.UUID) ([]PostgresAssetLogin, error)
	ListRequestPolicies(ctx context.Context, arg ListRequestPoliciesParams) ([]RequestPolicy, error)
	ListRequestPoliciesByAsset(ctx context.Context, scopeAssetID pgtype.UUID) ([]RequestPolicy, error)
	// Bindings matching the (all-optional) filters, fully resolved for display in SQL:
	// subject kind/name/group-home path/member count, role name, and the binding's scope
	// rendered as a dotted path (or 'global'). Single-sources folder-path rendering via
	// folder_path(); no per-row Go resolution.
	ListRoleBindings(ctx context.Context, arg ListRoleBindingsParams) ([]ListRoleBindingsRow, error)
	ListRoleBindingsByAsset(ctx context.Context, scopeAssetID pgtype.UUID) ([]RoleBinding, error)
	ListRoleGrants(ctx context.Context, arg ListRoleGrantsParams) ([]RoleGrant, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListRolesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Role, error)
	ListRolesByIDsPaged(ctx context.Context, arg ListRolesByIDsPagedParams) ([]Role, error)
	ListSSHAssetLogins(ctx context.Context, assetID uuid.UUID) ([]SshAssetLogin, error)
	ListSessionRecordings(ctx context.Context, arg ListSessionRecordingsParams) ([]SessionRecording, error)
	ListStaleWorkerSessions(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]uuid.UUID, error)
	ListStuckTerminatingSessions(ctx context.Context, terminateRequestedAt pgtype.Timestamptz) ([]uuid.UUID, error)
	ListUndrainedOutbox(ctx context.Context, limit int64) ([]ListUndrainedOutboxRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockLastAuditEntry(ctx context.Context) ([]byte, error)
	MarkLiveSessionTerminating(ctx context.Context, id uuid.UUID) (int64, error)
	// memberGroupIDs.
	MemberGroupIDs(ctx context.Context, user uuid.UUID) ([]pgtype.UUID, error)
	NormalizeJSON(ctx context.Context, dollar_1 []byte) ([]byte, error)
	NotifyAuthzChanged(ctx context.Context) error
	// NotifyTeardown: publish a payload on a NOTIFY channel via pg_notify.
	NotifyChannel(ctx context.Context, arg NotifyChannelParams) error
	// Clears the approver gate on surviving policies that named the role as their
	// approver role (the policy survives, just loses that gate). Part of DeleteRole.
	NullApproverRoleForRole(ctx context.Context, approverRoleID pgtype.UUID) error
	// Clears the requester gate on surviving policies that named the role as their
	// requester role (the policy survives, just loses that gate). Part of DeleteRole.
	NullRequesterRoleForRole(ctx context.Context, requesterRoleID pgtype.UUID) error
	PoliciesScopedToFoldersOrAssets(ctx context.Context, arg PoliciesScopedToFoldersOrAssetsParams) ([]RequestPolicy, error)
	ReactivateUser(ctx context.Context, id uuid.UUID) error
	RemoveGroupFromGroup(ctx context.Context, arg RemoveGroupFromGroupParams) error
	RemovePolicySubject(ctx context.Context, id uuid.UUID) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	// [2] requestableRoles: roles requestable (but not already active) for the user on
	// the asset under the request_policy eligibility model. The effective policy per
	// candidate role is authz_effective_request_policy(role, asset); the held /
	// held_standing closures come from the shared authz_held / authz_held_standing
	// functions. A role is requestable iff its effective policy makes the user eligible
	// (requester_role held STANDING on the asset OR an explicit kind='requester'
	// subject) AND the user does not already hold it Active on the asset (grants count).
	RequestableRolesOnAsset(ctx context.Context, arg RequestableRolesOnAssetParams) ([]uuid.UUID, error)
	// [26] approvals.IsEligibleRequester explicit-subject arm. Mirrors
	// ApproverSubjectExists, differing only by the kind='requester' literal.
	RequesterSubjectExists(ctx context.Context, arg RequesterSubjectExistsParams) (bool, error)
	// [23] accessrequest.reviewableGrants: the grants the caller may review, resolved
	// set-based (reproducing CanReviewGrant over the whole candidate set). A grant is
	// reviewable when the caller is its subject OR (the caller is active AND, for the
	// grant's (role, asset) EFFECTIVE policy — authz_effective_request_policy — an
	// explicit kind='approver' subject, direct or via a nested group, OR the approver_role
	// held STANDING on the asset). The subject arm intentionally has no active-user check,
	// matching CanReviewGrant. @restrict limits the candidate set to those grant ids (a
	// keyset page); a NULL array considers all grants. Ordered granted_at DESC, id.
	ReviewableGrants(ctx context.Context, arg ReviewableGrantsParams) ([]ReviewableGrantsRow, error)
	// Revokes a role's still-live grants (not yet revoked, not yet expired) so the
	// terminator can tear down the sessions they authorized. Used by the DeleteRole
	// cascade before the role row (and, via FK cascade, these grant rows) is deleted.
	RevokeActiveGrantsForRole(ctx context.Context, arg RevokeActiveGrantsForRoleParams) ([]AccessGrant, error)
	RevokeActiveGrantsForUser(ctx context.Context, arg RevokeActiveGrantsForUserParams) ([]AccessGrant, error)
	// Predicate is revoked_at IS NULL only (NOT the derived "active" filter with
	// expires_at): a grant past expiry but not yet reaped is still revocable so the
	// deactivation cascade can stamp a reason/actor on it. Authz already excludes it
	// (expires_at > now() is false everywhere), so this is harmless.
	RevokeGrant(ctx context.Context, arg RevokeGrantParams) (AccessGrant, error)
	RoleCapabilityRows(ctx context.Context, roleID uuid.UUID) ([]RoleCapabilityRowsRow, error)
	// Subjects whose standing binding confers p_role on the given object (asset|folder),
	// mirroring the base arm of authz_held over the backward goal-expansion. Subjects are
	// returned as NODES (not expanded to members), fully resolved for display, tagged with
	// the actually-bound role (via_role_name). Deactivated user-subjects excluded.
	RoleStandingHolders(ctx context.Context, arg RoleStandingHoldersParams) ([]RoleStandingHoldersRow, error)
	// CapabilitiesOnScope asset arm (global_held ∪ held on the asset or its ancestor-or-self folders).
	ScopeCapabilitiesAsset(ctx context.Context, arg ScopeCapabilitiesAssetParams) ([]ScopeCapabilitiesAssetRow, error)
	// CapabilitiesOnScope folder arm (global_held ∪ held on folders in the scope subtree).
	ScopeCapabilitiesFolder(ctx context.Context, arg ScopeCapabilitiesFolderParams) ([]ScopeCapabilitiesFolderRow, error)
	SearchAssetsByIDs(ctx context.Context, arg SearchAssetsByIDsParams) ([]Asset, error)
	// Name-matching folders within a visible-id set. The `name ILIKE` predicate is
	// served by the pg_trgm GIN index (idx_folders_name_trgm), so search filters by
	// name in the database instead of materializing the whole visible catalog.
	SearchFoldersByIDs(ctx context.Context, arg SearchFoldersByIDsParams) ([]Folder, error)
	SearchGroupsByIDs(ctx context.Context, arg SearchGroupsByIDsParams) ([]Group, error)
	SearchRolesByIDs(ctx context.Context, arg SearchRolesByIDsParams) ([]Role, error)
	SetAccessRequestStatus(ctx context.Context, arg SetAccessRequestStatusParams) error
	SetAssetSecret(ctx context.Context, arg SetAssetSecretParams) (AssetSecret, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	UpdateAssetCatalogName(ctx context.Context, arg UpdateAssetCatalogNameParams) error
	UpdateAssetFolder(ctx context.Context, arg UpdateAssetFolderParams) error
	UpdateAssetName(ctx context.Context, arg UpdateAssetNameParams) error
	UpdateFolderCatalogName(ctx context.Context, arg UpdateFolderCatalogNameParams) error
	UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) error
	UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) error
	UpdateRequestPolicy(ctx context.Context, arg UpdateRequestPolicyParams) (RequestPolicy, error)
	UpsertPostgresAssetConfig(ctx context.Context, arg UpsertPostgresAssetConfigParams) (PostgresAssetConfig, error)
	UpsertPostgresAssetLogin(ctx context.Context, arg UpsertPostgresAssetLoginParams) (PostgresAssetLogin, error)
	UpsertSSHAssetConfig(ctx context.Context, arg UpsertSSHAssetConfigParams) (SshAssetConfig, error)
	UpsertSSHAssetLogin(ctx context.Context, arg UpsertSSHAssetLoginParams) (SshAssetLogin, error)
	UpsertSessionRecording(ctx context.Context, arg UpsertSessionRecordingParams) error
	UpsertWorkerPresence(ctx context.Context, workerID string) error
	// [13] VisibleAssetsUnder: asset ids under `parent` the user may see, unifying the
	// ACCESS (access_ids), MANAGEMENT (catalog:asset:read OR the subtree-wide
	// catalog:folder:read, cascade over authz_held / authz_global_held), and CONNECT
	// (ssh:login entitled over the full asset-scope cascade) axes. The (parent, cascade)
	// browse level is selected by the nullable @parent and @cascade args (the (NULL
	// parent, non-cascade) case is short-circuited by the caller and never reaches this
	// query). The catalog:folder:read literal arm is the READ-ONLY subtree broadening
	// (see authz.FolderReadCap) — it confers READ, never CONNECT or grantable authority.
	VisibleAssetsUnder(ctx context.Context, arg VisibleAssetsUnderParams) ([]uuid.UUID, error)
	// VisibleFoldersUnder: folders under `parent` visible to the user under the path-reveal
	// model, each with a `governed` flag. `anchors` are the folders whose browse PATH must be
	// revealed (ancestor-or-self); `mgmt_ids` are the folders the user manages (their subtrees
	// are visible AND governed). The (parent, cascade) browse level is selected by the nullable
	// @parent and @cascade args, mirroring childCandidateFolderIDs.
	VisibleFoldersUnder(ctx context.Context, arg VisibleFoldersUnderParams) ([]VisibleFoldersUnderRow, error)
	// [18] visibleHomedSetBased(groups): groups homed under `parent` visible to the user,
	// each with its home folder. ACCESS (access_ids = transitive membership) ∪ MANAGEMENT
	// (identity:group:read OR the subtree-wide catalog:folder:read cascade). Table variant
	// of VisibleRolesHomed (FROM groups). The catalog:folder:read literal arm is the
	// READ-ONLY subtree broadening (see authz.FolderReadCap).
	VisibleGroupsHomed(ctx context.Context, arg VisibleGroupsHomedParams) ([]VisibleGroupsHomedRow, error)
	// [3] visibleRequestable: every (asset, role) requestable (and not already active)
	// for the user across ALL assets. The candidate (asset, role) universe is the union
	// of asset-scoped, ancestor-folder-scoped, and scopeless request_policies; per pair
	// the winning policy is authz_effective_request_policy(role, asset) via LATERAL. The
	// eligibility and active-exclusion arms mirror RequestableRolesOnAsset, keyed on the
	// (asset, role) pair.
	VisibleRequestable(ctx context.Context, user pgtype.UUID) ([]VisibleRequestableRow, error)
	// [18] visibleHomedSetBased(roles): roles homed under `parent` visible to the user,
	// each with its home folder. ACCESS (access_ids) ∪ MANAGEMENT (access:role:read OR
	// the subtree-wide catalog:folder:read, cascade over authz_held / authz_global_held).
	// Level selected by @parent/@cascade. The catalog:folder:read literal arm is the
	// READ-ONLY subtree broadening (see authz.FolderReadCap).
	VisibleRolesHomed(ctx context.Context, arg VisibleRolesHomedParams) ([]VisibleRolesHomedRow, error)
}

var _ Querier = (*Queries)(nil)
