// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionSigningKey = `-- name: CreateSessionSigningKey :one
INSERT INTO session_signing_keys (sealed, public_key) VALUES ($1, $2) RETURNING id, sealed, public_key, created_at, active
`

type CreateSessionSigningKeyParams struct {
	Sealed    []byte `json:"sealed"`
	PublicKey []byte `json:"public_key"`
}

func (q *Queries) CreateSessionSigningKey(ctx context.Context, arg CreateSessionSigningKeyParams) (SessionSigningKey, error) {
	row := q.db.QueryRow(ctx, createSessionSigningKey, arg.Sealed, arg.PublicKey)
	var i SessionSigningKey
	err := row.Scan(
		&i.ID,
		&i.Sealed,
		&i.PublicKey,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const deleteLiveSession = `-- name: DeleteLiveSession :execrows
DELETE FROM live_sessions WHERE id = $1
`

func (q *Queries) DeleteLiveSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLiveSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleWorkerPresence = `-- name: DeleteStaleWorkerPresence :exec
DELETE FROM worker_presence wp
WHERE wp.last_seen_at < $1
  AND NOT EXISTS (SELECT 1 FROM live_sessions ls WHERE ls.worker_id = wp.worker_id)
`

func (q *Queries) DeleteStaleWorkerPresence(ctx context.Context, lastSeenAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteStaleWorkerPresence, lastSeenAt)
	return err
}

const getActiveSessionSigningKey = `-- name: GetActiveSessionSigningKey :one
SELECT id, sealed, public_key, created_at, active FROM session_signing_keys WHERE active
`

func (q *Queries) GetActiveSessionSigningKey(ctx context.Context) (SessionSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSessionSigningKey)
	var i SessionSigningKey
	err := row.Scan(
		&i.ID,
		&i.Sealed,
		&i.PublicKey,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp, started_at, terminate_requested_at FROM live_sessions WHERE id = $1
`

func (q *Queries) GetLiveSession(ctx context.Context, id uuid.UUID) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSession, id)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssetID,
		&i.WorkerID,
		&i.GrantID,
		&i.Protocol,
		&i.Principals,
		&i.ClientKeyFp,
		&i.StartedAt,
		&i.TerminateRequestedAt,
	)
	return i, err
}

const getLiveSessionParties = `-- name: GetLiveSessionParties :one
SELECT user_id, asset_id, worker_id, protocol FROM live_sessions WHERE id = $1
`

type GetLiveSessionPartiesRow struct {
	UserID   uuid.UUID `json:"user_id"`
	AssetID  uuid.UUID `json:"asset_id"`
	WorkerID string    `json:"worker_id"`
	Protocol string    `json:"protocol"`
}

func (q *Queries) GetLiveSessionParties(ctx context.Context, id uuid.UUID) (GetLiveSessionPartiesRow, error) {
	row := q.db.QueryRow(ctx, getLiveSessionParties, id)
	var i GetLiveSessionPartiesRow
	err := row.Scan(
		&i.UserID,
		&i.AssetID,
		&i.WorkerID,
		&i.Protocol,
	)
	return i, err
}

const insertLiveSession = `-- name: InsertLiveSession :one
INSERT INTO live_sessions (id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp, started_at, terminate_requested_at
`

type InsertLiveSessionParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	AssetID     uuid.UUID   `json:"asset_id"`
	WorkerID    string      `json:"worker_id"`
	GrantID     pgtype.UUID `json:"grant_id"`
	Protocol    string      `json:"protocol"`
	Principals  []string    `json:"principals"`
	ClientKeyFp string      `json:"client_key_fp"`
}

func (q *Queries) InsertLiveSession(ctx context.Context, arg InsertLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, insertLiveSession,
		arg.ID,
		arg.UserID,
		arg.AssetID,
		arg.WorkerID,
		arg.GrantID,
		arg.Protocol,
		arg.Principals,
		arg.ClientKeyFp,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssetID,
		&i.WorkerID,
		&i.GrantID,
		&i.Protocol,
		&i.Principals,
		&i.ClientKeyFp,
		&i.StartedAt,
		&i.TerminateRequestedAt,
	)
	return i, err
}

const listDistinctAssetsByUserAndWorkers = `-- name: ListDistinctAssetsByUserAndWorkers :many
SELECT DISTINCT asset_id FROM live_sessions
WHERE user_id = $1 AND worker_id = ANY($2::text[])
`

type ListDistinctAssetsByUserAndWorkersParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 []string  `json:"column_2"`
}

func (q *Queries) ListDistinctAssetsByUserAndWorkers(ctx context.Context, arg ListDistinctAssetsByUserAndWorkersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDistinctAssetsByUserAndWorkers, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var asset_id uuid.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctUserAssetsByWorkers = `-- name: ListDistinctUserAssetsByWorkers :many
SELECT DISTINCT user_id, asset_id FROM live_sessions WHERE worker_id = ANY($1::text[])
`

type ListDistinctUserAssetsByWorkersRow struct {
	UserID  uuid.UUID `json:"user_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

func (q *Queries) ListDistinctUserAssetsByWorkers(ctx context.Context, dollar_1 []string) ([]ListDistinctUserAssetsByWorkersRow, error) {
	rows, err := q.db.Query(ctx, listDistinctUserAssetsByWorkers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctUserAssetsByWorkersRow
	for rows.Next() {
		var i ListDistinctUserAssetsByWorkersRow
		if err := rows.Scan(&i.UserID, &i.AssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByAsset = `-- name: ListLiveSessionsByAsset :many
SELECT id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp, started_at, terminate_requested_at FROM live_sessions WHERE asset_id = $1
`

func (q *Queries) ListLiveSessionsByAsset(ctx context.Context, assetID uuid.UUID) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSession
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetID,
			&i.WorkerID,
			&i.GrantID,
			&i.Protocol,
			&i.Principals,
			&i.ClientKeyFp,
			&i.StartedAt,
			&i.TerminateRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByUser = `-- name: ListLiveSessionsByUser :many
SELECT id FROM live_sessions WHERE user_id = $1
`

func (q *Queries) ListLiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByUserAsset = `-- name: ListLiveSessionsByUserAsset :many
SELECT id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp, started_at, terminate_requested_at FROM live_sessions WHERE user_id = $1 AND asset_id = $2
`

type ListLiveSessionsByUserAssetParams struct {
	UserID  uuid.UUID `json:"user_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

func (q *Queries) ListLiveSessionsByUserAsset(ctx context.Context, arg ListLiveSessionsByUserAssetParams) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByUserAsset, arg.UserID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSession
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetID,
			&i.WorkerID,
			&i.GrantID,
			&i.Protocol,
			&i.Principals,
			&i.ClientKeyFp,
			&i.StartedAt,
			&i.TerminateRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByWorker = `-- name: ListLiveSessionsByWorker :many
SELECT id, user_id, asset_id, worker_id, grant_id, protocol, principals, client_key_fp, started_at, terminate_requested_at FROM live_sessions WHERE worker_id = $1
`

func (q *Queries) ListLiveSessionsByWorker(ctx context.Context, workerID string) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSession
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetID,
			&i.WorkerID,
			&i.GrantID,
			&i.Protocol,
			&i.Principals,
			&i.ClientKeyFp,
			&i.StartedAt,
			&i.TerminateRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleWorkerSessions = `-- name: ListStaleWorkerSessions :many
SELECT ls.id FROM live_sessions ls
JOIN worker_presence wp ON wp.worker_id = ls.worker_id
WHERE wp.last_seen_at < $1
`

func (q *Queries) ListStaleWorkerSessions(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleWorkerSessions, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckTerminatingSessions = `-- name: ListStuckTerminatingSessions :many
SELECT id FROM live_sessions
WHERE terminate_requested_at IS NOT NULL AND terminate_requested_at < $1
`

func (q *Queries) ListStuckTerminatingSessions(ctx context.Context, terminateRequestedAt pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStuckTerminatingSessions, terminateRequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLiveSessionTerminating = `-- name: MarkLiveSessionTerminating :execrows
UPDATE live_sessions SET terminate_requested_at = now() WHERE id = $1 AND terminate_requested_at IS NULL
`

func (q *Queries) MarkLiveSessionTerminating(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markLiveSessionTerminating, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyChannel = `-- name: NotifyChannel :exec
SELECT pg_notify($1, $2)
`

type NotifyChannelParams struct {
	Channel string `json:"channel"`
	Payload string `json:"payload"`
}

// NotifyTeardown: publish a payload on a NOTIFY channel via pg_notify.
func (q *Queries) NotifyChannel(ctx context.Context, arg NotifyChannelParams) error {
	_, err := q.db.Exec(ctx, notifyChannel, arg.Channel, arg.Payload)
	return err
}

const upsertWorkerPresence = `-- name: UpsertWorkerPresence :exec
INSERT INTO worker_presence (worker_id, last_seen_at) VALUES ($1, now())
ON CONFLICT (worker_id) DO UPDATE SET last_seen_at = now()
`

func (q *Queries) UpsertWorkerPresence(ctx context.Context, workerID string) error {
	_, err := q.db.Exec(ctx, upsertWorkerPresence, workerID)
	return err
}
