// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target_identity.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTrustAnchor = `-- name: ApproveTrustAnchor :one
INSERT INTO target_trust_anchors (
    asset_id,
    endpoint_revision,
    kind,
    algorithm,
    sha256_fingerprint,
    public_material,
    required_ssh_principals,
    required_dns_names,
    required_ip_addresses,
    source,
    observation_id,
    approved_by,
    approved_at,
    not_before,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::uuid,
    $12::uuid,
    $13,
    $14::timestamptz,
    $15::timestamptz
)
RETURNING id, asset_id, endpoint_revision, kind, algorithm, sha256_fingerprint, public_material, required_ssh_principals, required_dns_names, required_ip_addresses, source, observation_id, approved_by, approved_at, not_before, expires_at, revoked_at, revoked_by, revocation_reason
`

type ApproveTrustAnchorParams struct {
	AssetID               uuid.UUID          `json:"asset_id"`
	EndpointRevision      int64              `json:"endpoint_revision"`
	Kind                  string             `json:"kind"`
	Algorithm             string             `json:"algorithm"`
	Sha256Fingerprint     string             `json:"sha256_fingerprint"`
	PublicMaterial        string             `json:"public_material"`
	RequiredSshPrincipals []string           `json:"required_ssh_principals"`
	RequiredDnsNames      []string           `json:"required_dns_names"`
	RequiredIpAddresses   []string           `json:"required_ip_addresses"`
	Source                string             `json:"source"`
	ObservationID         pgtype.UUID        `json:"observation_id"`
	ApprovedBy            pgtype.UUID        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	NotBefore             pgtype.Timestamptz `json:"not_before"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ApproveTrustAnchor(ctx context.Context, arg ApproveTrustAnchorParams) (TargetTrustAnchor, error) {
	row := q.db.QueryRow(ctx, approveTrustAnchor,
		arg.AssetID,
		arg.EndpointRevision,
		arg.Kind,
		arg.Algorithm,
		arg.Sha256Fingerprint,
		arg.PublicMaterial,
		arg.RequiredSshPrincipals,
		arg.RequiredDnsNames,
		arg.RequiredIpAddresses,
		arg.Source,
		arg.ObservationID,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.NotBefore,
		arg.ExpiresAt,
	)
	var i TargetTrustAnchor
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.Kind,
		&i.Algorithm,
		&i.Sha256Fingerprint,
		&i.PublicMaterial,
		&i.RequiredSshPrincipals,
		&i.RequiredDnsNames,
		&i.RequiredIpAddresses,
		&i.Source,
		&i.ObservationID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevocationReason,
	)
	return i, err
}

const claimProbeJob = `-- name: ClaimProbeJob :one
WITH candidate AS MATERIALIZED (
    SELECT j.id
    FROM target_probe_jobs j
    JOIN assets a
      ON a.id = j.asset_id
     AND a.endpoint_revision = j.endpoint_revision
     AND a.kind = j.protocol
    WHERE j.state = 'queued'
      AND j.next_attempt_at <= now()
      AND j.attempt_count < j.max_attempts
    ORDER BY j.next_attempt_at, j.created_at, j.id
    FOR UPDATE OF j SKIP LOCKED
    LIMIT 1
), leased AS (
    UPDATE target_probe_jobs j
    SET state = 'leased',
        attempt_count = j.attempt_count + 1,
        lease_worker_id = $1,
        lease_token_hash = $2,
        lease_expires_at = $3,
        started_at = COALESCE(j.started_at, now()),
        completed_at = NULL,
        failure_category = NULL,
        failure_detail = NULL
    FROM candidate c
    WHERE j.id = c.id
    RETURNING j.id, j.previous_job_id, j.asset_id, j.endpoint_revision, j.protocol, j.state, j.reason, j.requested_by, j.attempt_count, j.max_attempts, j.next_attempt_at, j.lease_worker_id, j.lease_token_hash, j.lease_expires_at, j.failure_category, j.failure_detail, j.created_at, j.started_at, j.completed_at
), attempt AS (
    INSERT INTO target_probe_attempts (
        job_id,
        attempt_number,
        worker_id,
        lease_token_hash,
        lease_expires_at
    )
    SELECT
        l.id,
        l.attempt_count,
        l.lease_worker_id,
        l.lease_token_hash,
        l.lease_expires_at
    FROM leased l
    RETURNING id, job_id
)
SELECT
    l.id AS job_id,
    attempt.id AS attempt_id,
    l.asset_id,
    l.endpoint_revision,
    l.protocol,
    l.reason,
    l.attempt_count,
    l.max_attempts,
    l.lease_expires_at,
    CASE l.protocol
        WHEN 'ssh' THEN ssh.target_address
        WHEN 'postgres' THEN postgres.target_address
        WHEN 'rdp' THEN rdp.target_address
        ELSE ''
    END::text AS target_address
FROM leased l
JOIN attempt ON attempt.job_id = l.id
LEFT JOIN ssh_asset_config ssh ON ssh.asset_id = l.asset_id AND l.protocol = 'ssh'
LEFT JOIN postgres_asset_config postgres ON postgres.asset_id = l.asset_id AND l.protocol = 'postgres'
LEFT JOIN rdp_asset_config rdp ON rdp.asset_id = l.asset_id AND l.protocol = 'rdp'
`

type ClaimProbeJobParams struct {
	WorkerID       pgtype.Text        `json:"worker_id"`
	LeaseTokenHash []byte             `json:"lease_token_hash"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

type ClaimProbeJobRow struct {
	JobID            uuid.UUID          `json:"job_id"`
	AttemptID        uuid.UUID          `json:"attempt_id"`
	AssetID          uuid.UUID          `json:"asset_id"`
	EndpointRevision int64              `json:"endpoint_revision"`
	Protocol         string             `json:"protocol"`
	Reason           string             `json:"reason"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	TargetAddress    string             `json:"target_address"`
}

func (q *Queries) ClaimProbeJob(ctx context.Context, arg ClaimProbeJobParams) (ClaimProbeJobRow, error) {
	row := q.db.QueryRow(ctx, claimProbeJob, arg.WorkerID, arg.LeaseTokenHash, arg.LeaseExpiresAt)
	var i ClaimProbeJobRow
	err := row.Scan(
		&i.JobID,
		&i.AttemptID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.Protocol,
		&i.Reason,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.TargetAddress,
	)
	return i, err
}

const claimProbeJobForProtocol = `-- name: ClaimProbeJobForProtocol :one
WITH candidate AS MATERIALIZED (
    SELECT job.id
    FROM target_probe_jobs job
    JOIN assets asset
      ON asset.id = job.asset_id
     AND asset.endpoint_revision = job.endpoint_revision
     AND asset.kind = job.protocol
    WHERE job.state = 'queued'
      AND job.protocol = $1
      AND job.next_attempt_at <= now()
      AND job.attempt_count < job.max_attempts
    ORDER BY job.next_attempt_at, job.created_at, job.id
    FOR UPDATE OF job SKIP LOCKED
    LIMIT 1
), leased AS (
    UPDATE target_probe_jobs job
    SET state = 'leased',
        attempt_count = job.attempt_count + 1,
        lease_worker_id = $2,
        lease_token_hash = $3,
        lease_expires_at = $4,
        started_at = COALESCE(job.started_at, now()),
        completed_at = NULL,
        failure_category = NULL,
        failure_detail = NULL
    FROM candidate
    WHERE job.id = candidate.id
    RETURNING job.id, job.previous_job_id, job.asset_id, job.endpoint_revision, job.protocol, job.state, job.reason, job.requested_by, job.attempt_count, job.max_attempts, job.next_attempt_at, job.lease_worker_id, job.lease_token_hash, job.lease_expires_at, job.failure_category, job.failure_detail, job.created_at, job.started_at, job.completed_at
), attempt AS (
    INSERT INTO target_probe_attempts (job_id, attempt_number, worker_id, lease_token_hash, lease_expires_at)
    SELECT id, attempt_count, lease_worker_id, lease_token_hash, lease_expires_at
    FROM leased
    RETURNING id, job_id
)
SELECT leased.id AS job_id,
       attempt.id AS attempt_id,
       leased.asset_id,
       leased.endpoint_revision,
       leased.protocol,
       leased.reason,
       leased.attempt_count,
       leased.max_attempts,
       leased.lease_expires_at,
       CASE leased.protocol
           WHEN 'ssh' THEN ssh.target_address
           WHEN 'postgres' THEN postgres.target_address
           WHEN 'rdp' THEN rdp.target_address
           ELSE ''
       END::text AS target_address
FROM leased
JOIN attempt ON attempt.job_id = leased.id
LEFT JOIN ssh_asset_config ssh ON ssh.asset_id = leased.asset_id AND leased.protocol = 'ssh'
LEFT JOIN postgres_asset_config postgres ON postgres.asset_id = leased.asset_id AND leased.protocol = 'postgres'
LEFT JOIN rdp_asset_config rdp ON rdp.asset_id = leased.asset_id AND leased.protocol = 'rdp'
`

type ClaimProbeJobForProtocolParams struct {
	Protocol       string             `json:"protocol"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	LeaseTokenHash []byte             `json:"lease_token_hash"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

type ClaimProbeJobForProtocolRow struct {
	JobID            uuid.UUID          `json:"job_id"`
	AttemptID        uuid.UUID          `json:"attempt_id"`
	AssetID          uuid.UUID          `json:"asset_id"`
	EndpointRevision int64              `json:"endpoint_revision"`
	Protocol         string             `json:"protocol"`
	Reason           string             `json:"reason"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	TargetAddress    string             `json:"target_address"`
}

func (q *Queries) ClaimProbeJobForProtocol(ctx context.Context, arg ClaimProbeJobForProtocolParams) (ClaimProbeJobForProtocolRow, error) {
	row := q.db.QueryRow(ctx, claimProbeJobForProtocol,
		arg.Protocol,
		arg.WorkerID,
		arg.LeaseTokenHash,
		arg.LeaseExpiresAt,
	)
	var i ClaimProbeJobForProtocolRow
	err := row.Scan(
		&i.JobID,
		&i.AttemptID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.Protocol,
		&i.Reason,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.TargetAddress,
	)
	return i, err
}

const completeProbeAttempt = `-- name: CompleteProbeAttempt :one
WITH completed_job AS (
    UPDATE target_probe_jobs j
    SET state = CASE $1::text
                    WHEN 'succeeded' THEN 'succeeded'
                    ELSE 'failed'
                END,
        lease_worker_id = NULL,
        lease_token_hash = NULL,
        lease_expires_at = NULL,
        failure_category = $2::text,
        failure_detail = $3::text,
        completed_at = now()
    WHERE j.id = $4
      AND j.state = 'leased'
      AND j.lease_worker_id = $5
      AND j.lease_token_hash = $6
      AND j.lease_expires_at > now()
      AND $1::text IN ('succeeded','failed')
    RETURNING j.id, j.attempt_count
), completed_attempt AS (
    UPDATE target_probe_attempts a
    SET completed_at = now(),
        outcome = $1,
        failure_category = $2::text,
        failure_detail = $3::text
    FROM completed_job j
    WHERE a.job_id = j.id
      AND a.attempt_number = j.attempt_count
      AND a.worker_id = $5
      AND a.lease_token_hash = $6
      AND a.completed_at IS NULL
    RETURNING a.id, a.job_id, a.attempt_number, a.worker_id, a.lease_token_hash, a.lease_expires_at, a.started_at, a.completed_at, a.outcome, a.failure_category, a.failure_detail
)
SELECT id, job_id, attempt_number, worker_id, lease_token_hash, lease_expires_at, started_at, completed_at, outcome, failure_category, failure_detail FROM completed_attempt
`

type CompleteProbeAttemptParams struct {
	Outcome         string      `json:"outcome"`
	FailureCategory pgtype.Text `json:"failure_category"`
	FailureDetail   pgtype.Text `json:"failure_detail"`
	JobID           uuid.UUID   `json:"job_id"`
	WorkerID        pgtype.Text `json:"worker_id"`
	LeaseTokenHash  []byte      `json:"lease_token_hash"`
}

type CompleteProbeAttemptRow struct {
	ID              uuid.UUID          `json:"id"`
	JobID           uuid.UUID          `json:"job_id"`
	AttemptNumber   int32              `json:"attempt_number"`
	WorkerID        string             `json:"worker_id"`
	LeaseTokenHash  []byte             `json:"lease_token_hash"`
	LeaseExpiresAt  time.Time          `json:"lease_expires_at"`
	StartedAt       time.Time          `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Outcome         pgtype.Text        `json:"outcome"`
	FailureCategory pgtype.Text        `json:"failure_category"`
	FailureDetail   pgtype.Text        `json:"failure_detail"`
}

func (q *Queries) CompleteProbeAttempt(ctx context.Context, arg CompleteProbeAttemptParams) (CompleteProbeAttemptRow, error) {
	row := q.db.QueryRow(ctx, completeProbeAttempt,
		arg.Outcome,
		arg.FailureCategory,
		arg.FailureDetail,
		arg.JobID,
		arg.WorkerID,
		arg.LeaseTokenHash,
	)
	var i CompleteProbeAttemptRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Outcome,
		&i.FailureCategory,
		&i.FailureDetail,
	)
	return i, err
}

const createProbeJob = `-- name: CreateProbeJob :one
INSERT INTO target_probe_jobs (
    previous_job_id,
    asset_id,
    endpoint_revision,
    protocol,
    state,
    reason,
    requested_by,
    max_attempts,
    next_attempt_at
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    'queued',
    $5,
    $6::uuid,
    $7,
    $8
)
RETURNING id, previous_job_id, asset_id, endpoint_revision, protocol, state, reason, requested_by, attempt_count, max_attempts, next_attempt_at, lease_worker_id, lease_token_hash, lease_expires_at, failure_category, failure_detail, created_at, started_at, completed_at
`

type CreateProbeJobParams struct {
	PreviousJobID    pgtype.UUID        `json:"previous_job_id"`
	AssetID          uuid.UUID          `json:"asset_id"`
	EndpointRevision int64              `json:"endpoint_revision"`
	Protocol         string             `json:"protocol"`
	Reason           string             `json:"reason"`
	RequestedBy      pgtype.UUID        `json:"requested_by"`
	MaxAttempts      int32              `json:"max_attempts"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) CreateProbeJob(ctx context.Context, arg CreateProbeJobParams) (TargetProbeJob, error) {
	row := q.db.QueryRow(ctx, createProbeJob,
		arg.PreviousJobID,
		arg.AssetID,
		arg.EndpointRevision,
		arg.Protocol,
		arg.Reason,
		arg.RequestedBy,
		arg.MaxAttempts,
		arg.NextAttemptAt,
	)
	var i TargetProbeJob
	err := row.Scan(
		&i.ID,
		&i.PreviousJobID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.Protocol,
		&i.State,
		&i.Reason,
		&i.RequestedBy,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseWorkerID,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.FailureCategory,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAssetVerificationStatus = `-- name: GetAssetVerificationStatus :one
WITH current_asset AS (
    SELECT id, endpoint_revision
    FROM assets
    WHERE id = $2
), latest_observation AS (
    SELECT observation.id, observation.job_id, observation.asset_id, observation.endpoint_revision, observation.worker_id, observation.source, observation.resolved_addresses, observation.protocol_metadata, observation.observed_at, observation.outcome, observation.validation_state, observation.failure_category, observation.failure_detail
    FROM target_identity_observations observation
    JOIN current_asset asset
      ON asset.id = observation.asset_id
     AND asset.endpoint_revision = observation.endpoint_revision
    ORDER BY observation.observed_at DESC, observation.id DESC
    LIMIT 1
), latest_terminal_job AS (
    SELECT job.id, job.previous_job_id, job.asset_id, job.endpoint_revision, job.protocol, job.state, job.reason, job.requested_by, job.attempt_count, job.max_attempts, job.next_attempt_at, job.lease_worker_id, job.lease_token_hash, job.lease_expires_at, job.failure_category, job.failure_detail, job.created_at, job.started_at, job.completed_at
    FROM target_probe_jobs job
    JOIN current_asset asset
      ON asset.id = job.asset_id
     AND asset.endpoint_revision = job.endpoint_revision
    WHERE job.state IN ('succeeded','failed','superseded','cancelled')
    ORDER BY job.completed_at DESC, job.id DESC
    LIMIT 1
), active_anchor AS (
    SELECT anchor.id, anchor.asset_id, anchor.endpoint_revision, anchor.kind, anchor.algorithm, anchor.sha256_fingerprint, anchor.public_material, anchor.required_ssh_principals, anchor.required_dns_names, anchor.required_ip_addresses, anchor.source, anchor.observation_id, anchor.approved_by, anchor.approved_at, anchor.not_before, anchor.expires_at, anchor.revoked_at, anchor.revoked_by, anchor.revocation_reason
    FROM target_trust_anchors anchor
    JOIN current_asset asset
      ON asset.id = anchor.asset_id
     AND asset.endpoint_revision = anchor.endpoint_revision
    WHERE anchor.revoked_at IS NULL
      AND anchor.approved_at <= now()
      AND (anchor.not_before IS NULL OR anchor.not_before <= now())
      AND (anchor.expires_at IS NULL OR anchor.expires_at > now())
), matching_identity AS (
    SELECT 1
    FROM latest_observation observation
    JOIN active_anchor anchor
      ON (
          (anchor.kind = 'ssh_host_key'
              AND EXISTS (
                  SELECT 1
                  FROM target_identity_evidence evidence
                  WHERE evidence.observation_id = observation.id
                    AND evidence.kind = 'ssh_host_key'
                    AND anchor.sha256_fingerprint = evidence.sha256_fingerprint
              ))
       OR (anchor.kind = 'ssh_host_ca'
              AND EXISTS (
                  SELECT 1
                  FROM target_identity_validation_facts validation
                  JOIN target_identity_evidence evidence
                    ON evidence.id = validation.evidence_id
                   AND evidence.observation_id = validation.observation_id
                  WHERE validation.observation_id = observation.id
                    AND validation.asset_id = observation.asset_id
                    AND validation.endpoint_revision = observation.endpoint_revision
                    AND validation.anchor_id = anchor.id
                    AND evidence.kind = 'ssh_host_certificate'
                    AND evidence.valid_from IS NOT NULL
                    AND evidence.valid_until IS NOT NULL
                    AND evidence.valid_from <= now()
                    AND evidence.valid_until > now()
                    AND (
                        cardinality(anchor.required_ssh_principals) = 0
                        OR anchor.required_ssh_principals && evidence.ssh_principals
                    )
              ))
       OR (anchor.kind = 'tls_leaf'
              AND EXISTS (
                  SELECT 1
                  FROM target_identity_evidence evidence
                  WHERE evidence.observation_id = observation.id
                    AND evidence.kind = 'tls_leaf'
                    AND anchor.sha256_fingerprint = evidence.sha256_fingerprint
                    AND evidence.valid_from IS NOT NULL
                    AND evidence.valid_until IS NOT NULL
                    AND evidence.valid_from <= now()
                    AND evidence.valid_until > now()
                    AND (
                        cardinality(anchor.required_dns_names) = 0
                        OR anchor.required_dns_names && evidence.dns_names
                    )
                    AND (
                        cardinality(anchor.required_ip_addresses) = 0
                        OR anchor.required_ip_addresses && evidence.ip_addresses
                    )
              ))
       OR (anchor.kind = 'tls_ca'
              AND EXISTS (
                  SELECT 1
                  FROM target_identity_validation_facts validation
                  JOIN target_identity_evidence leaf
                    ON leaf.id = validation.evidence_id
                   AND leaf.observation_id = validation.observation_id
                  WHERE validation.observation_id = observation.id
                    AND validation.asset_id = observation.asset_id
                    AND validation.endpoint_revision = observation.endpoint_revision
                    AND validation.anchor_id = anchor.id
                    AND leaf.kind = 'tls_leaf'
                    AND leaf.valid_from IS NOT NULL
                    AND leaf.valid_until IS NOT NULL
                    AND leaf.valid_from <= now()
                    AND leaf.valid_until > now()
                    AND (
                        cardinality(anchor.required_dns_names) = 0
                        OR anchor.required_dns_names && leaf.dns_names
                    )
                    AND (
                        cardinality(anchor.required_ip_addresses) = 0
                        OR anchor.required_ip_addresses && leaf.ip_addresses
                    )
              ))
     )
    LIMIT 1
)
SELECT
    asset.id AS asset_id,
    asset.endpoint_revision,
    CASE
        WHEN observation.outcome = 'mismatch' THEN 'identity_changed'
        WHEN observation.outcome = 'succeeded'
             AND EXISTS (SELECT 1 FROM matching_identity)
             AND $1::timestamptz IS NOT NULL
             AND observation.observed_at < $1::timestamptz
            THEN 'verification_expired'
        WHEN observation.outcome = 'succeeded' AND EXISTS (SELECT 1 FROM matching_identity) THEN 'verified'
        WHEN observation.outcome = 'succeeded' AND EXISTS (SELECT 1 FROM active_anchor) THEN 'identity_changed'
        WHEN observation.outcome = 'succeeded' THEN 'awaiting_approval'
        WHEN job.state = 'failed'
             AND (observation.observed_at IS NULL OR job.completed_at >= observation.observed_at)
            THEN 'probe_failed'
        ELSE 'pending_verification'
    END::text AS verification_status,
    observation.id AS latest_observation_id,
    job.id AS latest_probe_job_id
FROM current_asset asset
LEFT JOIN latest_observation observation ON true
LEFT JOIN latest_terminal_job job ON true
`

type GetAssetVerificationStatusParams struct {
	FreshnessCutoff pgtype.Timestamptz `json:"freshness_cutoff"`
	AssetID         pgtype.UUID        `json:"asset_id"`
}

type GetAssetVerificationStatusRow struct {
	AssetID             uuid.UUID   `json:"asset_id"`
	EndpointRevision    int64       `json:"endpoint_revision"`
	VerificationStatus  string      `json:"verification_status"`
	LatestObservationID pgtype.UUID `json:"latest_observation_id"`
	LatestProbeJobID    pgtype.UUID `json:"latest_probe_job_id"`
}

func (q *Queries) GetAssetVerificationStatus(ctx context.Context, arg GetAssetVerificationStatusParams) (GetAssetVerificationStatusRow, error) {
	row := q.db.QueryRow(ctx, getAssetVerificationStatus, arg.FreshnessCutoff, arg.AssetID)
	var i GetAssetVerificationStatusRow
	err := row.Scan(
		&i.AssetID,
		&i.EndpointRevision,
		&i.VerificationStatus,
		&i.LatestObservationID,
		&i.LatestProbeJobID,
	)
	return i, err
}

const getCompletedAttemptOutcome = `-- name: GetCompletedAttemptOutcome :one
SELECT outcome
FROM target_probe_attempts
WHERE job_id = $1
  AND worker_id = $2
  AND lease_token_hash = $3
  AND completed_at IS NOT NULL
ORDER BY attempt_number DESC
LIMIT 1
`

type GetCompletedAttemptOutcomeParams struct {
	JobID          uuid.UUID `json:"job_id"`
	WorkerID       string    `json:"worker_id"`
	LeaseTokenHash []byte    `json:"lease_token_hash"`
}

func (q *Queries) GetCompletedAttemptOutcome(ctx context.Context, arg GetCompletedAttemptOutcomeParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCompletedAttemptOutcome, arg.JobID, arg.WorkerID, arg.LeaseTokenHash)
	var outcome pgtype.Text
	err := row.Scan(&outcome)
	return outcome, err
}

const getIdentityEvidenceForApproval = `-- name: GetIdentityEvidenceForApproval :one
SELECT evidence.id, evidence.observation_id, evidence.kind, evidence.algorithm, evidence.sha256_fingerprint, evidence.public_material, evidence.certificate_subject, evidence.certificate_issuer, evidence.issuer_sha256_fingerprint, evidence.dns_names, evidence.ip_addresses, evidence.ssh_principals, evidence.serial_number, evidence.valid_from, evidence.valid_until, evidence.key_metadata, evidence.display_extensions, evidence.created_at
FROM target_identity_evidence evidence
WHERE evidence.id = $1
  AND evidence.observation_id = $2
`

type GetIdentityEvidenceForApprovalParams struct {
	EvidenceID    uuid.UUID `json:"evidence_id"`
	ObservationID uuid.UUID `json:"observation_id"`
}

func (q *Queries) GetIdentityEvidenceForApproval(ctx context.Context, arg GetIdentityEvidenceForApprovalParams) (TargetIdentityEvidence, error) {
	row := q.db.QueryRow(ctx, getIdentityEvidenceForApproval, arg.EvidenceID, arg.ObservationID)
	var i TargetIdentityEvidence
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.Kind,
		&i.Algorithm,
		&i.Sha256Fingerprint,
		&i.PublicMaterial,
		&i.CertificateSubject,
		&i.CertificateIssuer,
		&i.IssuerSha256Fingerprint,
		&i.DnsNames,
		&i.IpAddresses,
		&i.SshPrincipals,
		&i.SerialNumber,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.KeyMetadata,
		&i.DisplayExtensions,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTerminalProbeJob = `-- name: GetLatestTerminalProbeJob :one
SELECT state, completed_at
FROM target_probe_jobs
WHERE asset_id = $1
  AND endpoint_revision = $2
  AND state IN ('succeeded','failed','superseded','cancelled')
ORDER BY completed_at DESC, id DESC
LIMIT 1
`

type GetLatestTerminalProbeJobParams struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

type GetLatestTerminalProbeJobRow struct {
	State       string             `json:"state"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetLatestTerminalProbeJob(ctx context.Context, arg GetLatestTerminalProbeJobParams) (GetLatestTerminalProbeJobRow, error) {
	row := q.db.QueryRow(ctx, getLatestTerminalProbeJob, arg.AssetID, arg.EndpointRevision)
	var i GetLatestTerminalProbeJobRow
	err := row.Scan(&i.State, &i.CompletedAt)
	return i, err
}

const getPreviousProbeJobState = `-- name: GetPreviousProbeJobState :one
SELECT state
FROM target_probe_jobs
WHERE id = $1
  AND asset_id = $2
  AND endpoint_revision = $3
`

type GetPreviousProbeJobStateParams struct {
	JobID            uuid.UUID `json:"job_id"`
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

func (q *Queries) GetPreviousProbeJobState(ctx context.Context, arg GetPreviousProbeJobStateParams) (string, error) {
	row := q.db.QueryRow(ctx, getPreviousProbeJobState, arg.JobID, arg.AssetID, arg.EndpointRevision)
	var state string
	err := row.Scan(&state)
	return state, err
}

const getValidationEvidence = `-- name: GetValidationEvidence :one
SELECT kind, valid_from, valid_until
FROM target_identity_evidence
WHERE id = $1
  AND observation_id = $2
`

type GetValidationEvidenceParams struct {
	EvidenceID    uuid.UUID `json:"evidence_id"`
	ObservationID uuid.UUID `json:"observation_id"`
}

type GetValidationEvidenceRow struct {
	Kind       string             `json:"kind"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
}

func (q *Queries) GetValidationEvidence(ctx context.Context, arg GetValidationEvidenceParams) (GetValidationEvidenceRow, error) {
	row := q.db.QueryRow(ctx, getValidationEvidence, arg.EvidenceID, arg.ObservationID)
	var i GetValidationEvidenceRow
	err := row.Scan(&i.Kind, &i.ValidFrom, &i.ValidUntil)
	return i, err
}

const incrementAssetEndpointRevision = `-- name: IncrementAssetEndpointRevision :one
UPDATE assets
SET endpoint_revision = endpoint_revision + 1
WHERE id = $1
RETURNING endpoint_revision
`

func (q *Queries) IncrementAssetEndpointRevision(ctx context.Context, assetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, incrementAssetEndpointRevision, assetID)
	var endpoint_revision int64
	err := row.Scan(&endpoint_revision)
	return endpoint_revision, err
}

const insertIdentityEvidence = `-- name: InsertIdentityEvidence :one
INSERT INTO target_identity_evidence (
    observation_id,
    kind,
    algorithm,
    sha256_fingerprint,
    public_material,
    certificate_subject,
    certificate_issuer,
    issuer_sha256_fingerprint,
    dns_names,
    ip_addresses,
    ssh_principals,
    serial_number,
    valid_from,
    valid_until,
    key_metadata,
    display_extensions
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::text,
    $7::text,
    $8::text,
    $9,
    $10,
    $11,
    $12::text,
    $13::timestamptz,
    $14::timestamptz,
    $15,
    $16
)
RETURNING id, observation_id, kind, algorithm, sha256_fingerprint, public_material, certificate_subject, certificate_issuer, issuer_sha256_fingerprint, dns_names, ip_addresses, ssh_principals, serial_number, valid_from, valid_until, key_metadata, display_extensions, created_at
`

type InsertIdentityEvidenceParams struct {
	ObservationID           uuid.UUID          `json:"observation_id"`
	Kind                    string             `json:"kind"`
	Algorithm               string             `json:"algorithm"`
	Sha256Fingerprint       string             `json:"sha256_fingerprint"`
	PublicMaterial          string             `json:"public_material"`
	CertificateSubject      pgtype.Text        `json:"certificate_subject"`
	CertificateIssuer       pgtype.Text        `json:"certificate_issuer"`
	IssuerSha256Fingerprint pgtype.Text        `json:"issuer_sha256_fingerprint"`
	DnsNames                []string           `json:"dns_names"`
	IpAddresses             []string           `json:"ip_addresses"`
	SshPrincipals           []string           `json:"ssh_principals"`
	SerialNumber            pgtype.Text        `json:"serial_number"`
	ValidFrom               pgtype.Timestamptz `json:"valid_from"`
	ValidUntil              pgtype.Timestamptz `json:"valid_until"`
	KeyMetadata             []byte             `json:"key_metadata"`
	DisplayExtensions       []byte             `json:"display_extensions"`
}

func (q *Queries) InsertIdentityEvidence(ctx context.Context, arg InsertIdentityEvidenceParams) (TargetIdentityEvidence, error) {
	row := q.db.QueryRow(ctx, insertIdentityEvidence,
		arg.ObservationID,
		arg.Kind,
		arg.Algorithm,
		arg.Sha256Fingerprint,
		arg.PublicMaterial,
		arg.CertificateSubject,
		arg.CertificateIssuer,
		arg.IssuerSha256Fingerprint,
		arg.DnsNames,
		arg.IpAddresses,
		arg.SshPrincipals,
		arg.SerialNumber,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.KeyMetadata,
		arg.DisplayExtensions,
	)
	var i TargetIdentityEvidence
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.Kind,
		&i.Algorithm,
		&i.Sha256Fingerprint,
		&i.PublicMaterial,
		&i.CertificateSubject,
		&i.CertificateIssuer,
		&i.IssuerSha256Fingerprint,
		&i.DnsNames,
		&i.IpAddresses,
		&i.SshPrincipals,
		&i.SerialNumber,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.KeyMetadata,
		&i.DisplayExtensions,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdentityObservation = `-- name: InsertIdentityObservation :one
INSERT INTO target_identity_observations (
    job_id,
    asset_id,
    endpoint_revision,
    worker_id,
    source,
    resolved_addresses,
    protocol_metadata,
    observed_at,
    outcome,
    validation_state,
    failure_category,
    failure_detail
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::text,
    $12::text
)
RETURNING id, job_id, asset_id, endpoint_revision, worker_id, source, resolved_addresses, protocol_metadata, observed_at, outcome, validation_state, failure_category, failure_detail
`

type InsertIdentityObservationParams struct {
	JobID             pgtype.UUID        `json:"job_id"`
	AssetID           uuid.UUID          `json:"asset_id"`
	EndpointRevision  int64              `json:"endpoint_revision"`
	WorkerID          string             `json:"worker_id"`
	Source            string             `json:"source"`
	ResolvedAddresses []byte             `json:"resolved_addresses"`
	ProtocolMetadata  []byte             `json:"protocol_metadata"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	Outcome           string             `json:"outcome"`
	ValidationState   string             `json:"validation_state"`
	FailureCategory   pgtype.Text        `json:"failure_category"`
	FailureDetail     pgtype.Text        `json:"failure_detail"`
}

func (q *Queries) InsertIdentityObservation(ctx context.Context, arg InsertIdentityObservationParams) (TargetIdentityObservation, error) {
	row := q.db.QueryRow(ctx, insertIdentityObservation,
		arg.JobID,
		arg.AssetID,
		arg.EndpointRevision,
		arg.WorkerID,
		arg.Source,
		arg.ResolvedAddresses,
		arg.ProtocolMetadata,
		arg.ObservedAt,
		arg.Outcome,
		arg.ValidationState,
		arg.FailureCategory,
		arg.FailureDetail,
	)
	var i TargetIdentityObservation
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.WorkerID,
		&i.Source,
		&i.ResolvedAddresses,
		&i.ProtocolMetadata,
		&i.ObservedAt,
		&i.Outcome,
		&i.ValidationState,
		&i.FailureCategory,
		&i.FailureDetail,
	)
	return i, err
}

const insertIdentityValidationFact = `-- name: InsertIdentityValidationFact :exec
INSERT INTO target_identity_validation_facts (
    observation_id, asset_id, endpoint_revision, anchor_id, evidence_id
)
VALUES (
    $1, $2,
    $3, $4, $5
)
`

type InsertIdentityValidationFactParams struct {
	ObservationID    uuid.UUID `json:"observation_id"`
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
	AnchorID         uuid.UUID `json:"anchor_id"`
	EvidenceID       uuid.UUID `json:"evidence_id"`
}

func (q *Queries) InsertIdentityValidationFact(ctx context.Context, arg InsertIdentityValidationFactParams) error {
	_, err := q.db.Exec(ctx, insertIdentityValidationFact,
		arg.ObservationID,
		arg.AssetID,
		arg.EndpointRevision,
		arg.AnchorID,
		arg.EvidenceID,
	)
	return err
}

const isObservationApprovedActive = `-- name: IsObservationApprovedActive :one
SELECT EXISTS (
    SELECT 1
    FROM target_trust_anchors
    WHERE asset_id = $1
      AND endpoint_revision = $2
      AND observation_id = $3
      AND revoked_at IS NULL
      AND approved_at <= $4::timestamptz
      AND (not_before IS NULL OR not_before <= $4::timestamptz)
      AND (expires_at IS NULL OR expires_at > $4::timestamptz)
)
`

type IsObservationApprovedActiveParams struct {
	AssetID          uuid.UUID   `json:"asset_id"`
	EndpointRevision int64       `json:"endpoint_revision"`
	ObservationID    pgtype.UUID `json:"observation_id"`
	AtTime           time.Time   `json:"at_time"`
}

func (q *Queries) IsObservationApprovedActive(ctx context.Context, arg IsObservationApprovedActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isObservationApprovedActive,
		arg.AssetID,
		arg.EndpointRevision,
		arg.ObservationID,
		arg.AtTime,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isObservationRejected = `-- name: IsObservationRejected :one
SELECT EXISTS (
    SELECT 1 FROM audit_outbox
    WHERE event_type = 'target_identity.observation_rejected'
      AND subject = $1
      AND details->>'observation_id' = $2::text
    UNION ALL
    SELECT 1 FROM audit_log
    WHERE event_type = 'target_identity.observation_rejected'
      AND subject = $1
      AND details->>'observation_id' = $2::text
)
`

type IsObservationRejectedParams struct {
	Subject       pgtype.Text `json:"subject"`
	ObservationID pgtype.Text `json:"observation_id"`
}

func (q *Queries) IsObservationRejected(ctx context.Context, arg IsObservationRejectedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isObservationRejected, arg.Subject, arg.ObservationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCurrentActiveTrustAnchors = `-- name: ListCurrentActiveTrustAnchors :many
SELECT anchor.id, anchor.asset_id, anchor.endpoint_revision, anchor.kind, anchor.algorithm, anchor.sha256_fingerprint, anchor.public_material, anchor.required_ssh_principals, anchor.required_dns_names, anchor.required_ip_addresses, anchor.source, anchor.observation_id, anchor.approved_by, anchor.approved_at, anchor.not_before, anchor.expires_at, anchor.revoked_at, anchor.revoked_by, anchor.revocation_reason
FROM target_trust_anchors anchor
JOIN assets asset
  ON asset.id = anchor.asset_id
 AND asset.endpoint_revision = anchor.endpoint_revision
WHERE anchor.asset_id = $1
  AND anchor.revoked_at IS NULL
  AND anchor.approved_at <= $2::timestamptz
  AND (anchor.not_before IS NULL OR anchor.not_before <= $2::timestamptz)
  AND (anchor.expires_at IS NULL OR anchor.expires_at > $2::timestamptz)
ORDER BY anchor.approved_at, anchor.id
`

type ListCurrentActiveTrustAnchorsParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	AtTime  time.Time `json:"at_time"`
}

func (q *Queries) ListCurrentActiveTrustAnchors(ctx context.Context, arg ListCurrentActiveTrustAnchorsParams) ([]TargetTrustAnchor, error) {
	rows, err := q.db.Query(ctx, listCurrentActiveTrustAnchors, arg.AssetID, arg.AtTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetTrustAnchor
	for rows.Next() {
		var i TargetTrustAnchor
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.EndpointRevision,
			&i.Kind,
			&i.Algorithm,
			&i.Sha256Fingerprint,
			&i.PublicMaterial,
			&i.RequiredSshPrincipals,
			&i.RequiredDnsNames,
			&i.RequiredIpAddresses,
			&i.Source,
			&i.ObservationID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.NotBefore,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevocationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEvidence = `-- name: ListIdentityEvidence :many
SELECT evidence.id, evidence.observation_id, evidence.kind, evidence.algorithm, evidence.sha256_fingerprint, evidence.public_material, evidence.certificate_subject, evidence.certificate_issuer, evidence.issuer_sha256_fingerprint, evidence.dns_names, evidence.ip_addresses, evidence.ssh_principals, evidence.serial_number, evidence.valid_from, evidence.valid_until, evidence.key_metadata, evidence.display_extensions, evidence.created_at
FROM target_identity_evidence evidence
JOIN target_identity_observations observation ON observation.id = evidence.observation_id
WHERE observation.asset_id = $1
  AND observation.endpoint_revision = $2
ORDER BY observation.observed_at, evidence.created_at, evidence.id
`

type ListIdentityEvidenceParams struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

func (q *Queries) ListIdentityEvidence(ctx context.Context, arg ListIdentityEvidenceParams) ([]TargetIdentityEvidence, error) {
	rows, err := q.db.Query(ctx, listIdentityEvidence, arg.AssetID, arg.EndpointRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetIdentityEvidence
	for rows.Next() {
		var i TargetIdentityEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ObservationID,
			&i.Kind,
			&i.Algorithm,
			&i.Sha256Fingerprint,
			&i.PublicMaterial,
			&i.CertificateSubject,
			&i.CertificateIssuer,
			&i.IssuerSha256Fingerprint,
			&i.DnsNames,
			&i.IpAddresses,
			&i.SshPrincipals,
			&i.SerialNumber,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.KeyMetadata,
			&i.DisplayExtensions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusObservations = `-- name: ListStatusObservations :many
SELECT id, observed_at, outcome
FROM target_identity_observations
WHERE asset_id = $1
  AND endpoint_revision = $2
ORDER BY observed_at DESC, id DESC
`

type ListStatusObservationsParams struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

type ListStatusObservationsRow struct {
	ID         uuid.UUID `json:"id"`
	ObservedAt time.Time `json:"observed_at"`
	Outcome    string    `json:"outcome"`
}

func (q *Queries) ListStatusObservations(ctx context.Context, arg ListStatusObservationsParams) ([]ListStatusObservationsRow, error) {
	rows, err := q.db.Query(ctx, listStatusObservations, arg.AssetID, arg.EndpointRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatusObservationsRow
	for rows.Next() {
		var i ListStatusObservationsRow
		if err := rows.Scan(&i.ID, &i.ObservedAt, &i.Outcome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustAnchors = `-- name: ListTrustAnchors :many
SELECT anchor.id, anchor.asset_id, anchor.endpoint_revision, anchor.kind, anchor.algorithm, anchor.sha256_fingerprint, anchor.public_material, anchor.required_ssh_principals, anchor.required_dns_names, anchor.required_ip_addresses, anchor.source, anchor.observation_id, anchor.approved_by, anchor.approved_at, anchor.not_before, anchor.expires_at, anchor.revoked_at, anchor.revoked_by, anchor.revocation_reason
FROM target_trust_anchors anchor
WHERE anchor.asset_id = $1
ORDER BY anchor.approved_at, anchor.id
`

func (q *Queries) ListTrustAnchors(ctx context.Context, assetID uuid.UUID) ([]TargetTrustAnchor, error) {
	rows, err := q.db.Query(ctx, listTrustAnchors, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetTrustAnchor
	for rows.Next() {
		var i TargetTrustAnchor
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.EndpointRevision,
			&i.Kind,
			&i.Algorithm,
			&i.Sha256Fingerprint,
			&i.PublicMaterial,
			&i.RequiredSshPrincipals,
			&i.RequiredDnsNames,
			&i.RequiredIpAddresses,
			&i.Source,
			&i.ObservationID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.NotBefore,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevocationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProbeCompletion = `-- name: LockProbeCompletion :one
SELECT job.asset_id,
       job.endpoint_revision AS job_endpoint_revision,
       asset.endpoint_revision AS asset_endpoint_revision,
       job.protocol
FROM target_probe_jobs job
JOIN assets asset ON asset.id = job.asset_id
WHERE job.id = $1
FOR UPDATE OF job, asset
`

type LockProbeCompletionRow struct {
	AssetID               uuid.UUID `json:"asset_id"`
	JobEndpointRevision   int64     `json:"job_endpoint_revision"`
	AssetEndpointRevision int64     `json:"asset_endpoint_revision"`
	Protocol              string    `json:"protocol"`
}

func (q *Queries) LockProbeCompletion(ctx context.Context, jobID uuid.UUID) (LockProbeCompletionRow, error) {
	row := q.db.QueryRow(ctx, lockProbeCompletion, jobID)
	var i LockProbeCompletionRow
	err := row.Scan(
		&i.AssetID,
		&i.JobEndpointRevision,
		&i.AssetEndpointRevision,
		&i.Protocol,
	)
	return i, err
}

const lockTargetIdentityAsset = `-- name: LockTargetIdentityAsset :one
SELECT endpoint_revision, kind
FROM assets
WHERE id = $1
FOR UPDATE
`

type LockTargetIdentityAssetRow struct {
	EndpointRevision int64  `json:"endpoint_revision"`
	Kind             string `json:"kind"`
}

func (q *Queries) LockTargetIdentityAsset(ctx context.Context, assetID uuid.UUID) (LockTargetIdentityAssetRow, error) {
	row := q.db.QueryRow(ctx, lockTargetIdentityAsset, assetID)
	var i LockTargetIdentityAssetRow
	err := row.Scan(&i.EndpointRevision, &i.Kind)
	return i, err
}

const lockTargetIdentityObservation = `-- name: LockTargetIdentityObservation :one
SELECT outcome
FROM target_identity_observations
WHERE id = $1
  AND asset_id = $2
  AND endpoint_revision = $3
FOR UPDATE
`

type LockTargetIdentityObservationParams struct {
	ObservationID    uuid.UUID `json:"observation_id"`
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
}

func (q *Queries) LockTargetIdentityObservation(ctx context.Context, arg LockTargetIdentityObservationParams) (string, error) {
	row := q.db.QueryRow(ctx, lockTargetIdentityObservation, arg.ObservationID, arg.AssetID, arg.EndpointRevision)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const observationMatchesCurrentAnchors = `-- name: ObservationMatchesCurrentAnchors :one
SELECT EXISTS (
    SELECT 1
    FROM target_trust_anchors anchor
    WHERE anchor.asset_id = $1
      AND anchor.endpoint_revision = $2
      AND anchor.revoked_at IS NULL
      AND anchor.approved_at <= $3::timestamptz
      AND (anchor.not_before IS NULL OR anchor.not_before <= $3::timestamptz)
      AND (anchor.expires_at IS NULL OR anchor.expires_at > $3::timestamptz)
      AND (
          (anchor.kind = 'ssh_host_key' AND EXISTS (
              SELECT 1 FROM target_identity_evidence evidence
              WHERE evidence.observation_id = $4
                AND evidence.kind = 'ssh_host_key'
                AND evidence.sha256_fingerprint = anchor.sha256_fingerprint
          ))
       OR (anchor.kind = 'tls_leaf' AND EXISTS (
              SELECT 1 FROM target_identity_evidence evidence
              WHERE evidence.observation_id = $4
                AND evidence.kind = 'tls_leaf'
                AND evidence.sha256_fingerprint = anchor.sha256_fingerprint
                AND evidence.valid_from IS NOT NULL AND evidence.valid_until IS NOT NULL
                AND evidence.valid_from <= $3::timestamptz
                AND evidence.valid_until > $3::timestamptz
                AND (cardinality(anchor.required_dns_names) = 0 OR anchor.required_dns_names && evidence.dns_names)
                AND (cardinality(anchor.required_ip_addresses) = 0 OR anchor.required_ip_addresses && evidence.ip_addresses)
          ))
       OR (anchor.kind = 'ssh_host_ca' AND EXISTS (
              SELECT 1
              FROM target_identity_validation_facts validation
              JOIN target_identity_evidence evidence
                ON evidence.id = validation.evidence_id
               AND evidence.observation_id = validation.observation_id
              WHERE validation.observation_id = $4
                AND validation.anchor_id = anchor.id
                AND evidence.kind = 'ssh_host_certificate'
                AND evidence.valid_from IS NOT NULL AND evidence.valid_until IS NOT NULL
                AND evidence.valid_from <= $3::timestamptz
                AND evidence.valid_until > $3::timestamptz
                AND (cardinality(anchor.required_ssh_principals) = 0 OR anchor.required_ssh_principals && evidence.ssh_principals)
          ))
       OR (anchor.kind = 'tls_ca' AND EXISTS (
              SELECT 1
              FROM target_identity_validation_facts validation
              JOIN target_identity_evidence evidence
                ON evidence.id = validation.evidence_id
               AND evidence.observation_id = validation.observation_id
              WHERE validation.observation_id = $4
                AND validation.anchor_id = anchor.id
                AND evidence.kind = 'tls_leaf'
                AND evidence.valid_from IS NOT NULL AND evidence.valid_until IS NOT NULL
                AND evidence.valid_from <= $3::timestamptz
                AND evidence.valid_until > $3::timestamptz
                AND (cardinality(anchor.required_dns_names) = 0 OR anchor.required_dns_names && evidence.dns_names)
                AND (cardinality(anchor.required_ip_addresses) = 0 OR anchor.required_ip_addresses && evidence.ip_addresses)
          ))
      )
)
`

type ObservationMatchesCurrentAnchorsParams struct {
	AssetID          uuid.UUID `json:"asset_id"`
	EndpointRevision int64     `json:"endpoint_revision"`
	AtTime           time.Time `json:"at_time"`
	ObservationID    uuid.UUID `json:"observation_id"`
}

func (q *Queries) ObservationMatchesCurrentAnchors(ctx context.Context, arg ObservationMatchesCurrentAnchorsParams) (bool, error) {
	row := q.db.QueryRow(ctx, observationMatchesCurrentAnchors,
		arg.AssetID,
		arg.EndpointRevision,
		arg.AtTime,
		arg.ObservationID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeTrustAnchor = `-- name: RevokeTrustAnchor :one
UPDATE target_trust_anchors
SET revoked_at = $1,
    revoked_by = $2::uuid,
    revocation_reason = $3::text
WHERE id = $4
  AND asset_id = $5
  AND revoked_at IS NULL
RETURNING id, asset_id, endpoint_revision, kind, algorithm, sha256_fingerprint, public_material, required_ssh_principals, required_dns_names, required_ip_addresses, source, observation_id, approved_by, approved_at, not_before, expires_at, revoked_at, revoked_by, revocation_reason
`

type RevokeTrustAnchorParams struct {
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy        pgtype.UUID        `json:"revoked_by"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
	AnchorID         uuid.UUID          `json:"anchor_id"`
	AssetID          uuid.UUID          `json:"asset_id"`
}

func (q *Queries) RevokeTrustAnchor(ctx context.Context, arg RevokeTrustAnchorParams) (TargetTrustAnchor, error) {
	row := q.db.QueryRow(ctx, revokeTrustAnchor,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevocationReason,
		arg.AnchorID,
		arg.AssetID,
	)
	var i TargetTrustAnchor
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EndpointRevision,
		&i.Kind,
		&i.Algorithm,
		&i.Sha256Fingerprint,
		&i.PublicMaterial,
		&i.RequiredSshPrincipals,
		&i.RequiredDnsNames,
		&i.RequiredIpAddresses,
		&i.Source,
		&i.ObservationID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevocationReason,
	)
	return i, err
}

const targetIdentityDatabaseTime = `-- name: TargetIdentityDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) TargetIdentityDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, targetIdentityDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}
