// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCAKey = `-- name: CreateCAKey :one
INSERT INTO ca_keys (kind, sealed, public_material) VALUES ($1, $2, $3) RETURNING id, kind, sealed, public_material, created_at, active
`

type CreateCAKeyParams struct {
	Kind           string `json:"kind"`
	Sealed         []byte `json:"sealed"`
	PublicMaterial string `json:"public_material"`
}

func (q *Queries) CreateCAKey(ctx context.Context, arg CreateCAKeyParams) (CaKey, error) {
	row := q.db.QueryRow(ctx, createCAKey, arg.Kind, arg.Sealed, arg.PublicMaterial)
	var i CaKey
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Sealed,
		&i.PublicMaterial,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const deleteAssetSecret = `-- name: DeleteAssetSecret :exec
DELETE FROM asset_secrets WHERE id = $1
`

func (q *Queries) DeleteAssetSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetSecret, id)
	return err
}

const getActiveCA = `-- name: GetActiveCA :one
SELECT id, kind, sealed, public_material, created_at, active FROM ca_keys WHERE kind = $1 AND active
`

func (q *Queries) GetActiveCA(ctx context.Context, kind string) (CaKey, error) {
	row := q.db.QueryRow(ctx, getActiveCA, kind)
	var i CaKey
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Sealed,
		&i.PublicMaterial,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const getAssetSecret = `-- name: GetAssetSecret :one
SELECT id, asset_id, name, sealed, created_at FROM asset_secrets WHERE id = $1 AND asset_id = $2
`

type GetAssetSecretParams struct {
	ID      uuid.UUID `json:"id"`
	AssetID uuid.UUID `json:"asset_id"`
}

// Scoped to the owning asset: a config referencing another asset's secret (admin
// misconfiguration) fails closed rather than leaking a secret cross-asset.
func (q *Queries) GetAssetSecret(ctx context.Context, arg GetAssetSecretParams) (AssetSecret, error) {
	row := q.db.QueryRow(ctx, getAssetSecret, arg.ID, arg.AssetID)
	var i AssetSecret
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Name,
		&i.Sealed,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetSecretByID = `-- name: GetAssetSecretByID :one
SELECT id, asset_id, name, sealed, created_at FROM asset_secrets WHERE id = $1
`

// Loads a secret by id alone (for management scope-derivation → owning asset).
func (q *Queries) GetAssetSecretByID(ctx context.Context, id uuid.UUID) (AssetSecret, error) {
	row := q.db.QueryRow(ctx, getAssetSecretByID, id)
	var i AssetSecret
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Name,
		&i.Sealed,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetSecrets = `-- name: ListAssetSecrets :many
SELECT id, asset_id, name, created_at FROM asset_secrets
WHERE asset_id = $1
  AND (
    $2::text IS NULL
    OR (name, id) > ($2, $3::uuid)
  )
ORDER BY name, id
LIMIT $4
`

type ListAssetSecretsParams struct {
	AssetID   uuid.UUID   `json:"asset_id"`
	AfterName pgtype.Text `json:"after_name"`
	AfterID   pgtype.UUID `json:"after_id"`
	Lim       int64       `json:"lim"`
}

type ListAssetSecretsRow struct {
	ID        uuid.UUID `json:"id"`
	AssetID   uuid.UUID `json:"asset_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListAssetSecrets(ctx context.Context, arg ListAssetSecretsParams) ([]ListAssetSecretsRow, error) {
	rows, err := q.db.Query(ctx, listAssetSecrets,
		arg.AssetID,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetSecretsRow
	for rows.Next() {
		var i ListAssetSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssetSecret = `-- name: SetAssetSecret :one
INSERT INTO asset_secrets (asset_id, name, sealed) VALUES ($1, $2, $3)
ON CONFLICT (asset_id, name) DO UPDATE SET sealed = EXCLUDED.sealed
RETURNING id, asset_id, name, sealed, created_at
`

type SetAssetSecretParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	Name    string    `json:"name"`
	Sealed  []byte    `json:"sealed"`
}

func (q *Queries) SetAssetSecret(ctx context.Context, arg SetAssetSecretParams) (AssetSecret, error) {
	row := q.db.QueryRow(ctx, setAssetSecret, arg.AssetID, arg.Name, arg.Sealed)
	var i AssetSecret
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Name,
		&i.Sealed,
		&i.CreatedAt,
	)
	return i, err
}
