{{- range $c := list "warden" "gateway" "ssh-proxy" "pg-proxy" "rdp-proxy" "k8s-broker" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jumpgate.fullname" $ }}-{{ $c }}
  labels:
    {{- include "jumpgate.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $c }}
automountServiceAccountToken: false
{{- end }}
